### ISSUE TITLE
Option for exporting colspan?

### ISSUE THREAD

**Issue by p00tster** [hhurz/tableExport.jquery.plugin#10]
I guess this isn't so much of an issue as it is a question.  I am exporting a table and everything is working correctly except for one thing and I can't figure out how to make it work correctly:

My table has a header row with a colspan set to the number of columns in the rest of the table (i.e. the header row takes up the entire width of the table, while the rest of my table rows have 5 columns).  However, when I export to Excel, the colspan doesn't carry over and only drops the header row into a single cell.

Any suggestions?

**Comment by p00tster** [comment]
Nevermind!  I figured it out.  I was able to correct this by modifying this section of code:

```
// Row Vs Column
    var rowCount=1;
    $(el).find('tbody').find(defaults.tbodySelector).each(function() {
      excel += "<tr>";
      var colCount=0;
      $(this).filter(':visible').find('td').each(function(index,data) {
        if ($(this).css('display') != 'none' &&
            $(this).data("tableexport-display") != 'none'){
          if(defaults.ignoreColumn.indexOf(index) == -1){
            excel += "<td style='";
            for( var styles in defaults.excelstyles ) {
              if( defaults.excelstyles.hasOwnProperty(styles) ) {
                excel += defaults.excelstyles[styles] + ": " + $(this).css(defaults.excelstyles[styles]) + ";";
              }
            }
```

under "$(this).filter(':visible').find('td').each(function(index,data) {", I added the following line:

```
var mycolspan = $(this).prop("colSpan");  
```

I then modified "excel += "'>" + parseString(this, rowIndex, index) + "</td>"; to:

```
excel += "' colspan='" + mycolspan + "'>" + parseString(this, rowIndex, index) + "</td>";
```

**Comment by hhurz** [comment]
@p00tster: ty for your suggestion. Added it recently

**Comment by p00tster** [comment]
FYI, I tried using the updated plugin.js file and it's not exporting the colspan.

**Comment by hhurz** [comment]
Just double checked it with Firefox, IE11 and Chrome. The colspan from the test page (test/index.html)

```
<tr>
<td colspan="6">&nbsp;</td>
</tr>
```

was exported successfully.by each browser to

```
<tr>
<td style='border-bottom: ;border-top: ;border-left: ;border-right: ;' colspan='6'></td>
</tr>
```

**Comment by simogeo** [comment]
@ p00tster  : maybe a cache issue ....
