### ISSUE TITLE
multi table export to excel horizontally

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#102]
Currently when try to export multiple tables to an excel files , all the tables are exported below each other meaning vertically , is it also possible to show them next to each other meaning horizontally as well ?

**Comment by hhurz** [comment]
No, thats currently not possible.

**Comment by hhurz** [comment]
Use export type 'excel' with excelFileFormat:'xmlss' to export in XML Spreadsheet 2003 file format that supports multiple worksheets
