### ISSUE TITLE
Export to csv to include leading zero

### ISSUE THREAD

**Issue by aisuhua** [hhurz/tableExport.jquery.plugin#103]
I have seen related topic about it #81 and #94. If i export to excel (.xls) format, it work well.
But, now i export the data to csv format, the leading zero still be removed.
Like:

```
030611 -> 30611
0030610 -> 30610
```

Is that a way to keep the leading zero when exporting the csv format. Thank!

**Comment by hhurz** [comment]
That would require a new csv related option that let you export numbers as text.

**Comment by hhurz** [comment]
Meanwhile leading zeros remain in the exported csv file. But if you try to open the csv file with Excel the zeros get lost again. Thats a well known issue or feature of Excel. You have to cheat Excel so it doesn't strip leading zeros of numbers. 
Here is an example that keeps leading zeros of numbers in the first column of a table:

```javascript
$table.tableExport({
    type: "csv",
    csvSeparator: ';', 
    onCellData: DoOnCellData
});
```
```javascript
function DoOnCellData(cell, row, col, data){
    var result = data;
    if (result != "" && row > 0 && col == 0) {
        result = "\x1F" + data;
    }
    return result;
}
```
The trick is to prepend a non printable character (x1F = unit separator) to the number that you want to export with leading zeros. They will not be removed when you open the csv file with Excel.

**Comment by sangar82** [comment]
Can I have the excel headers of each table in bold??
I'm not able to achieve it. Thanks!!!
