### ISSUE TITLE
After export, browser's page is changed

### ISSUE THREAD

**Issue by mashbash** [hhurz/tableExport.jquery.plugin#105]
Browser: Chrome 
OS: Ubuntu 16.04

After exporting to xls, the data in the tables in my browser are reset to 0. In pages where I use AJAX to dynamically create input fields based on previous selections, these fields do not show after export as well. 

Is there a way for me to have the browser page remain as is (with all the data, dynamically generated input-fields etc.) even after the export? Thanks.

**Comment by hhurz** [comment]
I'm not sure if this plugn is really responsible for what you are observing. Without any example code (e.g. fiddle or like that) I can only guess. Beside that, I'd suggest you offer a separate print/export page that shows the results of your page in a clean non active table and then let the user export this page.

**Comment by mashbash** [comment]
After looking into this, it seems that the td values are reset when it is in FileSaver.js. Thanks for your suggestion, I will look into giving that a try.
