### ISSUE TITLE
Excel Export: CSS counter not showing

### ISSUE THREAD

**Issue by mashbash** [hhurz/tableExport.jquery.plugin#106]
Browser: Chrome
OS: Ubuntu 16.04
LibreOffice 5

I have a table where I use the CSS counter to list the index numbers, but when I export, I don't see these values in the excel file.

I've tried setting the option excelstyles: ['content']. Please let me know how I should go about setting this correctly?

**Comment by hhurz** [comment]
An example would be fine...

**Comment by mashbash** [comment]
Please check out this [example](https://jsfiddle.net/8z9203w3/)

**Comment by hhurz** [comment]
Thanks for providing that example. CSS counters are not seen when traversing the DOM:

``` javascript
<table class="table table-bordered">
    <thead>
      <tr>
        <td>Index</td>
        <td>Name</td>
        <td>Number</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td>Bob Mash</td>
        <td>123456</td>
      </tr>
      <tr>
        <td></td>
        <td>Peter Cash</td>
        <td>789456</td>
      </tr>
    </tbody>
  </table>
```

As you can see the numbers will be drawn when the browser engine renders the tabel content. Thus the tableExport plugin cannot "see" those counters and cannot export them. 
See also: http://stackoverflow.com/questions/2651739/how-to-access-css-generated-content-with-javascript

**Comment by mashbash** [comment]
Thanks for looking into it and for the link, was helpful to read
