### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by maxwowpow** [hhurz/tableExport.jquery.plugin#11]
well, since this is a web project, bower support would be nice.

**Comment by hhurz** [comment]
Merged your pull request. TY

**Comment by mattgi** [comment]
I had to run this for your package to be available in bower:
`bower register tableExport.jquery.plugin git@github.com:hhurz/tableExport.jquery.plugin.git`
should be good to go now ;) if you use semver versioning tags things will just work
