### ISSUE TITLE
How to show tables next to each other when exporting to pdf in one page 

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#110]
I have 5 tables that i would like to show next to each other when exporting to pdf in a single page.
currently tables are generated below one another , is it possible to have next to each other. 
Something like we do for divs using 'float:left' applied to each div 

If its possible please also show how to do it
More details added :-
Basically what i am looking for is something like 
![additional_information](https://cloud.githubusercontent.com/assets/5576379/18507748/47f09e46-7a8f-11e6-9ab5-f9462dc7223e.png)

**Comment by hhurz** [comment]
There is a working example: https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/sidebyside.html
Please note, that I can't provide more support than this. Any further details or tweaks you have to figure out by yourself. Thanks.

**Comment by nshah143** [comment]
Thank you so much for the help :+1:

**Comment by nshah143** [comment]
Hi @hhurz , 
First of all Thanks again for the support and ideas you provide for the queries of the users.

the above solution provided by you works but still there is one small issue in it.
The tables provided by you in the example are very small , in my case they are having much more data and of irregular sizes (not all tables are of fixed and same size) .

So i have to use **tableWidth: 'wrap'**  in my usage , now the problem appears in the function **doBeforeAutotable** in the lines mentioned below

```
  **settings.margin.left = 10 + settings.tableExport.mytableno * (settings.tableWidth + 10);
  settings.margin.right =  settings.margin.left + settings.tableWidth;**
```

here when i check the value of **settings.tableWidth** it is giving me as **wrap**

So it is not possible to assign the next tables margin automatically in the same pdf page.
So i had to hardcore it to something like 

**var n = settings.tableExport.mytableno;
if(settings.tableExport.mytableno == 5) {
        left_margin = 10;
    settings.tableExport.mytableno = 0;
    settings.tableExport.doc.addPage();
}
settings.startY = 10;
if(n==0) left_margin = 10;
if(n==1) left_margin = 175;
if(n==2) left_margin = 273;
if(n==3) left_margin = 375;
if(n==4) left_margin = 470;
settings.margin.left = left_margin;**

This way i get my desired output in the 1st page , but from next page as the table`s content differ it does not set correctly.

So my question would be is there anyway when using **tableWidth: 'wrap'** i can get the width of the wrapped tables somehow from some other argument or value.

Please check the attached PDF file. ( NOTE: it seems that i am not able to upload the pdf file , i attached the screen shots below.)

![report-page-001](https://cloud.githubusercontent.com/assets/5576379/18605993/68e96b8c-7cbf-11e6-9a65-c25e8fa96cba.jpg)
![report-page-002](https://cloud.githubusercontent.com/assets/5576379/18605994/6d75b174-7cbf-11e6-9196-288fbeca3ddc.jpg)
![report-page-003](https://cloud.githubusercontent.com/assets/5576379/18605995/70e6d37e-7cbf-11e6-82a0-0aea0a41735d.jpg)
![report-page-004](https://cloud.githubusercontent.com/assets/5576379/18605996/74766798-7cbf-11e6-9801-a4a8cdd48e6b.jpg)
![report-page-005](https://cloud.githubusercontent.com/assets/5576379/18605998/7789adc8-7cbf-11e6-96f3-7fc7bc627105.jpg)
![report-page-006](https://cloud.githubusercontent.com/assets/5576379/18605999/7a92259a-7cbf-11e6-9178-856366141077.jpg)

The difference appears from page 3 , 4 , 5 & 6. Even the page 1 & 2 will not work efficient with the static margins bcoz as soon as the values in the table change , the wrapped width will change and so the margin will not be consistent.

**Comment by hhurz** [comment]
You could try to calculate the width of your tables before exporting it and to use this width when calculating the margin. There is an internal(!) function "getPropertyUnitValue" in the plugins source code which I use to calculate the width of a table in pt. It should be easy to make a copy of this function for your use. You would call it then like this: 
var w = myGetPropertyUnitValue($(''#mytable'), 'width', 'pt');
