### ISSUE TITLE
Export pdf with images

### ISSUE THREAD

**Issue by kamov** [hhurz/tableExport.jquery.plugin#111]
hi,
I have a html table with images inside.
I want to export in pdf and table is correctly exported.
only images is not added on pdf.
what is missing?
thanks

**Comment by hhurz** [comment]
Currently there is no support to export images.

**Comment by kamov** [comment]
There is a solution with autotable plugin which I just found, check here this example:

https://codepen.io/someatoms/pen/vLYXWB

**Comment by hhurz** [comment]
@kamov Thanks for pointing me to the solution above. I just released a new version that supports images.

**Comment by chillaz** [comment]
I have no problem with adding images to the .pdf file, but the images need to be reduced to fit the cell. Is there code for the $('#myTable').tableExport.. that I can use to control the width and height of each image? This link https://codepen.io/someatoms/pen/vLYXWB is no solution for me.

**Comment by hhurz** [comment]
The tableExport plugin doesn't support scaling of images. I added this issue to the list of feature requests.

**Comment by chillaz** [comment]
Thank you hhurz. I look forward to this feature and I appreciate you for making this project available for all of us to use.

**Comment by hhurz** [comment]
@chillaz: Your request should be resolved within release 1.6.5. Thanks.
