### ISSUE TITLE
Switch or include PDFmake on the options

### ISSUE THREAD

**Issue by arivera12** [hhurz/tableExport.jquery.plugin#112]
I have been using over year this plugin from the original author. I didn't knew there was a fork from the original repo and maintainers that have been keeping this good project alive with great improvements as I can see. Sometime ago jspdf have been not maintained anymore. I have made some changes to this plugin(tableexport) when exporting to pdf using pdfmake. I will be sharing my code so if your are interested on how this work visit [pdkmake.org](http://pdfmake.org/) and if you want to implement this I will sharing the code to export a table to pdf using pdfmake. For compatibility, I think you should try to keep both, but for more flexible and easy customization pdfmake I think is better cause you don't need to play with X and Y anymore, also it supports images in JPEG and PNG formats without any external plugins and also you can return a base 64 string of the created pdf so you can do something else with it on some server side.
PS. I am not a contributor or don't have any relation with jspdf or pdfmake.

```
//where i is an object for table export options
//var i = {
//                    separator: ",",
//                    ignoreColumn: [],
//                    tableName: "yourTableName",
//                    type: "csv",
//                    pdfFontSize: 14,
//                    pdfLeftMargin: 20,
//                    escape: "true",
//                    htmlContent: "false",
//                    consoleLog: "false"
//                }
// o = this; //tableexport intance
if ("pdf" == i.type) {
                var body = [];
                var h = [];
                var r = [[]];
                e(o).find("thead").find("tr").each(function() {
                    e(this).filter(":visible").find("th").each(function(t, o) {
                        if ("none" != e(this).css("display") && -1 == i.ignoreColumn.indexOf(t)) {
                            h.push(n(e(this)))
                        }
                    })
                });
                body.push(h);
                var index = 0;
                e(o).find("tbody").find("tr").each(function(t, o) {
                    r.push([]), e(this).filter(":visible").find("td").each(function(t, o) {
                        if ("none" != e(this).css("display") && -1 == i.ignoreColumn.indexOf(t)) {
                            r[index].push(n(e(this)))
                        }
                    });
                    body.push(r[index]);
                    index++;
                });
                var widths = [];
                for(var i = 0; i < h.length;i++)
                {
                    widths.push("*");
                }
                var docDefinition = {
                    pageOrientation: 'landscape',
                    content: [
                            {
                              table: {
                                headerRows: 1,
                                widths: widths,
                                body: body
                              }
                            }
                           ]
                };
                pdfMake.createPdf(docDefinition).open();
            }.
```

**Comment by hhurz** [comment]
Thanks for sharing this information. Although my tests with pdfmake didn't convince me to abandon jspdf, I added a new option that lets you optionally use this library. Actually I'm missing advanced styling options in pdfmake, plus there seem to be issues that are already known but not fixed. There is a fork https://github.com/ceczkn/bitpdfmake that covers a couple of issues of the original project, but moves away from the original developement, Anyway, if you want to use pdfmake and make some contributions just include `pdfmake.min.js` and `vfs_fonts.js` and set the new option `pdfmake: {enabled: true}`.

**Comment by arivera12** [comment]
jspdf is very versatile in the way it writes using x and y and all the options available you have on it. But I think to create documents where you only need text and images pdfmake suites better but that is just personal preferences. For general purpose jspdf fits better cause all the options like drawing stuff and html render. But anyways I hope this help for enhancements purpose for this plugin. Take care.
