### ISSUE TITLE
Unable to run "bower install" - js-xlsx got the wrong version number

### ISSUE THREAD

**Issue by duff92** [hhurz/tableExport.jquery.plugin#114]
When trying to update this package, running `bower install`, the follwing error appears:

> bower js-xlsx#0.8.14                    ENORESTARGET No tag found that was able to satisfy 0.8.14
> 
> Additional error details:
> Available versions in https://github.com/SheetJS/js-xlsx.git: 0.8.0, 0.7.11, 0.7.10, 0.7.9, 0.7.7, 0.7.6, 0.7.6-i, 0.7.6-h, 0.7.6-a, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.5.10, 0.5.9, 0.5.8, 0.5.7, 0.5.0, 0.4.3

**Comment by hhurz** [comment]
Thanks for reporting this issue, I just fixed this by removing the js-xslx dependency from bower.json. Actually I want to add a dependency from a fork of the package: https://github.com/protobi/js-xlsx, which current version is 0.8.14, but don't know how to add this to bower.json...

**Comment by duff92** [comment]
@hhurz Thanks for quick support, now it works for me again!

**Comment by talatbaig** [comment]
Hi @hhurz could you do the same for the package.json file please

**Comment by hhurz** [comment]
@talatbaig: Done.
