### ISSUE TITLE
Style building for mso-number-format needs semi-colon at the end.

### ISSUE THREAD

**Issue by Richard-Prins** [hhurz/tableExport.jquery.plugin#115]
When the data-tableexport-msonumberformat attribute is present on a TD in the TBODY with a value, it gets put into a new style attribute, and other css settings (if applicable) get appended. However, there is no semi-colon between the msonumberformat part and other attributes.

I changed line 407:

tdstyle = 'style="mso-number-format:\'' + tdcss + '\'';

to:

tdstyle = 'style="mso-number-format:\'' + tdcss + '\'' + ';';

in order to get them exported correctly.

**Comment by hhurz** [comment]
Thanks for reporting this issue. I reworked the excel stye building code.
