### ISSUE TITLE
Open pdf in new tab?

### ISSUE THREAD

**Issue by surgiie** [hhurz/tableExport.jquery.plugin#117]
Is there a way to export table pdf to a new tab instead of downloading?

**Comment by hhurz** [comment]
Actually this plugin can't (still) do that, but I marked that as a feature request. Meanwhile you can try to set the option `outputMode: 'base64'` to get the pdf output from the plugin as result and put this in a new window by yourself.  See also: http://stackoverflow.com/questions/17739816/how-to-open-generated-pdf-using-jspdf-in-new-window

**Comment by surgiie** [comment]
Ah gotcha. Well thanks for the help! This would be a useful feature^^ @hhurz
