### ISSUE TITLE
Export extra information

### ISSUE THREAD

**Issue by corina10** [hhurz/tableExport.jquery.plugin#118]
Is it possible to add information other than the contents of the table in the export file?
Thanks!

**Comment by hhurz** [comment]
This plugin is not designed to do that!
But if you export in pdf format and are ready to dig into jspdf you could try to use the callback functions of tableExport and manipulate the jspdf doc object. But thats no quite easy to do...

An other way, which i used in an other project that also uses tableExport, is to put the extra content into "special" tables before and/or after the table. Then you export all those tables. During export you can suppress the table borders of the special tables, if you implement the callback function onBeforeTable where you can change the output styling.

**Comment by corina10** [comment]
Thank you!

**Comment by nisrinaqa28** [comment]
Hi @hhurz , can you give me the example source code using callback function onBeforeTable?
