### ISSUE TITLE
export cell dislocation

### ISSUE THREAD

**Issue by peryang** [hhurz/tableExport.jquery.plugin#119]
export cell dislocation when merge cell with xlsx

![qq 20161017101546](https://cloud.githubusercontent.com/assets/12420973/19423449/fa45a30c-9452-11e6-9700-9a7344e76bab.png)

**Comment by peryang** [comment]
modify callback of the function ForEachVisibleCell in line 503.

`var colspan = cell.getAttribute('colspan');`
`var rowspan = cell.getAttribute('rowspan');`

to

`var colspan = parseInt(cell.getAttribute('colspan'));`
`var rowspan = parseInt(cell.getAttribute('rowspan'));`

because the type of the colspan and rowspan is String.

to

`ranges.push({s:{r:rowIndex, c:cols.length},e:{r:rowIndex+rowspan-1, c:cols.length+colspan-1}});`

the result is wrong.

**Comment by peryang** [comment]
I just get the solution to fix the problem. But I'm not familiar with git. So please test the code and comment it.

**Comment by peryang** [comment]
@hhurz please do it.

**Comment by hhurz** [comment]
Thanks for reporting this. I added your solution to the last commit.
