### ISSUE TITLE
export table with wrong header under the select type of filter control 

### ISSUE THREAD

**Issue by peryang** [hhurz/tableExport.jquery.plugin#120]
the header contain the select option value.

![222](https://cloud.githubusercontent.com/assets/12420973/19423667/3731249c-9455-11e6-968c-820961031e03.png)

**Comment by peryang** [comment]
because the function text() get all select option value, we can use the function html().

![111](https://cloud.githubusercontent.com/assets/12420973/19423706/9e9c93a0-9455-11e6-8ab2-8ccbae908796.png)

**Comment by peryang** [comment]
I just get the solution to fix the problem. But I'm not familiar with git. So please test the code and comment it.

**Comment by peryang** [comment]
@hhurz please do it.

**Comment by hhurz** [comment]
Thanks for reporting this. I added your solution to fix it to the last commit.
