### ISSUE TITLE
Newlines (<br />) in cells disappearing after export to excel

### ISSUE THREAD

**Issue by brknkfr** [hhurz/tableExport.jquery.plugin#121]
When exporting a table with cells containing multiple lines to excel, this isn't converted correctly ... In the excel file there aren't any newlines anymore.

When I copy and paste the same table into an excel file, newlines in cells are copied correctly.

Is this maybe because of a missing `<br style="mso-data-placement:same-cell;" />`which keeps the newlines when converting from html to excel?

**Comment by hhurz** [comment]
Thanks for reporting this issue, I just fixed the problem and committed the changes. The fix will be published within the next release.  Alternatively you can download [tableExport.min.js](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/tableExport.min.js) now

**Comment by brknkfr** [comment]
Working as expected.
