### ISSUE TITLE
Export all records of bootstrap-table

### ISSUE THREAD

**Issue by oscarruz** [hhurz/tableExport.jquery.plugin#122]
Hello,
I'm beginning with this kind of bootstrap plugin. I would like to do: When I clicked in a button create a csv file but the problem is that now only create the document with the records it's showed to table doesn't create the records of the others paginations of the table.
Please Could you help me?
Thanks!

**Comment by hhurz** [comment]
Try to set the bootstrap option `exportDataType` with something like that:

``` javascript
$(document).ready(function()
{
  $('#table').bootstrapTable('refreshOptions', { exportDataType: 'all' });
});
```

There is a working example: https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap.html or have a look into the bootstap examples page: https://github.com/wenzhixin/bootstrap-table-examples.
In case this doesn't help, please ask your question here: https://github.com/wenzhixin/bootstrap-table/issues
