### ISSUE TITLE
how to export table except the first and last columns

### ISSUE THREAD

**Issue by xubangbang** [hhurz/tableExport.jquery.plugin#123]
in **tableExport.js** there are two options:
      ignoreColumn: [],
        ignoreRow:[],
i've tried array of index and field names,but they didn't work neither.

**Comment by hhurz** [comment]
ignoreColumn can be either an array of indexes (i.e. ignoreColumn:[0, 2]) or field names (i.e. ignoreColumn:["id", "name"]).
Indexes correspond to the position of the header elements <th> in the DOM starting at 0. 
(If the <th> elements are removed or added to the DOM, the indexes will be shifted so use the functionality wisely!)
Field names should correspond to the values set on the "data-field" attribute of the header elements <th> in the DOM. "Nameless" columns without data-field attribute will be named by their index number (converted to a string)

The ignoreRow array can contain all row indices from thead AND tbody. Writing ignoreRow:[0] would suppress the output of the header row of a simple html table. Where as with ignoreRow:[1] the first data row would be ignored.
Use the ignoreRow option, e.g. ignoreRow: [0,1] to exclude the first two rows from export.

**Comment by xubangbang** [comment]
@hhurz I've tired the two ways correctly.And I found that I have not include the _tableExport.jquery.plugin_ ,I just do `<script src="extensions/export/bootstrap-table-export.js"></script>` this and `<script src="tableExport.jquery.plugin-master/tableExport.js"></script>` this.
But I don't know how to fill in this to use the plugin correctly.
![image](https://cloud.githubusercontent.com/assets/23259390/20035907/f2acaa0c-a431-11e6-99e4-35b10a71a64e.png)
 Please HELP!

**Comment by hhurz** [comment]
Ok got it: This is bootstrap-table related question.
There is a working example: https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap.html or have a look into the bootstap examples page: https://github.com/wenzhixin/bootstrap-table-examples.
In case this doesn't help, please ask your question here: https://github.com/wenzhixin/bootstrap-table/issues
