### ISSUE TITLE
Download links not working under iOS

### ISSUE THREAD

**Issue by JPustkuchen** [hhurz/tableExport.jquery.plugin#125]
Hi and thank you very very much for this great library.

We're running into the issue that the file generation doesn't seem to work on mobile iOS devices. Did someone experience the same issue already or has an idea what may cause this?

Thank you very much in advance.

**Comment by hhurz** [comment]
Hi, this plugin uses [filesaver.js](https://github.com/eligrey/FileSaver.js/) to save its export result. Please have a look into this issue: https://github.com/eligrey/FileSaver.js/issues/12 There seem to be many problems with iOS and Safari when trying to save a file. Thanks,
