### ISSUE TITLE
Not Export Element  "tfoot"

### ISSUE THREAD

**Issue by ghost** [hhurz/tableExport.jquery.plugin#126]
Help, I can not export the information contained in tfoot !
```
<tfoot> 
  <tr>
    <th>text</th>
    <th>text </th>
    <th>30/09/2016</th>
    <th>22/11/2016</th>    
  </tr>
</tfoot>
```

**Comment by hhurz** [comment]
The current version of this plugin doesn't support th elements with a tfoot as (grand) parent element. Only td elements are working. I put this issue on the list of feature requests. Thanks.
