### ISSUE TITLE
 Download the amount of data for the 10000 row *9 column *8 bytes download failed

### ISSUE THREAD

**Issue by wushuang5112** [hhurz/tableExport.jquery.plugin#127]
Hello, I use the Bootstrap Table Export function, this function can download data when the browser will last for a long time will fail card, download, do not know if you have not tried this example, if there is please reply how to deal with?

主题：
下载数据量为10000行*9列*8字节时下载失败
描述：
你好，我使用Bootstrap Table的Export功能，这个功能可能在下载数据大时会浏览器会卡很久，最后会下载失败，不知道你们有没有试过这种例子，如果有请回复如何处理？

**Comment by wushuang5112** [comment]
The Code:
    var table = $("#mytest");

------------------------------------------------------------------------init
        var options = {
            "resizable": true,
            "clickToSelect": true,
            "singleSelect": 0,
            "showExport": true,
            "exportTypes": ["csv",
                "txt",
                "sql",
                "excel"],
            "showColumns": true,
            "search": true,
            "searchOnEnterKey": true,
            "searchAlign": "right",
            "striped": true,
            "pagination": true,
            "pageSize": 20,
            "exportDataType": 'all',
            "columns": getTableColumns()
        };

        table.bootstrapTable(options).bootstrapTable('showLoading');

--------------------------------------------------------------------------update
                loadingData = {
                    "data" :allData
                };
                table.bootstrapTable('refreshOptions', loadingData);
                $('#toolbar').show();

============================================================
I use ajax to request data, the data counts is 10000+, while I use to download in chrome, it death and can't to download

**Comment by hhurz** [comment]
That seems to be a bootstrap-table related question and a similar question was already asked before. Thus
please have a look into this issue: https://github.com/hhurz/tableExport.jquery.plugin/issues/70

You can check out other export related issues with bootstrap-table there: https://github.com/wenzhixin/bootstrap-table/search?q=export+server&type=Issues&utf8=%E2%9C%93.

Have you tried other browsers (Firefox, IE) ?
All I can do for now is to suggest that you update bootstrap table to the latest version.

**Comment by wushuang5112** [comment]
Hello, I find a solution for the upper question!
I change the plugin-"## Export" file, it can't support 10000+ lines downloads for *.txt, *.xls, *.sql.
I am using the latest plugin;

change file: tableExport.js:
you can change the code to this, but *.csv file would be ## messy code for "simple chinese";
line:1315-1318
                        if (header.toLowerCase().indexOf("base64,") >= 0)
                            DownloadLink.href = header + base64encode(data);
                        else
                            DownloadLink.href = header + encodeURIComponent(data);

replace:
                        var URL = window.URL || window.webkitURL;
                        blob = new Blob([convertCode(data)], { type:'text/csv;charset=windows-1252;'});
                        var csvUrl = URL.createObjectURL(blob);
                        DownloadLink.href = csvUrl;

Can you push the lastest solution to me ?

**Comment by hhurz** [comment]
* Line 1315-1318 do not match with latest released version of this plugin!
* Did you include FileSaver.js in your project? FileSaver.js, which is used by this plugin, should save the file as a blob.
* The changes you suggest, tell me that you didn't. The code you changed, is only used, if FileSaver.js can not save a blob, because it fails or it is not present.

**Comment by wushuang5112** [comment]
think you, when I use FileSaver.js to my project, it's work well.
but when the table has chinese(中文), download the *.csv would be garbled(乱码), it can't solve?
I am download the csv file, it code in utf-8, if I change the code type with ANSI(windows), it display well.

**Comment by wushuang5112** [comment]
### the lower is what i download with csv.
------------------------------------------------------------- download *.csv display in excel
鏃ユ湡  椤圭洰ID    涓氫富鐘舵€?鍩庡競  椤圭洰缁撴灉    鍥炶鑺傜偣 杈炬垚闃舵 姝诲崟鍘熷洜    鍒涘缓鏃堕棿
201611xx    12479xxx    鍏朵粬  鍚夊畨甯?鏈噺鎴挎鍗?鏈噺鎴?閲忔埧7澶╁唴  鍏朵粬  2016/11/xx 17:31        
201611xx    10897xxx    寤舵湡瑁呬慨    鑻忓窞甯?宸茬湅鏂规姝诲崟  宸茬湅鏂规 鐪嬩笁瀹?鍏朵粬 2016/11/xx 15:18    
201611xx    14741xxx    寤舵湡瑁呬慨    瑗垮畨甯?鏈湅鏂规姝诲崟   宸查噺鎴?閲忔埧14澶╁唴  鍏朵粬  2016/11/xx 14:07    
201611xx    15098xxx    鍏朵粬  鍏洏姘村競 鏈噺鎴挎鍗?鏈噺鎴?閲忔埧7澶╁唴   鍏徃鐢佃瘽鎶ヤ环   2016/11/xx 14:41    
201611xx    15199xxx    鎵惧埆浜鸿 绂忓窞甯?鏈湅鏂规姝诲崟   宸查噺鎴?姝诲崟鍥炶    浠锋牸  2016/11/xx 14:51    
------------------------------------------------------------



------------------------------------------------------------- *.csv(utf-8) display in notepad++
日期,项目ID,业主状态,城市,项目结果,回访节点,达成阶段,死单原因,创建时间
201611xx,12479xx,其他,吉安市,未量房死单,未量房,量房7天内,其他,"2016-11-xx 17:31:03"
201611xx,10897xxx,延期装修,苏州市,已看方案死单,已看方案,看三家,其他,"2016-11-xx 15:18:24"
201611xx,14741xxx,延期装修,西安市,未看方案死单,已量房,量房14天内,其他,"2016-11-xx 14:07:14"
201611xx,15098xxx,其他,六盘水市,未量房死单,未量房,量房7天内,公司电话报价,"2016-11-xx 14:41:45"
------------------------------------------------------------

**Comment by hhurz** [comment]
I can not reproduce your problem. I checked the export with the data from your "display in notepad++"  example and it works fine. When I export the following table to csv
```html
    <h3>Issue 127: Chinese csv export</h3>
    <table id="issue127" class="">
      <thead>
      <tr>
        <th>日期</th><th>项目ID</th><th>业主状态</th><th>城市</th><th>项目结果</th><th>回访节点</th><th>达成阶段</th><th>死单原因</th><th>创建时间</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>201611xx</td><td>12479xx</td><td>其他</td><td>吉安市</td><td>未量房死单</td><td>未量房</td><td>量房7天内</td><td>其他</td><td>2016-11-xx 17:31:03</td>
      </tr>
      <tr>
        <td>201611xx</td><td>10897xxx</td><td>延期装修</td><td>苏州市</td><td>已看方案死单</td><td>已看方案</td><td>看三家</td><td>其他</td><td>2016-11-xx 15:18:24</td>
      </tr>
      <tr>
        <td>201611xx</td><td>14741xxx</td><td>延期装修</td><td>西安市</td><td>未看方案死单</td><td>已量房</td><td>量房14天内</td><td>其他</td><td>2016-11-xx 14:07:14</td>
      </tr>
      <tr>
        <td>201611xx</td><td>15098xxx</td><td>其他</td><td>六盘水市</td><td>未量房死单</td><td>未量房</td><td>量房7天内</td><td>公司电话报价</td><td>2016-11-xx 14:41:45</td>
      </tr>
      </tbody>
    </table>
```
I get this csv file:
```
 日期,项目ID,业主状态,城市,项目结果,回访节点,达成阶段,死单原因,创建时间
 201611xx,12479xx,其他,吉安市,未量房死单,未量房,量房7天内,其他,"2016-11-xx 17:31:03"
 201611xx,10897xxx,延期装修,苏州市,已看方案死单,已看方案,看三家,其他,"2016-11-xx 15:18:24"
 201611xx,14741xxx,延期装修,西安市,未看方案死单,已量房,量房14天内,其他,"2016-11-xx 14:07:14"
 201611xx,15098xxx,其他,六盘水市,未量房死单,未量房,量房7天内,公司电话报价,"2016-11-xx 14:41:45"
```
which is opened and correctly diplayed in open office calc:
![issue127](https://cloud.githubusercontent.com/assets/4164372/20924928/2a6b5e5e-bbb4-11e6-9a82-7bfb9d94f8ed.png)

So if you get some "garbeled output" I think the problem seems to be on your side...
