### ISSUE TITLE
XLSX Error

### ISSUE THREAD

**Issue by carlhussey** [hhurz/tableExport.jquery.plugin#128]
When trying to export a table of data in the XLSX format, Firefox is giving me a 400 Bad request error. This was with 20 rows.

I tried it with 900 rows and got a URI too long error.

**Firefox can’t find the file at https://mySite/emp/application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=UTF-8QID, Columns/Data Here**

Plugin is included and in the correct order. Thoughts? XLS works fine but really would like XLSX to work as well.

**Comment by hhurz** [comment]
Did you include xlsx.core.min.js AND FileSaver.js ? 
I just verified the XLSX export with Firefox on PC and Mac -> [tableExport.xlsx](https://github.com/hhurz/tableExport.jquery.plugin/files/640297/tableExport.xlsx)

**Comment by carlhussey** [comment]
I don't think I did FileSaver, didn't know that needed to be there for the other to work.

**Comment by carlhussey** [comment]
That seemed to fix the issue. Anyway to prevent this message? 
![screen shot 2016-12-08 at 11 49 42 am](https://cloud.githubusercontent.com/assets/6022490/21023139/84a22d88-bd3c-11e6-8d4b-7208a42165de.png)

File opens fine but people may be put off by "unsafe"

**Comment by hhurz** [comment]
Try xlsx as file extension. The alert shows that xls was used.

**Comment by carlhussey** [comment]
That did it :) Thank You!
