### ISSUE TITLE
After the export, the display of time is not complete

### ISSUE THREAD

**Issue by WangChuangnv** [hhurz/tableExport.jquery.plugin#129]
![image](https://cloud.githubusercontent.com/assets/15187835/20995413/c398fb62-bd31-11e6-9b85-1855704d22e3.png)
when the datetime is like this  20161024160002,when i export the table,the time can't display complete

**Comment by hhurz** [comment]
That's not an issue of this plugin! 20161024160002 isn't a valid date/time format. Excel handles it as a number.
