### ISSUE TITLE
doc.addhtml is not function

### ISSUE THREAD

**Issue by rafaoli** [hhurz/tableExport.jquery.plugin#13]
When click the pdf option following error show in console **doc.addhtml is not function**
i'm using the extension bootstrap...

**Comment by hhurz** [comment]
doc.addHTML is a jspdf function. Did you include jspdf ?

**Comment by rafaoli** [comment]
yes, the following order:
resources/js/tableExport/tableExport.min.js
resources/js/tableExport/libs/FileSaver/FileSaver.js
resources/js/tableExport/libs/html2canvas/html2canvas.js
resources/js/tableExport/libs/jsPDF/jspdf.js
resources/js/bootstrap-table-export.js

**Comment by hhurz** [comment]
could you please try an include order like this:

bootstrap.min.js
bootstrap-table-export.js
FileSaver.min.js
tableExport.min.js
html2canvas.min.js
jspdf.min.js

In an other project im using a similar include order (but without bootstrap-table-export.js) which works for me.

**Comment by rafaoli** [comment]
spend your email I want to send you a print.

**Comment by mdjaman** [comment]
@rafaoli Did you manage to make it work?
Having the same issue
