### ISSUE TITLE
Exporting when "mobileResponsive: true" does not behave properly

### ISSUE THREAD

**Issue by migosantos** [hhurz/tableExport.jquery.plugin#130]
Exporting files from the bootstrap table works perfectly when done in the normal maximized desktop view.

When I resize the browser into the mobile size (with option "mobileResponsive:true"), the table gets converted to the card-view type. Afterwards, when I click on the export to csv or pdf, the exported data contains all these html tags which are not supposed to be in the export.

HTML when in mobile/card-view:
![csv2](https://cloud.githubusercontent.com/assets/5512190/21714906/5ef3e060-d43c-11e6-88c0-6c58daa2ec25.png)

Export when in mobile/card-view:
![csv](https://cloud.githubusercontent.com/assets/5512190/21714913/6e757b70-d43c-11e6-8cda-ac0410b1ab17.png)

**Comment by hhurz** [comment]
This plugin is not a specific bootstrap table extension. It parses any html table and doesn't interpret the table content. So if you want to get rid of the card view tags you could try to implement the onCellHtmlData and/or onCellData functions and parse the cell content by yourself. Thanks.
