### ISSUE TITLE
TSV Export

### ISSUE THREAD

**Issue by pbelmann** [hhurz/tableExport.jquery.plugin#131]
I need a way to export .tsv and .csv files.
What is the best way to extend this library?
I would implement something like this:

~~~Javascript
if (defaults.type == 'csv' || defaults.type == 'txt' || defaults.type == 'tsv') {

  var csvData = "";
  var rowlength = 0;
  defaults.csvSeparator =  defaults.type == 'tsv' ? '\t' : defaults.csvSeparator
~~~

I could set up a PR.

**Comment by hhurz** [comment]
Quick and easy ;)  You will find tsv support in release v1.6.7. Thanks.
