### ISSUE TITLE
Why the browser freeze when I try to export large tables

### ISSUE THREAD

**Issue by leo-def** [hhurz/tableExport.jquery.plugin#132]
This tool work perfectly when I try to export small tables but if I try to export a table with more than 5.000 rows. Its take a lot of time and I recieve a alert message from Windows saying Google Chrome is taking long time to response, cancel or waiting.

Others libraries don't show this problems but is not too complete like this. There any alternative for solve this and keep using this library

**Comment by hhurz** [comment]
I suppose you are exporting to pdf? In this case, there can't be done much to speed up things, because this plugin relies on two other libraries (jspdf and jspdf autotable) which slows down the export process. Perhaps you could try pdfmake as an alternative pdf producer. For how you can include and activate pdfmake support within this plugin, see my comment in this [issue](https://github.com/hhurz/tableExport.jquery.plugin/issues/112). Be aware that pdfmake is very limited regarding output styling.

**Comment by leo-def** [comment]
@hhurz  I was exporting a XLSX and CSV file both of them I have the same problem.

**Comment by hhurz** [comment]
I can't confirm this. I just successfully exported with Chrome and Firefox a table containing 5555 rows and 26 cololumns to a xlsx and a csv file. Both browsers needed for both formats about 10 to 11 seconds. Is there something special with your table content?

**Comment by leo-def** [comment]
@hhurz I'm using It with angular-material.js and I call this inside a directive. There are two tables in screen, a normal table just for display informations and another one hidden Just for export.

**Comment by schutze** [comment]
I have seen this too.  The browser does not freeze it just takes a really long time to process lots of table cells.  I tested a 3 column table in IE 11.0.9600, Firefox 55.0.3, and Chrome 61 (results in seconds):

75 rows to CSV : IE 11 = 5, Firefox = 9, Chrome = 2
75 rows to XLS : IE 11 = 5, Firefox = 9, Chrome = 2
275 rows to CSV : IE 11 = 21, Firefox = 64, Chrome = 7
275 rows to XLS : IE 11 = 22, Firefox = 63, Chrome = 7
275 rows to PDF AutoTable: IE 11 = 57, Firefox = 64, Chrome = 7

Except for IE and AutoTable, the type of output does not seem to matter.  Is there maybe some inefficient code that prepares data for multiple output types?

**Comment by prog20901** [comment]
To solve this problem, is it possible to add pagination? else one more option to include all these export options bundles to datatable including their existing ones. example see the front page of it https://datatables.net/extensions/buttons/examples/initialisation/export it would be awesome if we do that.....

**Comment by prog20901** [comment]
The datatable works great even if the size is 10,000 where pagination is set

**Comment by prog20901** [comment]
https://datatables.net/extensions/scroller/examples/initialisation/large_js_source.html
