### ISSUE TITLE
Numbers are sometimes formatted as text in text and CSV output

### ISSUE THREAD

**Issue by kleinph** [hhurz/tableExport.jquery.plugin#137]
If a number has a thousand separator (is equal or bigger as 1000) the number is written as string into text and CSV output (including the thousands seperator). I would expect it to be written as a number.

**Comment by hhurz** [comment]
This only happens, if output thousands separator or decimal mark equals csv separator.  In this case numbers need to be quoted. Example:

Html table
```html
<table>
  <thead>
    <tr>
      <th>C1</th><th>C2</th><th>C3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1.101</td><td>2</td><td>30,000</td>
    </tr>
    <tr>
      <td rowspan="3">1</td><td>.2</td><td>30000</td>
    </tr>
    <tr>
      <td rowspan="3">2.2222222222</td><td>3.333</td>
    </tr>
    <tr>
      <td>30,000.30</td>
    </tr>
    <tr>
      <td>1</td><td>3</td>
    </tr>
  </tbody>
</table>
```
CSV output with different seperator options
```
Export options:
===============
csvSeparator: ','
decimalMark: '.'
thousandsSeparator: ','

CSV output:
===========
C1,C2,C3
1.101,2,"30,000"
1,.2,30000
,2.2222222222,3.333
,,"30,000.30"
1,,3
```

```
Export options:
===============
csvSeparator: ','
decimalMark: ','
thousandsSeparator: '.'

CSV output:
===========
C1,C2,C3
"1,101",2,30.000
1,",2",30.000
,"2,2222222222","3,333"
,,"30.000,30"
1,,3
```

**Comment by hhurz** [comment]
It should be noted, that if you want "numbers as numbers" in your csv output, you can achieve that by setting the separator options to this:

```javascript
csvSeparator: ';',
numbers: {html:   {decimalMark: '.',
                   thousandsSeparator: ','},
          output: {decimalMark: ',',
                   thousandsSeparator: ''}
```

**Comment by kleinph** [comment]
Thanks, that worked.
BTW: is text output really the same as CSV just with a .txt extension?

**Comment by hhurz** [comment]
Text output is identical to csv output. The only diffrence is an optional BOM for csv files.
