### ISSUE TITLE
Do not use thousandsSeparator in Excel output

### ISSUE THREAD

**Issue by kleinph** [hhurz/tableExport.jquery.plugin#138]
To get actual numbers in Excel output it seems thousandsSeparator has to be set to `''`. Wouldn't it be better if numbers are written in an excel compatible number format by default?

**Comment by hhurz** [comment]
Thanks for your suggestion, but I don't know if it is a good idea to change an established default behavor. Plus there are users, who prefer the same cell formating in excel as shown in the exported html table. I think this plugin has more a WYSIWYG approach and doesn't want to export the raw data only.

**Comment by kleinph** [comment]
Good point! But there should maybe a more obvious option, for that than setting the separator to the empty string, or at least the behavior should be documented somewhere. Because if the data is formatted like that in Excel it is treated as string and cannot be used in calculations, which is not what one would expect.

**Comment by hhurz** [comment]
You convinced me ;) Since release v1.6.9 you can set option ``` numbers: output: ``` to false to disable formatting of numbers. Thanks.

**Comment by kleinph** [comment]
Thanks for including this :)
