### ISSUE TITLE
Multiple header rows in PDF output

### ISSUE THREAD

**Issue by kleinph** [hhurz/tableExport.jquery.plugin#139]
If there are multiple headers (multiple `<tr>` in `<thead>`) only the last one is included in the PDF output. If  `data-tableexport-display="none"` is set on the last header row, no header is included in the PDF.

**Comment by hhurz** [comment]
Actually it's not possible to print more than one header row. Thats a limitation of the jspdf-autotable plugin, which is used by tableExport.jquery.plugin. I'm not sure if an update to the recent version of jspdf-autotable would fix this issue. But an update would at least require a major rework of the plugins pdf output, what I'm not able to do at the moment.
Anyway, I fixed the ```data-tableexport-display="none"``` part of this issue, which is available in the v1.7.0 release.

**Comment by hollismaynell** [comment]
What is the reason that my table also export the corresponding column options when it is export ? @hhurz
