### ISSUE TITLE
Is it possible to export all data with pagination?

### ISSUE THREAD

**Issue by stephenliu1944** [hhurz/tableExport.jquery.plugin#14]
When I use pagination, I just could export data of pagesize. How could I export all data?

**Comment by gtantum** [comment]
If you are using bootstrap-table you can toggle the pagination off and on.

```
function doExport(params){
        var $table = $('#table');
        var options = {tableName: 'Name',
                       worksheetName: 'Name',
                       fileName: FileName};

        $table.bootstrapTable('togglePagination');
        $.extend(true, options, params);
        $('#table').tableExport(options);
        $table.bootstrapTable('togglePagination');
    };
```

**Comment by TreyTaylor** [comment]
@gtantum 
Looking to do same thing, bit of a newby to this. I see the code but where do I place the code? and does this only mean it will export in a excel file?

-Thanks

**Comment by joomlaA1** [comment]
could be placed in a button... like this:

function doExport(params){
        var $table = $('#table');
        var options = {tableName: 'Name',
                       worksheetName: 'Name',
                       fileName: FileName};
        $table.bootstrapTable('togglePagination');
        $.extend(true, options, params);
        $('#table').tableExport(options);
        $table.bootstrapTable('togglePagination');
    };

('#buttonId').click(function{
doExport();
});
