### ISSUE TITLE
I want to remove col in the table, how to do it?

### ISSUE THREAD

**Issue by cgfeel** [hhurz/tableExport.jquery.plugin#148]
I try to setting that by `bootstrap-table` plugin
```
	exportOptions: {
		fileName: '充值记录表',
		onCellHtmlData: function(cell, row, col, data) {
			var result = "";
			if (col == 0 || col == 1) {
				return result;
			}

			if (data != "") {
				var html = jQuery.parseHTML(data);
				jQuery.each( html, function() {
					if ( typeof jQuery(this).html() === 'undefined' )
						result += jQuery(this).text();
					else if ( typeof jQuery(this).attr('class') === 'undefined' || jQuery(this).hasClass('th-inner') === true )
						result += jQuery(this).html();
				});
			}
			return result;
		}
	}
```

After export `cvs` col 0 and col 1 in the table was empty, but I want to remove col 0 and col 1. how can i set up?

**Comment by hhurz** [comment]
For hiding columns you don't need to implement onCellHtmlData. Use the ```ignoreColumn``` option to achieve this. In your example set it to ```ignoreColumn: [0,1]``` to exlude col 0 and col 1. See also readme.md for some remarks about the ignoreColumn option.

**Comment by cgfeel** [comment]
It's very nice! Thanks @hhurz
