### ISSUE TITLE
Error saving XLSX file types without fileSaver.js

### ISSUE THREAD

**Issue by GJKuz** [hhurz/tableExport.jquery.plugin#149]
Great plugin!!! Just came across a minor bug in tableExport.js at line 596 when FileSaver.js is not used. In the call to downloadFile, the third parameter is set to data instead of blob.

```
try {
          blob = new Blob([jx_s2ab(wbout)], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=UTF-8'});
          saveAs(blob, defaults.fileName + '.' + defaults.type);
        }
        catch (e) {
          downloadFile(defaults.fileName + '.' + defaults.type,
                       'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=UTF-8',
                       blob);
        }
```

**Comment by hhurz** [comment]
Thanks for reporting this issue. I fixed this and a bit more ;) so you should be able to save binary data even when filesaver.js is not included. This fix will be available in next release.

**Comment by GJKuz** [comment]
Thanks!!! Looking forward to the new version.

**Comment by hhurz** [comment]
@pyash FYI: v1.7.2 have been released
