### ISSUE TITLE
table export not work on IE8

### ISSUE THREAD

**Issue by kyo313** [hhurz/tableExport.jquery.plugin#15]
table export not work on IE8 when I visit index.html, it said the page have some mistakes

**Comment by zardaloop** [comment]
I am also having problem with the IE9, IE 10 and IE 11 or generally any IE. The export does not work on IE at all. the example could be here : http://issues.wenzhixin.net.cn/bootstrap-table/#extensions/export.html
if you go to this URL in IE and try to export into any format, you will get an error. However if you go to that URL using Chrome or Firefox it works perfectly fine. 

Any thought on that?

**Comment by hhurz** [comment]
When debugging your example code in IE i cannot find the TableExport.js code. It seems not be included in IE. I see that there is a include statement for "//rawgit.com/hhurz/tableExport.jquery.plugin/master/jquery.base64.js which doesn't exist any more. This missing file invokes an internal 404 error in firefox and chrome, which is caught by that browsers but seems not be handled by IE. Thus please remove that statement and try it again.

**Comment by RoelRoel** [comment]
It's crazy to still ask for IE 8 support nowadays in my opinion. Developers should not waste any more time on IE 8 support. The world has moved forward.

**Comment by TreyTaylor** [comment]
@RoelRoel I agree with you to an extent, a lotta companies still use IE8 for some weird reason, which causes tones of issues dev-end compatibility wise, I think companies should upgrade their browsers but til then support needs to be there or else that website will lose traffic

**Comment by hhurz** [comment]
FYI: **This plugin works with IE11**
Most reason for not working with IE is a missing include of the [FileSaver plugin](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/libs/FileSaver/FileSaver.min.js)

**Comment by RedPointMS** [comment]
@hhurz could you tell more on the FileSaver - how did you get it working? I included this plugin but still have the same problem

**Comment by hhurz** [comment]
More information about FileSaver you can find on its home page: https://github.com/eligrey/FileSaver.js

**Comment by RedPointMS** [comment]
Thanks @hhurz, got it working!

**Comment by PabloRodriguezMontalvo** [comment]
Works on IE11 but not in 8 T_T

**Comment by hhurz** [comment]
@PabloRodriguezMontalvo: I confirm this

**Comment by wilky27** [comment]
unfortunately our company is one stuck with IE8. Is there a fix this?

Thanks.

**Comment by hhurz** [comment]
Sorry, there is no IE8 support. Especially not for PDF format, cause the underlying jsPDF fails within IE8. For text based formats like csv and txt you could try the `outputMode` option set to `string` or `base64` and save the result of the `tableexport()` function on your own using some other plugins like [ChenWenBrian and koffsyrup's `saveTextAs()`](https://github.com/koffsyrup/FileSaver.js#examples) or [Downloadify](https://github.com/dcneiner/Downloadify)

**Comment by wilky27** [comment]
Yes ChenWenBrian's plugin worked for me. Many thanks!
