### ISSUE TITLE
export excel: can't export when table has img

### ISSUE THREAD

**Issue by WangChuangnv** [hhurz/tableExport.jquery.plugin#155]
when table has img , the export excel doesn't have img;
`<table id=”save” style=””>
<thead>
<tr><td>1</td><td>2</td></tr>
</thead>
<tr>
<td colspan=”2”>
<img width=”200” height=”400” src=”data:img/svg+xml;base64,PgICA.......+”>
</td>
</tr>
</table>`

 src=”data:img/svg+xml;base64,PgICA.......+”

the excel doesn't show img,why?and how img can show

**Comment by hhurz** [comment]
Images are only supported by pdf format. You can't export them to excel.
