### ISSUE TITLE
How to convert number to text when exporting to excel

### ISSUE THREAD

**Issue by wygdove** [hhurz/tableExport.jquery.plugin#156]
There is a column named "id" in my html table.Like 201703232500131.But after I exported the table to excel,this column turned to number and added a zero in the end.In Excel,it shows 2.01703E+15 ,and the value is 2017032325001310.I just want excel to show 201703232500131 in this column and have no other symbol.How can I do this?

**Comment by wygdove** [comment]
already fixed.
see http://www.studenty.cn/?p=445

**Comment by hhurz** [comment]
Thats *NOT* the solution that I'd recommend. If you add the suggested line to the code, excel would treat the content of every cell as text.
If you can change the table you want to export, you better would add a data attribute **```data-tableexport-msonumberformat="\@"```** to the cell named "id".
Or, if you can't change the table structure, you could use the callback function **```onMsoNumberFormat```** and return **```\@```** if the function is called for the "id" cell.

**Comment by wygdove** [comment]
Actually, I tried onMsoNumberFormat function.I even used console.log(value); in the function to make sure the value which is just the id column.It's just useless.

**Comment by hhurz** [comment]
There was an issue in my comment above, that suppressed the output of the leading backslash before the at-sign! 
The msonumberformat for text is not a single ```@``` as stated in the original comment, but it is a combination of a backslash and at-sign: **```\@```** 
I corrected the comment. Please try it again. Thanks.

**Comment by wygdove** [comment]
```
onMsoNumberFormat:function(cell,row,col) {
	if(col==3) {
		// console.log(cell);
		return "\\@";
	}
},
```

ok...... 
this fixed my problem.
thank you so much!
