### ISSUE TITLE
data-tableexport-value not working with jquery.data()

### ISSUE THREAD

**Issue by hakan-andersson** [hhurz/tableExport.jquery.plugin#157]
When adding data-tableexport-value to a td with jQuery.data() the check $cell[0].hasAttribute("data-tableexport-value") will always return false.

**Comment by hhurz** [comment]
Thats not a plugin related question. A Google-Search gives you a couple of results, e.g.
http://stackoverflow.com/questions/17351282/jquery-cant-get-data-attribute-value

**Comment by hakan-andersson** [comment]
Thanks, wonder how I could have missed that :)
