### ISSUE TITLE
only exporting visible rows, not all the rows

### ISSUE THREAD

**Issue by durgasekar** [hhurz/tableExport.jquery.plugin#158]

**Comment by bakiyuksel** [comment]
disable pagination when exporting

**Comment by durgasekar** [comment]
Thank you :)

**Comment by durgasekar** [comment]
Is der any other way @SaluteMB

**Comment by hhurz** [comment]
Duplicate of issue #153, #122, #85, #54, and #26

**Comment by bakiyuksel** [comment]
I linked it to a new page that closes after download is done. On that page it loads all rows of the table. @durgasekar
