### ISSUE TITLE
Multiple Tables Render Across Entire PDF

### ISSUE THREAD

**Issue by dreamcasting** [hhurz/tableExport.jquery.plugin#16]
Hello,

Thanks for maintaining this plugin! I'm figuring this out, so I hope my question isn't too stupid. I've got the tableExport plugin implemented but when I go to export to PDF everything renders as one big table across the PDF, rather than each instance of the tables on the html source.

 `<a href="#" onclick="$('table').tableExport({type:'pdf',escape:'false'});"> pdf</a>`

I get a 15 column wide single table in PDF, rather than 3 tables of 5 columns each.

Any assistance is appreciated!

**Comment by hhurz** [comment]
YAW. 
With $('table') you are using a jQuery "element selector" which selects all(!) tables of your page and produces a large single pdf table out of them. You can use an id selector to export a single table:

```
<a href="#" onclick="$('#table1').tableExport({type:'pdf',escape:'false'});pdf</a>
```

TableExport doesn't support the export of multiple tables.

**Comment by dreamcasting** [comment]
Ah, there's the rub. I knew I was scooping all the tables based on the selector, but thought the plugin could process that out, since it does have jsPDF-AutoTable, which support multi table. Do you know if you plan to add multiple table support?

**Comment by hhurz** [comment]
I will take this into consideration, but I cannot say when that will be. Merging a pull request would be much more faster ofcourse ;-)

**Comment by hhurz** [comment]
Added multiple tables support for pdf format (AutoTable).
