### ISSUE TITLE
PDFMake don't support rowspan and colspan?

### ISSUE THREAD

**Issue by JuniorYoung** [hhurz/tableExport.jquery.plugin#164]
I use pdfmake instead of jspdf(because it supports chinese)
but I found that cross rows and cross columns are not supported in pdfmake,
how to fix it ?

**Comment by hhurz** [comment]
pdfmake integration is still in an experimental stage. I just committed a version that offers some basic support for colspan and rowspan. Perhaps this helps.

**Comment by JuniorYoung** [comment]
Thanks for your help,but I found the other two bug:

1. When the table head has table cells that span multiple rows and column, it reports a error:

> `Malformed table row, a cell is undefined.`            

(The error only occurs on the thead )

   I have fixed it:
_tableExport.js line: 814:_        

```javascript
if (typeof cell !== 'undefined' && cell !== null) {
    var colspan = parseInt(cell.getAttribute('colspan'));
    var rowspan = parseInt(cell.getAttribute('rowspan'));
    var cellValue = parseString(cell, row, col) || " "; // ***************fixed this
    if (colspan > 1 || rowspan > 1) {
        colspan = colspan || 1;
        rowspan = rowspan || 1;
        h.push({colSpan: colspan, rowSpan: rowspan, text: cellValue});
    } else{
        h.push(cellValue);
    }
} else{
    h.push(" ");    //***************fixed this
}
```


2. Here is the situation:
<table>
<tr>
        <td rowspan="3">R1-C1</td>
        <td rowspan="3">R1-C2</td>
        <td colspan="5">R1-C3</td>
      </tr>
      <tr>
        <td rowspan="2">R2-C1</td>
        <td rowspan="2">R2-C2</td>
        <td colspan="3">R2-C3</td>
      </tr>
      <tr>
        <td>R3-C1</td>
        <td>R3-C2</td>
        <td>R3-C3</td>
      </tr>
</table>
I have some questions about this code of tableExport.js on the line 1339th.

I have fixed it too.

```javascript
if (typeof rowspans[rowIndex] != 'undefined' && rowspans[rowIndex].length > 0) {
    for (c = 0; c <= colIndex; c++) {
        if (typeof rowspans[rowIndex][c] != 'undefined') {
            cellcallback(null, rowIndex, c);
            delete rowspans[rowIndex][c];
            colIndex++;
        }
    }
}
```
replace with

```javascript
if (typeof rowspans[rowIndex] != 'undefined' && rowspans[rowIndex].length > 0) {
       var colIndexBak = colIndex;
       for (c = 0; c <= colIndexBak; c++) {
           if (typeof rowspans[rowIndex][c] != 'undefined') {
                cellcallback(null, rowIndex, c);
                delete rowspans[rowIndex][c];
                colIndexBak++;
            }
       }
       colIndex+=rowspans[rowIndex].length;
}
```

**Comment by hhurz** [comment]
@JuniorYoung:  Thanks a lot for reporting this and for your suggestions to solve it. I committed a new version that contains the fixes.
