### ISSUE TITLE
Which JQuery version this supports?

### ISSUE THREAD

**Issue by Giovanni-Enrico** [hhurz/tableExport.jquery.plugin#165]
Just want to know which version I can use, because I switched to JQuery 3.2.1 and it stopped working.
Thanks :)

**Comment by hhurz** [comment]
Just tested the plugin with all versions from https://code.jquery.com/
```
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
```
Every version worked fine for me.

**Comment by Giovanni-Enrico** [comment]
@hhurz  Thanks for the replying.

Im using the Export with its bootstrap-table version and a bootstrap-datetimepicker, I thought that I was importing in the wrong order, but I tried to switched the JQuery to "jquery-latest" and now it works, dont know why though, since the latest is the 3.2.1. Any ideas?

**Comment by hhurz** [comment]
FYI: "jquery-latest" is "jQuery v1.11.1" 
Suggestions: Have a look into your browsers console window. Perhaps you'll find some log entries that help you to locate the problem. Also check the [jQuery and Bootstrap version requirements for Bootstrap Table](https://stackoverflow.com/questions/38603505/what-are-jquery-and-bootstrap-version-requirements-for-bootstrap-table)

**Comment by Giovanni-Enrico** [comment]
Ohhh now I get it.
Again, thanks a lot for your help
