### ISSUE TITLE
Error "The file format and extesions 'file.xls' don't match" 

### ISSUE THREAD

**Issue by fiaraujo** [hhurz/tableExport.jquery.plugin#166]
Hi there.

Everytime I try to export data for a .xls format I receive the error "The file format and extesions 'file.xls' don't match". If I press "Yes" I'm able to open the file in Excel 2013 and 2016, but I'm receiving some users complaints that the file doens't opens for them. There's any way to solve that message?

**Comment by fiaraujo** [comment]
Just figured that exporting .xlsx solved the problem. Thanks

**Comment by hhurz** [comment]
See also issue #49
