### ISSUE TITLE
pdfmake is not working, not even the test

### ISSUE THREAD

**Issue by lbenedette** [hhurz/tableExport.jquery.plugin#168]
I've trying to use pdfmake instead jspdf, but an error occurs:
TypeError: $rows.each is not a function

I downloaded the tests and the same error occurs. I solve this transforming the $rows in a jquery object:
$($rows).each 
I send a pull request :+1: 

I use this plugin like an extension of bootstrap-table, even solving this problem I still receiving an error:
TypeError: Argument 1 is not valid for any of the 2-argument overloads of URL.createObjectURL

Any idea about what this error occur?

**Comment by hhurz** [comment]
@lbenedette: Thanks again for your fix. 
Regarding your problem with URL.createObjectURL: I just checked my bootstrap test files and they worked fine for me. Even when I changed them to exported to pdf with pdfmake there wasn't an error. 
Did you check the include order? 
There are many results when searching for the error text you mentioned above...
Actually I don't know what going wrong there,

**Comment by lbenedette** [comment]
@hhurz ohhh man, I've forgotten the FileSaver lib, importing pdf with jspdf don't need this lib, but the pdfmaker needs, now everything is working, thanks!
