### ISSUE TITLE
Is there a event handler after Export?

### ISSUE THREAD

**Issue by Giovanni-Enrico** [hhurz/tableExport.jquery.plugin#170]
Hi, I'm using bootstrap-table that uses your pluging and I'm having problems after the export is done. More details in [https://github.com/wenzhixin/bootstrap-table/issues/3206](url).
One of the solution that I thought would be to reload the page after the export is done, since this prevents the bug to happen, but I couldnt find this event in the documentation. If is there any, could you tell me?

Any response would be appreciated.

**Comment by hhurz** [comment]
Actually there is no "export is done" event, sorry. Also I wouldn't know how to provide such an event, because the plugin wouldn't know when the user finished downloading the export file. I suggest you reload the page after the "Filtrar" button was clicked.

**Comment by Giovanni-Enrico** [comment]
The "Filtrar" button is there just to update the "data-url" from the table, depending on the filters that are above him, if I reload the page after it's clicked, it will never show the data.
I'll try to create a custom buttom that exports the table using just your plugin and not the property "show-export" from the bootstrap-table, maybe that could prevent the bug to happen.

**Comment by Giovanni-Enrico** [comment]
Made it work, I created a button like I said with the following code
 `				$('#export').click(function() {
					$('#table').bootstrapTable('togglePagination');
			        $('#tableID').tableExport({type:'excel'});
					$('#table').bootstrapTable('togglePagination');
			      });`

Basically instead of using the export all from bootstrap-table, the button just disables pagination, exports the data, then enables pagination again.
