### ISSUE TITLE
Table Export is not a funciton Error

### ISSUE THREAD

**Issue by Dannym96** [hhurz/tableExport.jquery.plugin#171]
$("#pdf").click(function () {
               $('#table1').tableExport({type:'csv'});
            });
I have a vue cli project and when i try to run this function for table export i get this error.
Uncaught TypeError: $(...).TableExport is not a function
This is the imported dependencies in my main.js

import Vue from 'vue'
import App from './App.vue'
import VueRouter from 'vue-router'
import jQuery from 'jquery';
global.$ = jQuery;
import TableExport from  'tableexport.jquery.plugin';
I also import jquery in the tableExport.min.js which fixed a jquery not defined issue. 
Any solutions for this would be appreciated.

**Comment by hhurz** [comment]
I'm not familiar with vue, but in javascript this TypeError is usually raised if the tableExport.min.js is not properly included.
