### ISSUE TITLE
Version 1.9.2 - Circular dependency

### ISSUE THREAD

**Issue by haoksam** [hhurz/tableExport.jquery.plugin#173]
Latest version causes issues because of a circular dependency.
tableExport is requiring itself in dependencies, causing an infinite loop of "requiring packages".

Removing **_"tableExport.jquery.plugin": "^1.9.2"_** from **"dependencies"** section of bower.json solves the issue.

PS. used gulp for build purposes

**Comment by hhurz** [comment]
Thanks for reporting this issue. I fixed it in release v1.9.3
