### ISSUE TITLE
Page is not loading

### ISSUE THREAD

**Issue by langweiler2003** [hhurz/tableExport.jquery.plugin#175]
Hello,

I have an issue with the table export here is my code:

```
<script type="text/javascript" src="libs/FileSaver/FileSaver.min.js"></script>
<script type="text/javascript" src="libs/jsPDF/jspdf.min.js"></script>
<script type="text/javascript" src="libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
<script type="text/javascript" src="tableExport.min.js"></script>
<script>
   function chLocation(newLocation) { document.location = newLocation; }
</script>

<table width="720" id="Stundenzettel" cellspacing="4" cellpadding="7" border="0">     
          <tr>
            <td valign="top" colspan="2">

            {$report_content}

            </td>
          </tr>
</table> <table width="720" cellspacing="4" cellpadding="7" border="0">   
          <tr>
            <td align="center">

            <table><tr>
            <td>
                <input type="button" onclick="chLocation('report_send.php');" value="{$i18n.forward.sendbyemail}">
            </td>
            
            {if $user->isManager() || $user->isCoManager()}
            <td>
                <input type="button" onclick="chLocation('invoice.php');" value="{$i18n.forward.geninvoice}">
            </td>
            {/if}
            <td>
                <input type="button" onclick="$('#Stundenzettel').tableExport({type:'pdf'});" value="{$i18n.forward.pdf}">
                
            </td>
            </tr></table>
```

With this i get a blank page. If i change the onclick to this `onclick="$('#Stundenzettel').tableExport();` the page is loading but nothing is happening at all if i hit the button

**Comment by hhurz** [comment]
Hi, in your source code snippet above I'm missing the include of jquery. Did you have a look into the console output of your browser? There might be a corresponding error entry.

You didn't provide any information about the content of "{$report_content}". In case this is an other table you should use the id of this table to export it, because actually nested tables are not supported by this plugin.

**Comment by langweiler2003** [comment]
Hello,

thank you for your response. Indeed i haven't incuded it. And yes it is a nested table, so it looks like i have to find another solution :(
 
Is it possible to push more than one table into the PDF ?

Thank you and Regards

**Comment by hhurz** [comment]
Let me just clarify:
```javascript
<table id="Stundenzettel">
  <table id="zettel_1">
  </table>
</table>
```
As said before ```$('#Stundenzettel').tableExport({type:'pdf'});``` will not work, 
but ```$('#zettel_1').tableExport({type:'pdf'});``` does.

For multiple tables 
```javascript
<table id="Stundenzettel">
  <table id="zettel_1">
  </table>
  <table id="zettel_2">
  </table>
</table>
```
you would write ```$('#zettel_1,#zettel_2').tableExport({type:'pdf'});```

**Comment by langweiler2003** [comment]
Thank you very much,

it is working now :)
Regards
