### ISSUE TITLE
Images in Table are leading to malformed empty PDFs

### ISSUE THREAD

**Issue by langweiler2003** [hhurz/tableExport.jquery.plugin#177]
Hello,

i have an image in my table which should get exportet too.
I have tried it in base64 like this;

`<tr><td colspan='9' style='text-align:right;'><img src='data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAZABkAAD/......`

and alternative 
`<td colspan='9' style='text-align:right;'><img src='images/vectory.jpg'></td>`

In different Format ( gif, png ) i have tried it too.
In both cases, acrobat tells me that it is malformed and brings me only blank pages

Do i miss something in my includes ?

`<script type="text/javascript" src="jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="libs/FileSaver/FileSaver.min.js"></script>
<script type="text/javascript" src="libs/jsPDF/jspdf.min.js"></script>
<script type="text/javascript" src="libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
<script type="text/javascript" src="tableExport.js"></script>
<script type="text/javascript" src="libs/html2canvas/html2canvas.min.js"></script>`

Regards
PS: my mistake i have messed up the javascript Image is the pdf now but much too small
How i can get it to the correct size as my css for it seems to be ignored ?

**Comment by hhurz** [comment]
Actually there are no explicit options to size images within a table. The resulting size of the image in the pdf depends on the original size of the image and the row height of the pdf table. In case the pdf row height is larger than the image height, the image will be centered vertically. If the pdf row height is smaller, the image will be strectched proprtionally to fit into the cell.

FYI: You can set the row height of the pdf table with rowHeight option.
```javascript
{type: 'pdf',
 jspdf: {autotable: {styles: {rowHeight: 36}
                    }
        }
}
```

**Comment by langweiler2003** [comment]
Hello,

thank you for your response.
i have shrinked the image but now it looks like something in the pdf is overlaying it

![image](https://user-images.githubusercontent.com/22234818/28365868-8b8142d0-6c8a-11e7-9cad-f09a480c124c.png)

Any suggestion ?

**Comment by hhurz** [comment]
In your first post you wrote the image is too small, now it seems to be too large. Did you really shrink it? Anyway, without further information (an example would be handy) its hard to understand what is going wrong here.

**Comment by langweiler2003** [comment]
Hello,

yes i shrinked it. I thought at first that the image (220px x 199px ) was reduced in the output. But later i realised that i only saw the first few pixel of it so i shrinked it to fit the column height.

I think i have now nailed down my issue. As soon as i align the image to the right of the cell the first few pixel are on the right side of the colum and the rest which would reach into the next column is overlayed by it.
I now aligned it to the left and the complete image is shown
So issue can get closed

Thank you for your help
