### ISSUE TITLE
Casting String to Number - export crash

### ISSUE THREAD

**Issue by ddelporte** [hhurz/tableExport.jquery.plugin#181]
I use data-tableexport-value to set different value to export than I display.
If I have data-tableexport-value="100" for example, export CSV break on tableExport.js line 1728.
I think because htmlData is a number and not a String. I juste replace 
_var text = htmlData.replace(/\n/g,'\u2028').replace(/<br\s*[\/]?>/gi, '\u2060');_
by
_var text = String(String(htmlData).replace(/\n/g,'\u2028')).replace(/<br\s*[\/]?>/gi, '\u2060');_

I don't know if it's the good way.

**Comment by hhurz** [comment]
Thanks for reporting this issue. I fixed it by converting the data-tableexport-value to a string, just when the value is assigned to htmlData.

**Comment by ddelporte** [comment]
it works, thx
