### ISSUE TITLE
how to set the datetime format in the export excel

### ISSUE THREAD

**Issue by yongdchan** [hhurz/tableExport.jquery.plugin#183]
Hi, i found that the default format of datetime is "YYYY/MM/DD HH:mm" in the exported table. However, I would like to set the datetime format "YYYY-MM-DD HH:mm:SS". So i wonder is there any way that i can set the export format for datetime?

**Comment by hhurz** [comment]
There is no direct option to set the datetime format. But you can use one of two callback functions that are called during the export process. 1st callback function is ```onCellHtmlData``` which is called right after the content of a table cell has been read, but before it has been further processed. 2nd callback is ```onCellData```. This function is called after the cell content has prepared just before it will be written to the export file. Both functions let you change the data/text to be exported. To give you an idea how to implemet a callback function see this issue: #45

**Comment by yongdchan** [comment]
Thanks a lot for your response and suggestion!
