### ISSUE TITLE
Export a limited number of rows on selection

### ISSUE THREAD

**Issue by SRaiz** [hhurz/tableExport.jquery.plugin#184]
Hi hhurz,

Are we having facility for exporting the limited number of rows from the table. If not can we have this facility too?

**Comment by SRaiz** [comment]
Hi hhurz,

Any good news in adding this feature?

**Comment by hhurz** [comment]
~~Hi, I added this issue on the list of feature requests. But I'm not able to tell you when it will be realized.~~

**Comment by SRaiz** [comment]
I have solved this problem by adding some java script code on the table formed by plugin. If anyone needs explanation please ping me. Hereby closing the ticket. Thanks hhurz for your plugin.

**Comment by hhurz** [comment]
@SRaiz Could you please explain or show how you solved the problem. Perhaps this could help to implement the feature. Thanks.

**Comment by prog20901** [comment]
@SRaiz could you please kindly explain the java script so that it would be implemented by hhurz...please help us.

**Comment by SRaiz** [comment]
Hi hhurz/jkathir,

Sorry for replying late on the issue. Here are the process by which you can access and export limited data from the table :-

1.  First of all, you need to provide a checkbox against each row in order to select the row and send the 
     data(In this case the row) you want to export. You can either provide a checkbox or any alternative 
     way to select your row which you want to export.

2. So lets suppose I have a table with name mytable1 and I have selected some rows which I want to 
    export. I have a function named exportToPdf which triggers when I click on the export button. So, now 
    you will be able to export them by putting the data corresponding to your clicked rows into an EMPTY 
    table on your page and putting that data you have selected on that table dynamically. After the rows 
    are exported ensure that whenever you are exporting again the table should be empty again.
    eg :- 
                **totalChecked = $j('input[name="inputChkBox"]:checked').length;
                if(selectedOption == 'Export As PDF' && totalChecked > 0){
                    var values = [];
                    $j("#mytable1 input[name=inputChkBox]:checked").each(function(){
                        row = $j(this).closest("tr");
                        values.push({ 
                        //-----Puts the value of selected row columns on the basis of it having any value or not, if 
                        not a blank value is added-------//
                            Column1        : row[0].cells[1] != null ? row[0].cells[1].innerText : '',
                            Column2        : row[0].cells[2] != null ? row[0].cells[2].innerText : '',
                            Column3        : row[0].cells[3] != null ? row[0].cells[3].innerText : '',
                            Column4        : row[0].cells[4] != null ? row[0].cells[4].innerText : '',
                            Column5        : row[0].cells[5] != null ? row[0].cells[5].innerText : '',
                            Column6        : row[0].cells[6] != null ? row[0].cells[6].innerText : '',
                            Column7        : row[0].cells[7] != null ? row[0].cells[7].innerText : '',
                            Column8        : row[0].cells[8] != null ? row[0].cells[8].innerText : '',
                        });
                    });
                    $j("#myTableExportBodyPdf").empty();  //----Making the table empty everytime you click the 
                     export button-----//

                    //----Pushing all data in empty table-----//
                    var $tbody = $j("#mytableExportSelectedPdf tbody");
                    var tabledata = "";
                    for(var i = 0; i < values.length; i++ ){
                        tabledata = "";
                        tabledata += "<tr>";
                        tabledata += "<td>" + values[i].Column1+ "</td>";
                        tabledata += "<td>" + values[i].Column2+ "</td>";
                        tabledata += "<td>" + values[i].Column3+ "</td>";
                        tabledata += "<td>" + values[i].Column4+ "</td>";
                        tabledata += "<td>" + values[i].Column5+ "</td>";
                        tabledata += "<td>" + values[i].Column6+ "</td>";
                        tabledata += "<td>" + values[i].Column7+ "</td>";
                        tabledata += "<td>" + values[i].Column8+ "</td>";
                        tabledata += "</tr>";
                        $tbody.append(tabledata);
                    }
                }**

               //-----Empty table which is not displayed on the page-----//
              <table class="tablesorter" id="mytableExportSelectedPdf" style="display:none; font-size: 12px; overflow:auto;" data-tableexport-display="always" data-toolbar="#toolbar">
            <thead>
                <tr>
                    <th class="headerRow">Column1</th>
                    <th class="headerRow">Column2</th>
                    <th class="headerRow">Column3</th>
                    <th class="headerRow">Column4</th>                                         
                    <th class="headerRow">Column5</th>
                    <th class="headerRow">Column6</th>
                    <th class="headerRow">Column7</th>
                    <th class="headerRow">Column8</th>
                </tr>
            </thead>
            <tbody id="myTableExportBodyPdf">
                    //-----Empty Body of the table to export------//
            </tbody>
        </table>

         After that wherever you are exporting just provide the table Id which you have just populated 
         dynamically in order to export as follows :- 

         $j('#mytableExportSelectedPdf').tableExport({type:'pdf', 
                                fileName: 'Export',
                                jspdf:{
                                    orientation: 'l',
                                    format: 'a3',
                                    theme: 'grid',
                                    margins: {left:20, right:10, top:20, bottom:20},
                                    autotable: {
                                        styles: {
                                                overflow: 'linebreak',
                                                columnWidth: 105
                                            },
                                        tableWidth: 'auto',
                                    }
                                }
                            });

Hope this helps. In case of any issues, please feel free to ask over here.

Thanks,
Sraiz

**Comment by prog20901** [comment]
@SRaiz will go through the above. also, see whether you can help out or add comments in the existing reported open issues if possible.

**Comment by hhurz** [comment]
@SRaiz Thanks for your detailed description. Now I got it what you want to do. There is already an option that you could use for exporting selected rows: ```ignoreRow```. Using this option there is no need for a temporary table and your code can be reduced to this:

```javascript
var ignoredRows = [];

$j("#mytable1 input[name=inputChkBox]:not(:checked)").each(function(){
  ignoredRows.push($(this).closest("tr").index()+1);
});

$j('#mytable1').tableExport({type:'pdf', 
                       fileName: 'Export',
                       ignoreRow: ignoredRows,
                       jspdf:{
                           orientation: 'l',
                           format: 'a3',
                           theme: 'grid',
                           margins: {left:20, right:10, top:20, bottom:20},
                           autotable: {
                               styles: {
                                       overflow: 'linebreak',
                                       columnWidth: 105
                                   },
                               tableWidth: 'auto',
                           }
                       }
                   });
```

FYI: I also added a working [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/selectedRows.html) to the test folder of this project

**Comment by prog20901** [comment]
@hhurz can you integrate this in your main example where it has lots of export options?

**Comment by SRaiz** [comment]
@hhurz ...I tried to use the above ignoredRows attribute but for them the data(columns) which are not present on the page could not be exported. That is why I had to make a dynamic table.

But for the data which is on the table and that needs to be exported we can use IgonreRow attribute. 

Thanks
Sraiz
