### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by RZsam** [hhurz/tableExport.jquery.plugin#188]
how to add utf-8 to tableExport? arabic alphabet are seprated in png

**Comment by hhurz** [comment]
May be this is a duplicate of issue #159. If not, please provide more information of what you intend to do.

**Comment by RZsam** [comment]
@hhurz yeah I've read that issue too .I want to know is anyway to support utf-8?
 somehow you managed to fix it in excel

**Comment by hhurz** [comment]
In which format do you want to export to? In case of pdf, it is only possible with pdfmake as pdf producer. jsPDF is only able to export a few utf8 characters, but defenitely no arabic text.

**Comment by RZsam** [comment]
@hhurz with pdfmake arabic text is possible?

**Comment by hhurz** [comment]
I added a [pdfmake example for arabic text](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/arabicPdfmake.html) based on the code provided in issue #159.
