### ISSUE TITLE
PNG only exports viewable portion of table

### ISSUE THREAD

**Issue by schutze** [hhurz/tableExport.jquery.plugin#191]
The PNG option only exports the portion of the table that is currently viewable in the browser window.  If you lower the browser magnification, more rows of the table are included in the exported PNG.
The PNG option should export the entire HTML table and not just the rows that are currently shown.

**Comment by hhurz** [comment]
This plugin uses [html2canvas](https://github.com/niklasvh/html2canvas) to export a html table as png image. The result image is a screenshot of the table as you can see it on the screen.

**Comment by simogeo** [comment]
Which is a weired behavior, indeed.
Here is a discussion related to this "feature" : https://github.com/niklasvh/html2canvas/issues/622#issuecomment-289430228

For my part, I added a piece of js to export my whole table. You should just scroll to top before exporting to PNG. Not very user friendly but at least, it works.
