### ISSUE TITLE
ignoreColumn not supported for PNG?

### ISSUE THREAD

**Issue by schutze** [hhurz/tableExport.jquery.plugin#192]
It seems that type:'png' ignores the ignoreColumn setting.  This is my jQuery:

`$('#tableData').tableExport({type:'png', fileName: 'ExportData', escape:'false', ignoreColumn:'[4]'});`

The end result is a PNG that includes column 4 (I realize the setting is a zero based array).  If I use a different type, like 'excel' or 'txt', the column is not included in the output.

**Comment by hhurz** [comment]
This plugin uses [html2canvas](https://github.com/niklasvh/html2canvas) to export a html table as png image. The result image is a screenshot of the table as you can see it on the screen. Thus all options to manipulate the table before export are not working for png format.
