### ISSUE TITLE
onMsoNumberFormat for export to .xlsx ?

### ISSUE THREAD

**Issue by mlbaquerizo** [hhurz/tableExport.jquery.plugin#193]
I am generating a table in JS and then trying to export it using
```
$table.tableExport({
    type: "xlsx",
    worksheetName: "wsName",
    fileName: "file",
    displayTableName: false,
    headings: true,
    onMsoNumberFormat: msoNumberFormat
});
```
```
function msoNumberFormat(cell,row,col){
    var result = "";
    if(col==0){
        result = "\\@";
    }
    return result;
}
```

This should work when using `type: "excel"` but I need to use `type: "xlsx"`. Is this supported?

**Comment by mlbaquerizo** [comment]
To be clear I need to keep leading zero's in the exported file. If onMsoNumberFormat does not work I am open to any advice on another way to get this working...

**Comment by hhurz** [comment]
```onMsoNumberFormat``` is only supported when exporting to Excel 2000 html format. This plugin uses [js-xlsx](https://github.com/protobi/js-xlsx) to export to Excel 2007+ XML format which doesn't support mso-number-format strings. Perhaps you can try to make a string out of the number value, so excel doesn't treat it as a number. To do this use ```onCellData``` or ```onCellHtmlData``` and prepend a space to the regarding number value.

**Comment by mlbaquerizo** [comment]
Thanks for the reply. I tried your suggestions with no success. Also tried wrapping the value in various html tags (div, span, pre...), nothing worked. I'm sure there's a good way to make excel treat the value as a string, I'll see if I can hack away for a little longer and reply back if I find something.

**Comment by hhurz** [comment]
Try latest release 1.9.5
I added some code that let you use onCellData to return the cell data value as a specific data type. With that you can turn numbers to strings which excel will treat as text and so keep any leading zeros. 

Example that returns all numeric values of the first table colunm as strings:
```javascript
    function OnCellData(cell, row, col, data) {
      var result = data; // default data type: string
      if (result != "" && (row < 1 || col > 0)) {
        if ( result == +result )
          result = +result; // data type mumeric
      }
      return result;
    }
```
