### ISSUE TITLE
Not allowed to navigate top frame to data URL error

### ISSUE THREAD

**Issue by dunblanco** [hhurz/tableExport.jquery.plugin#198]
Hi I'm getting this error using tableexport plugin ... Not allowed to navigate top frame to data URL: .....

i'm using this code:

` <script>
  $(function () { $('#rcc_importe').DataTable({ "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]], iDisplayLength: 10,  buttons: ['pdf'] });});
  jQuery(function ($) {
        $("#imp_export_xls_Button").click(function () { $('#rcc_importe').tableExport({type:'excel', headings: true, trimWhitespace: true, bootstrap: true}); });
	$("#imp_export_pdf_Button").click(function () {
			$('#rcc_importe').tableExport( { 
                           type:'pdf',
                           jspdf: {orientation: 'p',
                                   margins: {left:20, top:10},
                                   autotable: { 
                                        style: {
					cellPadding: 5, fontSize: 10, font: "helvetica", lineColor: 200, lineWidth: 0,
					fontStyle: 'normal', overflow: 'ellipsize', fillColor: false, textColor: 20, 
                                        halign: 'left', valign: 'middle', columnWidth: 'auto'
                                        }
			          }
		           }
                       });
		});
  });
</script>`

Any idea?
thaks in advance

**Comment by hhurz** [comment]
Are you using Chrome? Does this happen when exporting to pdf only? 
When searching for "Not allowed to navigate top frame to data URL" there are a bunch of results.. E.g.:
https://stackoverflow.com/questions/45603201/window-is-not-allowed-to-navigate-top-frame-navigations-to-data-urls

**Comment by prog20901** [comment]
@hhurz do u remember i got the same error due to referring other javascript files? i guess you have fixed this issue previously for me

**Comment by prog20901** [comment]
https://datatables.net/forums/discussion/44202/not-allowed-to-navigate-top-frame-to-data-url#latest

**Comment by hhurz** [comment]
@jkathir In the link above you are referring to the original version of this plugin, which seems to be abandoned but still be owned by [kayalshri](https://github.com/kayalshri/tableExport.jquery.plugin). Please don't mix issues from the original version with issues from my forked version. Thanks.

@dunblanco Just do be clear: You are using my forked version and not kayalshr's original version?
