### ISSUE TITLE
New integration of supporting audio player

### ISSUE THREAD

**Issue by prog20901** [hhurz/tableExport.jquery.plugin#199]
Below is the discussion of open source audio player - 

https://github.com/pupunzi/jquery.mb.miniAudioPlayer/issues/12

It has been successfully working and you can go through the last few discussion with sample html.

It would be great if you could integrate and provide an option for audio player to support mp3 and other audio files. 

Please have a look at it and it should take less time to integrate then you think.

**Comment by prog20901** [comment]
Datatable click event for reference: http://beqi.datatables.net/forums/discussion/44723/playing-music-outside-of-the-datatable

**Comment by hhurz** [comment]
You are aware of that this plugin is for exporting html tables into several document formats? So what does a mp3 player have to do with that?

**Comment by prog20901** [comment]
right. can we have extension of the plugin as long as it doesn't affect the original functionality.

**Comment by schutze** [comment]
Agreeing with @hhurz point, this request does not make any sense.  Why are you suggesting functionality that has nothing to do with the intention of this plugin?

**Comment by prog20901** [comment]
@schutze no problem. kindly ignore this.
