### ISSUE TITLE
support to Alloy UI

### ISSUE THREAD

**Issue by prog20901** [hhurz/tableExport.jquery.plugin#200]
Hi,

I come across an alloy UI and we can add the audio player for mp3 files easily for cells. Not sure it comes as open source and the license says - https://github.com/liferay/alloy-ui/blob/master/LICENSE.md - Software License Agreement (BSD-3-Clause License)

example code for an audio player to play, stop and pause 

can you please go through and see whether this also can included if the license is open source and free to use it?

thanks. 

example for reference..

`<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0" /> <title>AlloyUI Audio Demo</title> <script src="https://cdn.alloyui.com/3.0.1/aui/aui-min.js"></script> <link href="https://cdn.alloyui.com/3.0.1/aui-css/css/bootstrap.min.css" rel="stylesheet"></link> <style> #container { height: 40px; margin-left: 10px; position: relative; width: 300px; } </style> </head> <body> <div id="container"> <div id="demo"></div> <br> <a class="btn btn-success" href="#" id="play-btn" role="button"> <span class="glyphicon glyphicon-play"></span> Play </a> <a class="btn btn-danger" href="#" id="pause-btn" role="button"> <span class="glyphicon glyphicon-pause"></span> Pause </a> </div> <script> YUI({ filter: 'raw' }).use('aui-audio', function(Y) { audio = new Y.Audio({ boundingBox: '#demo', fixedAttributes: { allowfullscreen: 'true' }, oggUrl: 'assets/bc.ogg', url: 'assets/bc.mp3' }).render(); audio.after('play', function() { Y.log('play'); }); audio.after('pause', function() { Y.log('pause'); }); Y.one('#play-btn').on('click', function(e) { e.preventDefault(); audio.play(); }); Y.one('#pause-btn').on('click', function(e) { e.preventDefault(); audio.pause(); }); }); </script> <script> function myFunction() { audio.pause(); audio.set('url', 'https://www.mfiles.co.uk/mp3-downloads/Toccata-and-Fugue-Dm.mp3'); audio.load(); audio.play(); } </script> <br/> <br/> <br/> <br/> <button onclick="myFunction()">Click me</button> </body> </html>`

**Comment by prog20901** [comment]
this may not be applicable for the intention of the plugin. however can we have extension of the plugin as long as it doesn't affect the original functionality.

**Comment by schutze** [comment]
This request does not make any sense. Why are you suggesting functionality that has nothing to do with the intention of this plugin?  And why did you create more than one post for the same thing? #199

**Comment by prog20901** [comment]
@schutze no problem. kindly ignore this.
