### ISSUE TITLE
Multiple worksheets and .xlsx file extension

### ISSUE THREAD

**Issue by ayellutero** [hhurz/tableExport.jquery.plugin#202]
Is it possible to have multiple tables exported in their own worksheets? If so, how? I tried using this example,

```
$('table').tableExport({
        type:'excel',
        excelFileFormat:'xmlss',
        worksheetName: ['Table 1','Table 2', 'Table 3']
});
```
but I can't seem to get it to work. It only exports one specific table with a worksheet name 'Table 1,Table 2,Table 3'. I don't know how to get multiple tables either. Please help.

Also when I download an excel file, its default file extension is .xml, not .xlsx. How do I fix this? I tried changing the excelFileFormat to 'xlsx' and it produces an .xls file.

**Comment by ayellutero** [comment]
P.S. My blade file contains multiple tables but the plugin is able to export only the first table. I tried changing $('table') to $('#tableID') but it produces a blank file.

**Comment by hhurz** [comment]
See this working [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/multipleExcel.html) 
Multiple tables are only supported for excelFileFormat 'xmlss'  which is the XML Spreadsheet 2003 file format. If in your case  only one table can be exported, I guess that your jQuery table selector isn't working. 

The file extension for the xmlss format is XML which cannot be changed by an option in the current version of the plugin. To change it anyway you need to save the file by yourself:
```javascript
var xmlssData = $('table').tableExport({
        type:'excel',
        excelFileFormat:'xmlss',
        worksheetName: ['Table 1','Table 2', 'Table 3'],
        outputMode: 'string'
});

var blob = new Blob([xmlssData], {type: "application/xml;charset=utf-8"});
saveAs(blob, 'myfilename.xlsx');
});
```

**Comment by ayellutero** [comment]
@hhurz I just figured out why the output doesn't produce multiple sheets. Exporting multiple tables into their own separate worksheets don't work with navigation tabs. Thank you. Your response helped. However, the outputs are still in .xml form. I really need an .xlsx or .xls output because my tables have custom formatting. I tried your code (put it into a function) but nothing happens.

EDIT: Got it. It's now downloading a file with an .xlsx file extension. I tried to open it but there was an error saying the file is corrupted. 

EDIT 2: I changed  the extension of 'myfilename.xlsx' to .xls. MS Excel was able to open it. The problem now is that the format or custom look of the table headers are completely gone. Is there any way to have customized table headers and multiple worksheets in an .xls or .xlsx file all at once? Or do I have to manually set a template in a variable?

**Comment by hhurz** [comment]
@EDIT 1: Although you changed the files extension to xlsx, the content of the file didn't change to xlsx format! It remains in xml format. That explains the corruption error.

@EDIT 2: I'm sorry, but there is no styling support for the xmlss format, which is the only excel format that supports multiple tables. Also there is no template variable you could set. But I take this as a feature request and put it on the list...

**Comment by ayellutero** [comment]
@hhurz I see. There's nothing I could do then. Thank you very much again for the reply.

**Comment by rfossella** [comment]
Has anyone had any luck exporting XLSX files?

**Comment by faisalemir** [comment]
i use this code and working..
`var xmlssData = $('#exSummary, #exDetail').tableExport({
                type:'excel',
                escape: false,
                mso: {
                    fileFormat:'xmlss',
                    worksheetName: ['Summary','Detail']
                },
                outputMode: 'string'
            }),
            blob = new Blob([xmlssData], {type: "application/vnd.ms-excel;charset=utf-8"}),;

            saveAs(blob, 'fileName.xls');`

**Comment by faisalemir** [comment]
i use this code and working..
`var xmlssData = $('#exSummary, #exDetail').tableExport({
type:'excel',
escape: false,
mso: {
fileFormat:'xmlss',
worksheetName: ['Summary','Detail']
},
outputMode: 'string'
}),
blob = new Blob([xmlssData], {type: "application/vnd.ms-excel;charset=utf-8"}),;
saveAs(blob, 'fileName.xls');`

**Comment by faisalemir** [comment]
i use this code and working..
```
var xmlssData = $('#tblSummary, #tblDetail').tableExport({
        type:'excel',
        escape: false,
        mso: {
                    fileFormat:'xmlss',
                    worksheetName: ['Summary','Detail']
         },
        outputMode: 'string'
 }),
blob = new Blob([xmlssData], {type: "application/vnd.ms-excel;charset=utf-8"});

saveAs(blob, 'fileName.xls');
```

**Comment by poplanchong123** [comment]
i change tableExport.js a part of sourse code，as follows
```
else if ( defaults.type === 'excel' && defaults.mso.fileFormat === 'xlsx' ) {
           var len = defaults.mso.worksheetName.length;
            var workbook = XLSX.utils.book_new();
            if (Array.isArray(defaults.mso.worksheetName) && len && (len === el.length)) {
                var fileType = '.xlsx';
                for (var i = 0; i < len; i++) {
                    var sheetName = defaults.mso.worksheetName[i];
                    var table = el[i];
                    var ws = XLSX.utils.table_to_sheet(table);
                    XLSX.utils.book_append_sheet(workbook, ws, sheetName);
                }
                var wbout = XLSX.write(workbook, {type: 'binary', bookType: defaults.mso.fileFormat, bookSST: false});
                try {
                    blob = new Blob([jx_s2ab(wbout)], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8'});
                    saveAs(blob, defaults.fileName + fileType);
                } catch (e) {
                    downloadFile(defaults.fileName + fileType,
                        'data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8,',
                        jx_s2ab(wbout));
                }
                return;

            }
...blew sourse code
```

i use this code and working

```
 $('#table1,#table2').tableExport({
            type: 'excel',
            mso: {
                fileFormat: 'xlsx',
                worksheetName: ['Table 1', 'Table 2']
            },
});
```

**Comment by hhurz** [comment]
@poplanchong123 Thanks a lot for your contribution, I will have a look on it and probably I will merge your code.

**Comment by gadget00** [comment]
Was this ever merged in the code?  Im having this xlsx need as well, but dont know how to implement this code snippet  to have it export XSLX format as it should be, thank you

**Comment by hhurz** [comment]
@gadget00: The code snippet is integrated since February 2019. Unfortunately, this issue was not closed after that.
