### ISSUE TITLE
Right to Left Sheet

### ISSUE THREAD

**Issue by bshafiei-ir** [hhurz/tableExport.jquery.plugin#203]
Hi
Im using for plugin for converting table to excel.
I need change sheet direction, how can do it?

**Comment by bshafiei-ir** [comment]
I found it's solution.
after
docFile += "<x:Name>";
                    docFile += defaults.worksheetName;
                    docFile += "</x:Name>";
we should add following line;
docFile += '<x:WorksheetOptions><x:DisplayRightToLeft/></x:WorksheetOptions>';

**Comment by hhurz** [comment]
Thanks a lot for reporting this issue and for providing a solution for it. So i could add a new export option ```excelRTL``` By setting this option to true Excel displays data from right to left.
