### ISSUE TITLE
Export file content error，why?

### ISSUE THREAD

**Issue by shinehertheway** [hhurz/tableExport.jquery.plugin#205]
First of all, thank you for your sharing.
I have an issue,I export the excel file, the first column of data displays the first row of the first column of data, other columns are normal, why?
The JavaScript I introduced is as follows：
`<script type="text/javascript" src="${APP_PATH}/static/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="${APP_PATH}/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>  
<script src="${APP_PATH}/static/dist/bootstrap-table.min.js"></script>  
<script src="${APP_PATH}/static/dist/extensions/export/bootstrap-table-export.js"></script>
<script src="${APP_PATH}/static/libs/tableExport.min.js"></script>`

`$("#table").bootstrapTable({  
	            method: "get",
	            url: "${APP_PATH}/Controller/querylist.do", 
	            method: 'get', 
	            sidePagination: "server",    
	            pageNumber:1,      
	            pageSize: 5,  
	            pageList: [5,10, 25, 50, 100], 
	            showExport: true,                     
	            exportDataType: "basic", 
	          });`
The relevant code is all about this.

**Comment by hhurz** [comment]
I'm sorry, without seeing the html code I'm not able to tell you whats going wrong. Additionally I'm not sure about what you mean with "the first column of data displays the first row of the first column of data".

**Comment by shinehertheway** [comment]
i export the excel file,the first row is same,this is not my want,for example,the first row,i need is number sequence, 1,2,3,4,5. but now is all the same.this issue i need how to solute it

**Comment by hhurz** [comment]
Sorry but the information you provided until now, doesn't let me answer your question.
