### ISSUE TITLE
Colspan in case of xmlss

### ISSUE THREAD

**Issue by surabhi6** [hhurz/tableExport.jquery.plugin#206]
First of all, Great plugin!

I want to export multiple tables from html to excel. Different table in different sheet in same workbook.
I was able to do that using your plugin but styling is not there. 
I just want to habdle colspan/rowspan. Please help its urgent.

**Comment by surabhi6** [comment]
It can be done using ss:MergeAcross

**Comment by hhurz** [comment]
Last commit should cover your request. Try it if you like to. Thanks.
