### ISSUE TITLE
Export function not working on Microsoft Edge navigator

### ISSUE THREAD

**Issue by promailson** [hhurz/tableExport.jquery.plugin#207]
Does anybody know how to make it work on Edge? It works perfectly on Chrome and Firefox.

Thanks.

**Comment by hhurz** [comment]
The plugin works with edge for me, Unable to reproduce your issue. Further details needed.

**Comment by promailson** [comment]
When trying to download in any type of file, the error appears as the image:
vnd_ms-excel; base64 can not be downloaded.

![error](https://user-images.githubusercontent.com/2487705/32954656-e298a5d0-cb9a-11e7-9a19-b2fe71fcd833.png)

**Comment by hhurz** [comment]
Thanks for providing more details on this issue, The problem does occure when you do not include FileSaver.js to save an export file. I fixed this within the last commit.

**Comment by promailson** [comment]
Now it worked. Thank you for your help.
