### ISSUE TITLE
How to get the content that is going to be exported?

### ISSUE THREAD

**Issue by arivera12** [hhurz/tableExport.jquery.plugin#208]
Currently I need to get the data that is being exported by the plugin and send it to the server. How can we achieve this?

**Comment by hhurz** [comment]
Use the ```outputMode``` option. When setting it to ```outputMode: 'string'``` tableexport() will return its output as a raw string. Or you can set it to ```outputMode: 'base64'``` in case you prefer to get a base64 encoded string.

**Comment by arivera12** [comment]
Let me give it a try I will reply back soon.

**Comment by jorgerc85** [comment]
Hi. I'm having a similar issue on my project. ~but~ I'm having trouble capturing the output of the tableexport() function. Do you mean the output of `$(tableElem).tableExport(options)`? I tried capturing the output of that but all I get is the element(s) that are used to make the exported file.

**Comment by jorgerc85** [comment]
I ended up using the `onAfterAutotable` hook to capture the output before giving the file to the user and still be able to send the data to the server.

```
var options = {
  type: 'pdf',
  outputMode: 'file',
  jspdf: {
    autotable: {
      tableExport: {
        onAfterAutotable: function(table, options) {
          // base64 encoded data.
          options.tableExport.doc.output('datauri');
        }
      }
    }
  }
};
```

**Comment by hhurz** [comment]
Thanks for sharing your solution. This is the best way to achieve both: 1st normal download of the export result and 2nd capturing the export result for further processing.
In case you just want to get the output data and not to download it as file, you can get the data from the result of the tableExport function call:

```var capturedData = $('#table').tableExport({type:'pdf', outputMode:'base64'});```

In case you want to capture the data unencoded use the option ```outputMode:'string'```
