### ISSUE TITLE
How to export several tables into one excel file?

### ISSUE THREAD

**Issue by gundamboyx** [hhurz/tableExport.jquery.plugin#209]
I have several tables in my web page.
for example：<table id="table1"></table><table id="table2"></table>......
and i use bootstrap-table to load data and display these tables.
now i have to export all these tables into only one excel file, table1 to sheet1,table2 to sheet2,and so on.
is it possible to use tableExport to do this?and how?

**Comment by hhurz** [comment]
See this working [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap4.html)
Multiple tables can be exported into a single excel file using the excel file format 'xmlss' only, which is the XML Spreadsheet 2003 file format.

**Comment by gundamboyx** [comment]
$('#4d_all,#4d_wj').tableExport({type:'excel',
                                                     excelFileFormat:'xmlss',
                                                     worksheetName: ['Table 1','Table 2']});
<table id="4d_all"/><table id="4d_wj"/>
I tried but failed.
The excel file only contain one sheet--Table 1.

**Comment by gundamboyx** [comment]
I may find the problem.
My tables are contained in tabs.So only one table can be seen at one time in my page.  The others may not be loaded.

**Comment by hhurz** [comment]
That could be the reason for your problem.

**Comment by hejiheji001** [comment]
@gundamboyx  try save the xml content of every tab by js, and then combine, then export xls.
