### ISSUE TITLE
格式与文件扩展名指定的格式不一致

### ISSUE THREAD

**Issue by yuxiao97** [hhurz/tableExport.jquery.plugin#212]
你好,不知中文能否看懂,在打开下载的excel文件时,出现如下提示,请问如何解决,谢谢!
![image](https://user-images.githubusercontent.com/27430795/34022977-63b5f648-e17d-11e7-8588-a455bfce3253.png)

**Comment by hejiheji001** [comment]
Just press "Yes". Please refer to 

[English: The file format differs from the format that the file name extension specifies](https://support.microsoft.com/en-us/help/948615/error-opening-file-the-file-format-differs-from-the-format-that-the-fi)

[中文: 打开文件时出错:"文件格式与文件扩展名指定的格式不同"](https://support.microsoft.com/zh-cn/help/948615/error-opening-file-the-file-format-differs-from-the-format-that-the-fi)

按“是"就好了

出现这个提示的原因是你使用了多工作表形式导出数据，这种情况下文件实际上是特殊结构的XML文件，仅仅是手动改成了XLS而已。Excel可以识别这种格式，但是新版Excel额外加入了一个提示框用以告诉用户可能的风险。旧版Excel没有这个问题。

为啥我知道？因为这个功能我做的。。。

以后建议用英文吧，原作者看不懂中文的（大概）

**Comment by hhurz** [comment]
Hello all, with help of Google translator I understood the chinese text of this issue ;-) 
@hejiheji001: 感謝您的支持！ I think your description and the link you provided explains the background and the reason of this problem.
Beside changing some registry entries to avoid the excel warning, the only solution I know would be to change the extension of the exported file from XLS to HTML. 
To achieve that during export I'm thinking about to provide an option to change the file extension in one of the next versions of the plugin.

**Comment by yuxiao97** [comment]
Thanks all you help @hejiheji001 @hhurz , the author's reply i can read, i found another question, the css can not apply the export file。

**Comment by D-kylin** [comment]
@Yuxiao97 作者没有对网页中的CSS样式作处理，所以导出的文件也没有的，只有标题一类做了加粗。

**Comment by yuxiao97** [comment]
> @yuxiao97 作者没有对网页中的CSS样式作处理，所以导出的文件也没有的，只有标题一类做了加粗。

不知有有没有对导出excel有更好支持的第三方框架
