### ISSUE TITLE
PDF Could not set fontSize for specific cell

### ISSUE THREAD

**Issue by milacay** [hhurz/tableExport.jquery.plugin#214]
Hi,  Great Job on this plug-in!  I really like it.
I am using the option "jsPDF-AutoTable: inherited", I could not figure out how to set the fontSize for specific cell to "Bold" or different size.  

For example, if I have a cell `<td colspan="2"  style="font-size:50;">Colspan</td>` in a table.  Is there a workaround to set the fontSize = 40?

Thanks,

**Comment by hhurz** [comment]
Hi, actually ```font-size``` is not supported to inherit. Regarding "bold" try to set ```font-weight: bold``` or ```font-weight: 700``` in your css

**Comment by milacay** [comment]
Thank you for responding.  I tried but `font-weight: bold` or `font-weight: 700` in my css, but no luck.  Any advice?
