### ISSUE TITLE
font-weight: Bold Is Not Working.

### ISSUE THREAD

**Issue by milacay** [hhurz/tableExport.jquery.plugin#215]
Hi,
I am using the option "jsPDF-AutoTable: inherited", I tried both `font-weight: bold` or `font-weight: 700` in CSS style and it is not working.  I couldn't continue my project unless I get this to work.  Would you please show me a workaround if possible.  

Thanks in advance.

**Comment by hhurz** [comment]
Hi, I added a working [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/cssPdf.html). Please have a look on it.

**Comment by milacay** [comment]
It works perfect.  Thank you so much for the example.   I missed the `fontStyle: 'inherit'`.
