### ISSUE TITLE
Please Help !

### ISSUE THREAD

**Issue by revolrevol** [hhurz/tableExport.jquery.plugin#216]

**Comment by revolrevol** [comment]
Hello,

I see thead data on each row on exported excel data. How can i remove thead data on every cell ?

Thank you.

**Comment by hhurz** [comment]
To answer your question I need more details about what and how you try to export. Providing an example would be very helpfull.

**Comment by revolrevol** [comment]
Hi again,

mytable table ss: http://izle.dcptr.com:8080/share.cgi?ssid=04mKrZT
exported excel table ss: http://izle.dcptr.com:8080/share.cgi?ssid=0FAxmG4

My Button html data:
<button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>

My Table:
<table width="100%" cellspacing="0" style="font-size:x-small;" class="tablesaw table-bordered table-hover no-footer "  id="myTable" data-tablesaw-sortable >
                                <thead>
                                  <div>
                                      <div class="text-muted" style="width:200px;float:left;display:inline-block;">
                                      </div>
                                      <div style="margin-left:200px;float:right">
                                          <button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>
                                          <h4 class="box-title"></h4>
                                      </div>
                                  </div>
                                        <tr>
                                            <th scope="col" data-tablesaw-sortable-col>Proje</th>
                                            <th scope="col" data-tablesaw-sortable-col>Sinema</th>
                                            <th scope="col" data-tablesaw-sortable-col>Gön. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Gön. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Salon Bilgileri</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Saati</th>
                                            <th scope="col" data-tablesaw-sortable-col text-center >İndir</th>
                                            <th data-tablesaw-sortable-col text-center>Mail</th>
                                        </tr>
                                      </thead>

<tbody>
<?php
		while ($row = mysqli_fetch_array($query))
		{
      $now = date("Y-m-d H:i:s");
      $amount  = $row['amount'] == 0 ? '' : number_format($row['amount']);
      $tarrihzaman = date($row['bittar'].' '.$row['bitsaat']);
      $tooltipsinema_temp=strtoupper($row['sinema']);
      $tooltipsinema=str_replace('_', ' ', $tooltipsinema_temp);
      if ($kdmsurecheck=="true"){
      if($tarrihzaman>$now){
      echo '
          <tr>

					<td >'.$row['proje'].'</td>
					<td >'.$row['sinema'].'</td>
					<td >'.$row['tarih'].'</td>
					<td >'.$row['saat'].'</td>
					<td >'.$row['salonlar'].'</td>
					<td >'.$row['bastar'].'</td>
					<td >'.$row['bassaat'].'</td>
					<td >'.$row['bittar'].'</td>
					<td >'.$row['bitsaat'].'</td>

					<td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="text-center fa fa-download text-inverse m-r-10"></i> </a></td>

					
					<td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
          data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
          data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'" data-kullanici="'.$kullanici.'"><img border="0" src="mail.png"></a>
					</td>
		</tr>';
    $counter++;
    }
  }else{
    echo '

        <tr>
        <td >'.$row['proje'].'</td>
        <td >'.$row['sinema'].'</td>
        <td >'.$row['tarih'].'</td>
        <td >'.$row['saat'].'</td>
        <td >'.$row['salonlar'].'</td>
        <td >'.$row['bastar'].'</td>
        <td >'.$row['bassaat'].'</td>
        <td >'.$row['bittar'].'</td>
        <td >'.$row['bitsaat'].'</td>

        <td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="fa fa-download text-inverse m-r-10 text-center"></i> </a></td>

        
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
        data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
        data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'"><img border="0" src="mail.png"></a>
        </td>
  </tr>';
  $counter++;
  }

			//$as=$row['kdm'];
			$_SESSION['as']=$_POST['as'];
			$total += $row['idow'];
			$no++;

		}
    //$geneltoplam=0;
		//$query = mysqli_query($conn, $sql_toplam);
		//$row_toplam= mysqli_fetch_array($query);
		//$geneltoplam=$row_toplam[0];
		//$conn->close();

		?>
</tbody>
                                <tfoot>
			<tr>
				<th colspan="5">TOPLAM</th>
				<th><?=number_format($counter-1)?></th>
			</tr>

		</tfoot>

                                </table>

**Comment by revolrevol** [comment]
My Table:
Hi again,

mytable table ss: http://izle.dcptr.com:8080/share.cgi?ssid=04mKrZT
exported excel table ss: http://izle.dcptr.com:8080/share.cgi?ssid=0FAxmG4

My Button html data:
<button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>

My Table:
<table width="100%" cellspacing="0" style="font-size:x-small;" class="tablesaw table-bordered table-hover no-footer "  id="myTable" data-tablesaw-sortable >
                                <thead>
                                  <div>
                                      <div class="text-muted" style="width:200px;float:left;display:inline-block;">
                                      </div>
                                      <div style="margin-left:200px;float:right">
                                          <button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>
                                          <h4 class="box-title"></h4>
                                      </div>
                                  </div>
                                        <tr>
                                            <th scope="col" data-tablesaw-sortable-col>Proje</th>
                                            <th scope="col" data-tablesaw-sortable-col>Sinema</th>
                                            <th scope="col" data-tablesaw-sortable-col>Gön. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Gön. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Salon Bilgileri</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Saati</th>
                                            <th scope="col" data-tablesaw-sortable-col text-center >İndir</th>
                                            <th data-tablesaw-sortable-col text-center>Mail</th>
                                        </tr>
                                      </thead>

<tbody>
<?php
		while ($row = mysqli_fetch_array($query))
		{
      $now = date("Y-m-d H:i:s");
      $amount  = $row['amount'] == 0 ? '' : number_format($row['amount']);
      $tarrihzaman = date($row['bittar'].' '.$row['bitsaat']);
      $tooltipsinema_temp=strtoupper($row['sinema']);
      $tooltipsinema=str_replace('_', ' ', $tooltipsinema_temp);
      if ($kdmsurecheck=="true"){
      if($tarrihzaman>$now){
      echo '
          <tr>

					<td >'.$row['proje'].'</td>
					<td >'.$row['sinema'].'</td>
					<td >'.$row['tarih'].'</td>
					<td >'.$row['saat'].'</td>
					<td >'.$row['salonlar'].'</td>
					<td >'.$row['bastar'].'</td>
					<td >'.$row['bassaat'].'</td>
					<td >'.$row['bittar'].'</td>
					<td >'.$row['bitsaat'].'</td>

					<td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="text-center fa fa-download text-inverse m-r-10"></i> </a></td>

					
					<td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
          data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
          data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'" data-kullanici="'.$kullanici.'"><img border="0" src="mail.png"></a>
					</td>
		</tr>';
    $counter++;
    }
  }else{
    echo '

        <tr>
        <td >'.$row['proje'].'</td>
        <td >'.$row['sinema'].'</td>
        <td >'.$row['tarih'].'</td>
        <td >'.$row['saat'].'</td>
        <td >'.$row['salonlar'].'</td>
        <td >'.$row['bastar'].'</td>
        <td >'.$row['bassaat'].'</td>
        <td >'.$row['bittar'].'</td>
        <td >'.$row['bitsaat'].'</td>

        <td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="fa fa-download text-inverse m-r-10 text-center"></i> </a></td>

        
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
        data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
        data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'"><img border="0" src="mail.png"></a>
        </td>
  </tr>';
  $counter++;
  }

			//$as=$row['kdm'];
			$_SESSION['as']=$_POST['as'];
			$total += $row['idow'];
			$no++;

		}
    //$geneltoplam=0;
		//$query = mysqli_query($conn, $sql_toplam);
		//$row_toplam= mysqli_fetch_array($query);
		//$geneltoplam=$row_toplam[0];
		//$conn->close();

		?>
</tbody>
                                <tfoot>
			<tr>
				<th colspan="5">TOPLAM</th>
				<th><?=number_format($counter-1)?></th>
			</tr>

		</tfoot>

                                </table>

**Comment by revolrevol** [comment]
Hi again,

mytable table ss: http://izle.dcptr.com:8080/share.cgi?ssid=04mKrZT
exported excel table ss: http://izle.dcptr.com:8080/share.cgi?ssid=0FAxmG4

**Comment by revolrevol** [comment]
My table html:
<table width="100%" cellspacing="0" style="font-size:x-small;" class="tablesaw table-bordered table-hover no-footer "  id="myTable" data-tablesaw-sortable >
                                <thead>
                                  <div>
                                      <div class="text-muted" style="width:200px;float:left;display:inline-block;">
                                      </div>
                                      <div style="margin-left:200px;float:right">
                                          <button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>
                                          <h4 class="box-title"></h4>
                                      </div>
                                  </div>
                                        <tr>
                                            <th scope="col" data-tablesaw-sortable-col>Proje</th>
                                            <th scope="col" data-tablesaw-sortable-col>Sinema</th>
                                            <th scope="col" data-tablesaw-sortable-col>Gön. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Gön. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Salon Bilgileri</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Saati</th>
                                            <th scope="col" data-tablesaw-sortable-col text-center >İndir</th>
                                            <th data-tablesaw-sortable-col text-center>Mail</th>
                                        </tr>
                                      </thead>

<tbody>
<?php
		while ($row = mysqli_fetch_array($query))
		{
      $now = date("Y-m-d H:i:s");
      $amount  = $row['amount'] == 0 ? '' : number_format($row['amount']);
      $tarrihzaman = date($row['bittar'].' '.$row['bitsaat']);
      $tooltipsinema_temp=strtoupper($row['sinema']);
      $tooltipsinema=str_replace('_', ' ', $tooltipsinema_temp);
      if ($kdmsurecheck=="true"){
      if($tarrihzaman>$now){
      echo '
          <tr>

					<td >'.$row['proje'].'</td>
					<td >'.$row['sinema'].'</td>
					<td >'.$row['tarih'].'</td>
					<td >'.$row['saat'].'</td>
					<td >'.$row['salonlar'].'</td>
					<td >'.$row['bastar'].'</td>
					<td >'.$row['bassaat'].'</td>
					<td >'.$row['bittar'].'</td>
					<td >'.$row['bitsaat'].'</td>

					<td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="text-center fa fa-download text-inverse m-r-10"></i> </a></td>

					
					<td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
          data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
          data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'" data-kullanici="'.$kullanici.'"><img border="0" src="mail.png"></a>
					</td>
		</tr>';
    $counter++;
    }
  }else{
    echo '

        <tr>
        <td >'.$row['proje'].'</td>
        <td >'.$row['sinema'].'</td>
        <td >'.$row['tarih'].'</td>
        <td >'.$row['saat'].'</td>
        <td >'.$row['salonlar'].'</td>
        <td >'.$row['bastar'].'</td>
        <td >'.$row['bassaat'].'</td>
        <td >'.$row['bittar'].'</td>
        <td >'.$row['bitsaat'].'</td>

        <td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="fa fa-download text-inverse m-r-10 text-center"></i> </a></td>

        
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
        data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
        data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'"><img border="0" src="mail.png"></a>
        </td>
  </tr>';
  $counter++;
  }

			//$as=$row['kdm'];
			$_SESSION['as']=$_POST['as'];
			$total += $row['idow'];
			$no++;

		}
    //$geneltoplam=0;
		//$query = mysqli_query($conn, $sql_toplam);
		//$row_toplam= mysqli_fetch_array($query);
		//$geneltoplam=$row_toplam[0];
		//$conn->close();

		?>
</tbody>
                                <tfoot>
			<tr>
				<th colspan="5">TOPLAM</th>
				<th><?=number_format($counter-1)?></th>
			</tr>

		</tfoot>

                                </table>

**Comment by revolrevol** [comment]
my export button' s html:
<button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>

**Comment by revolrevol** [comment]
my buttons html:

`<button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>`

**Comment by revolrevol** [comment]
my tables html:
`<table width="100%" cellspacing="0" style="font-size:x-small;" class="tablesaw table-bordered table-hover no-footer "  id="myTable" data-tablesaw-sortable >
                                <thead>
                                  <div>
                                      <div class="text-muted" style="width:200px;float:left;display:inline-block;">
                                      </div>
                                      <div style="margin-left:200px;float:right">
                                          <button class="btn-sm fcbtn btn btn-outline btn-primary btn-1b" href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: '<?php echo $proje?>',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>
                                          <h4 class="box-title"></h4>
                                      </div>
                                  </div>
                                        <tr>
                                            <th scope="col" data-tablesaw-sortable-col>Proje</th>
                                            <th scope="col" data-tablesaw-sortable-col>Sinema</th>
                                            <th scope="col" data-tablesaw-sortable-col>Gön. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Gön. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Salon Bilgileri</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Baş. Saati</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Tarihi</th>
                      											<th scope="col" data-tablesaw-sortable-col>Bit. Saati</th>
                                            <th scope="col" data-tablesaw-sortable-col text-center >İndir</th>
                                            <th data-tablesaw-sortable-col text-center>Mail</th>
                                        </tr>
                                      </thead>

<tbody>
<?php
		while ($row = mysqli_fetch_array($query))
		{
      $now = date("Y-m-d H:i:s");
      $amount  = $row['amount'] == 0 ? '' : number_format($row['amount']);
      $tarrihzaman = date($row['bittar'].' '.$row['bitsaat']);
      $tooltipsinema_temp=strtoupper($row['sinema']);
      $tooltipsinema=str_replace('_', ' ', $tooltipsinema_temp);
      if ($kdmsurecheck=="true"){
      if($tarrihzaman>$now){
      echo '
          <tr>

					<td >'.$row['proje'].'</td>
					<td >'.$row['sinema'].'</td>
					<td >'.$row['tarih'].'</td>
					<td >'.$row['saat'].'</td>
					<td >'.$row['salonlar'].'</td>
					<td >'.$row['bastar'].'</td>
					<td >'.$row['bassaat'].'</td>
					<td >'.$row['bittar'].'</td>
					<td >'.$row['bitsaat'].'</td>

					<td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="text-center fa fa-download text-inverse m-r-10"></i> </a></td>

					
					<td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
          data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
          data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'" data-kullanici="'.$kullanici.'"><img border="0" src="mail.png"></a>
					</td>
		</tr>';
    $counter++;
    }
  }else{
    echo '

        <tr>
        <td >'.$row['proje'].'</td>
        <td >'.$row['sinema'].'</td>
        <td >'.$row['tarih'].'</td>
        <td >'.$row['saat'].'</td>
        <td >'.$row['salonlar'].'</td>
        <td >'.$row['bastar'].'</td>
        <td >'.$row['bassaat'].'</td>
        <td >'.$row['bittar'].'</td>
        <td >'.$row['bitsaat'].'</td>

        <td align="center" class="text-center"> <a href="'.$row['kdm'].'" data-toggle="tooltip" data-original-title="İndir"> <i class="fa fa-download text-inverse m-r-10 text-center"></i> </a></td>

        
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" data-toggle="modal" data-target="#myModal" data-placement="left" data-tooltip="tooltip" title="'.$tooltipsinema.' sinemasına mail gönder"
        data-to="'.$row['sinema'].'" data-tarih="'.$row['tarih'].'" data-proje="'.$row['proje'].'" data-idow="'.$row['idow'].'"
        data-kdm="'.$row['kdm'].'" data-sinema="'.$row['sinema'].'"><img border="0" src="mail.png"></a>
        </td>
  </tr>';
  $counter++;
  }

			//$as=$row['kdm'];
			$_SESSION['as']=$_POST['as'];
			$total += $row['idow'];
			$no++;

		}
    //$geneltoplam=0;
		//$query = mysqli_query($conn, $sql_toplam);
		//$row_toplam= mysqli_fetch_array($query);
		//$geneltoplam=$row_toplam[0];
		//$conn->close();

		?>
</tbody>
                                <tfoot>
			<tr>
				<th colspan="5">TOPLAM</th>
				<th><?=number_format($counter-1)?></th>
			</tr>

		</tfoot>

                                </table>`

**Comment by hhurz** [comment]
There seems to be something special in the html result produced by your php code. When I strip down the code that you provided, I get a valid export result:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>HTML table Export</title>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="../libs/FileSaver/FileSaver.min.js"></script>
  <script type="text/javascript" src="../tableExport.js"></script>
</head>
<body>
  <table width="100%" cellspacing="0" style="font-size:x-small;" id="myTable">
    <thead>
      <div>
        <div style="width:200px;float:left;display:inline-block;">
        </div>
        <div style="margin-left:200px;float:right">
          <button href="#" onclick="$('#myTable').tableExport({type:'excel',escape:'false',htmlContent:'false',fileName: 'test',ignoreColumn: [0,10], excelstyles:['border-bottom', 'border-top', 'border-left', 'border-right']});">Excel</button>
          <h4></h4>
        </div>
      </div>
      <tr>
        <th scope="col">Proje</th>
        <th scope="col">Sinema</th>
        <th scope="col">Gön. Tarihi</th>
        <th scope="col">Gön. Saati</th>
        <th scope="col">Salon Bilgileri</th>
        <th scope="col">Baş. Tarihi</th>
        <th scope="col">Baş. Saati</th>
        <th scope="col">Bit. Tarihi</th>
        <th scope="col">Bit. Saati</th>
        <th scope="col">İndir</th>
        <th>Mail</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td >TAMIRCIKLER</td>
        <td >Adana Ariplex Avm</td>
        <td >2018-01-04</td>
        <td >15:43:27</td>
        <td >S1-S2-S3-S4-S5</td>
        <td >2018-01-05</td>
        <td >09:00:00</td>
        <td >2018-01-12</td>
        <td >09:00:00</td>
        <td align="center" class="text-center"> <a href="download"></a></td>
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" title="'K' sinemasına mail gönder">email</a></td>
      </tr>
      <tr>
        <td >TAMIRCIKLER</td>
        <td >Adana Ariplex Avm</td>
        <td >2018-01-04</td>
        <td >15:43:27</td>
        <td >S1-S2-S3-S4-S5</td>
        <td >2018-01-05</td>
        <td >09:00:00</td>
        <td >2018-01-12</td>
        <td >09:00:00</td>
        <td align="center" class="text-center"> <a href="download"></a></td>
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" title="'K' sinemasına mail gönder">email</a></td>
      </tr>
      <tr>
        <td >TAMIRCIKLER</td>
        <td >Adana Ariplex Avm</td>
        <td >2018-01-04</td>
        <td >15:43:27</td>
        <td >S1-S2-S3-S4-S5</td>
        <td >2018-01-05</td>
        <td >09:00:00</td>
        <td >2018-01-12</td>
        <td >09:00:00</td>
        <td align="center" class="text-center"> <a href="download"></a></td>
        <td align="center" class="text-center"> <a href="#" id="mailtooltip" type="button" title="'K' sinemasına mail gönder">email</a></td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <th colspan="5">TOPLAM</th>
        <th>3</th>
      </tr>
    </tfoot>
  </table>
   </body>
</html>
```
![snip](https://user-images.githubusercontent.com/4164372/34568552-78f2af44-f166-11e7-8eed-6e1b7554ebd0.png)
