### ISSUE TITLE
How to use JS options to set `data-tableexport-value`

### ISSUE THREAD

**Issue by cgfeel** [hhurz/tableExport.jquery.plugin#217]
How to use JS options to set `data-tableexport-value`

**Comment by hhurz** [comment]
I'm not sure if understand your question. ```data-tableexport-value``` needs to be set before calling the TableExport function. Thus you can do this while you create the table or after that using the related JS or jQuery functions. See [this page](https://plainjs.com/javascript/attributes/setting-getting-and-removing-data-attributes-8) or [this one](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) how you could do that. Example:

```html
to set

<td data-tableexport-value="myA">A</td>

use

var el = document.querySelector('td');
el.setAttribute('data-tableexport-value', 'myA');

or 

var el = document.querySelector('td');
el.dataset.tableexportValue = 'myA';

or

$('td').attr("data-tableexport-value", "myA");

```
