### ISSUE TITLE
For csv type,what's the max recrods for  tableExport?

### ISSUE THREAD

**Issue by tianwanfeng** [hhurz/tableExport.jquery.plugin#218]
hi,when the data size is not too large, such as 2000, it works fine, but when the size is more than 90000 ，the chrome browser may wait too long and then crash.From XHR in F12,the data is 26MB,and spends 7s. How can i export csv for large size data by tableExport ?

I use it with bootstrapTable like this:
`$('#tb_show').bootstrapTable({  
			  method: 'post',  
			  url: '/data/task/query',  
			  dataType: "json",  
			  pageSize: 10,  
			  pageNumber: 1,  
			  pageList: [10, 20, 50],  
			  sidePagination: "server", 
			  queryParams: queryParams,  
			  queryParamsType: "",
			  toolbar: "#toolbar",   
			  columns: columns, 
			  silent: true, 
			  showExport : true, 
			  exportDataType : "all", 
			  buttonsAlign:"right", 
      		  exportTypes:['csv','excel','json','xml'], 
      		  exportOptions : {
      		  	fileName: this.state.task.label, 
      		  },`

**Comment by hhurz** [comment]
There are already several issues dealing with export of large tables and problems within chrome: #70, #127, #132, #195. Perhaps those issues help you in solving yours. Finally I never figured out what caused the reported problems. There are some hints:
- Exporting highly styled html tables slows things down
- Not including Filesaver.js prevents from downloading large export results
- Using bootstrap table with an outdated version of the export plugin

**Comment by tianwanfeng** [comment]
Thank you for your suggestion. I will refer to those issues :)
