### ISSUE TITLE
兼容IE8的话要做哪些事情呢？

### ISSUE THREAD

**Issue by TKDtiny** [hhurz/tableExport.jquery.plugin#219]
兼容IE8的话要做哪些事情呢？
因项目问题，必须要兼容IE8，我在IE8下出现了trim()，forEach()未定义的错误，通过原型链解决了，但是又出现了jquery报错说对象不支持replace方法，请大神帮忙解决一下这个问题。

**Comment by hhurz** [comment]
See this: https://stackoverflow.com/questions/18327225/object-doesnt-support-addeventlistener-ie8-in-jquery  ~~Using jQuery 1.11.0 works for me with IE8~~ See comment below.

**Comment by TKDtiny** [comment]
我用的就是jquery 1.11 的版本~
c.trim(d);
不知道你这个trim方法我这样绑定到原型链能否正常使用呢？
if(typeof String.prototype.trim != 'function'){
    String.prototype.trim = function() {
        //return this.replace(/[(^\s+)(\s+$)]/g,"");//會把字符串中間的空白符也去掉
        return this.replace(/(^\s*)|(\s*$)/g, "");
        // return this.replace(/^\s+/g,"").replace(/\s+$/g,"");
    }
}

还有在IE8下forEach()也会出现问题，我也通过了原型链解决~
但是最后从tableExport.min.js中出来的对象被jq报错不支持对象。

**Comment by hhurz** [comment]
I changed the plugins source code to make it more compatible with IE8. Now it works with IE8 using jQuery up to version 1.12.4, but **NOT** for the export formats PNG, PDF and XLSX. There is also a restriction when saving DOC, JSON and XLS export results in IE8. Without changing the file extension of this formats to ".TXT", IE8 wont't let you save the file. Thats a known and unsolved IE8 bug.
So if you can live with this restrictions you can try the recently commited tableExport.min.js (it's still not released)
