### ISSUE TITLE
Data shift with PDF + data-tableexport-display="none"

### ISSUE THREAD

**Issue by maximethebault** [hhurz/tableExport.jquery.plugin#22]
Hi and thanks for this great fork!

I'm trying to export a table but I'm having a problem.
On thead, the first two columns are hidden thanks to data-tableexport-display="none".
Same for each row on tbody.

Excel, CSV and TXT export all work fine, but PDF export fails with the following error:

```
Error: col is undefined
.tableExport/</atOptions.renderCell@http://localhost:3000/bower_components/tableExport.jquery.plugin/tableExport.js:512:1
printRows/<@http://localhost:3000/bower_components/jspdf-autotable/jspdf.plugin.autotable.js:347:1
printRows@http://localhost:3000/bower_components/jspdf-autotable/jspdf.plugin.autotable.js:337:13
API.autoTable@http://localhost:3000/bower_components/jspdf-autotable/jspdf.plugin.autotable.js:90:9
.tableExport/<@http://localhost:3000/bower_components/tableExport.jquery.plugin/tableExport.js:556:15
```

I'm using the latest version from master.

Thanks for your help!

**Comment by hhurz** [comment]
Please try the last commit and give me a note if it's working or not, ty

**Comment by hhurz** [comment]
There was still an problem with hidden columns which i fixed now. Think your export should work now as desired.

**Comment by maximethebault** [comment]
It works great now, thanks!
