### ISSUE TITLE
Code incompatibilities may occur.

### ISSUE THREAD

**Issue by pppscn** [hhurz/tableExport.jquery.plugin#223]
Please note that,
jspdf-autotable#2.0.17 depends on jspdf#~1.0.178 which resolved to jspdf#1.0.272
tableExport.jquery.plugin#1.9.9 depends on jspdf#1.1.239 || 1.3.2 which resolved to jspdf#1.3.2
Resort to using jspdf#1.3.2 which resolved to jspdf#1.3.2
Code incompatibilities may occur.

**Comment by pppscn** [comment]
please update the jspdf and jspdf-autotable

**Comment by pppscn** [comment]
https://github.com/simonbengtsson/jsPDF-AutoTable/commit/5e5419bf6c3ea415ee82822424d19cf092893640

**Comment by hhurz** [comment]
Thanks for your hint. The parts of jspdf-autotable 2.0.17  that this plugin uses, should work with jsPDF 1.3.2 up to 1.3.4. At least my tests and production usage of tableexport didn't show anything else. Feel free to correct me with this.

**Comment by pppscn** [comment]
Unable to find a suitable version for jspdf, please choose one by typing one of the numbers below:
    1) jspdf#~1.0.178 which resolved to 1.0.272 and is required by jspdf-autotable#2.0.17
    2) jspdf#1.3.2 - 1.3.4 which resolved to 1.3.4 and is required by tableExport.jquery.plugin#1.9.10
