### ISSUE TITLE
Document orientation

### ISSUE THREAD

**Issue by Guite** [hhurz/tableExport.jquery.plugin#224]
Is there any way to change Word (and/or maybe Excel) document orientation to landscape? If the table to be exported has some more columns this would be very helpful.

**Comment by Guite** [comment]
Solved it by adding a new `excelLandscape` property and replacing https://github.com/hhurz/tableExport.jquery.plugin/blob/master/tableExport.js#L766 by:

```
        docFile += "<style>";
        if (defaults.excelLandscape) {
          docFile += "@page { size: landscape; mso-page-orientation: landscape; }";
        }
        docFile += "br {mso-data-placement:same-cell;}";
        docFile += "</style>";
```

**Comment by hhurz** [comment]
Thanks for your contribution. I added your changes, but changed the new option from 'defaults.excelLandscape: 0 or 1' to 'defaults.excelPageOrientation: 'portrait' or 'landscape'

**Comment by Guite** [comment]
Nice, thanks.

There is a problem in your implementation though.
`if (defaults.excelPageOrientation !== '')` should become `if (defaults.excelPageOrientation === 'landscape')` then.

**Comment by hhurz** [comment]
Fixed it. Thanks again.
