### ISSUE TITLE
Last row checked from datatable isn't export to print.

### ISSUE THREAD

**Issue by maikosantos** [hhurz/tableExport.jquery.plugin#227]
I am with a problem! When I use the checks to export the datatable, the last row not is print. The footer is work perfect, but last row is not work.

![table](https://user-images.githubusercontent.com/3418695/37787184-2924cb7e-2ddd-11e8-86d2-870bfe5fdeef.png)

**Comment by hhurz** [comment]
Sorry, I'm not able to answer this question
