### ISSUE TITLE
INVALID_CHARACTER_ERR: DOM Exception 5

### ISSUE THREAD

**Issue by yishuluo** [hhurz/tableExport.jquery.plugin#23]
I used this plugin with django platform.it works well.
When i add i18n for django,then changes webpage language from English to Chinese.It doesn't work.If webpage language back to English,it works well again.
the error is in JQuery.base64.js line 136:throw "INVALID_CHARACTER_ERR: DOM Exception 5";

**Comment by hhurz** [comment]
tableExport.js doesn't use JQuery.base64.js. Are you using the latest version? A stack trace would be helpfull to see what caused the error.

**Comment by yishuluo** [comment]
Thanks! I thinks find this BUG in other JS file that will use tableExport.js.
