### ISSUE TITLE
Formula Injection

### ISSUE THREAD

**Issue by mtaylor091** [hhurz/tableExport.jquery.plugin#230]
If you try to export data to a csv that has this string:

`=cmd|' /C calc'!A0`

it will try to open the calculator when the file is opened in excel. 

This article: https://www.owasp.org/index.php/CSV_Injection

suggests that you append a ' (quote) to any string the starts with `=,+,- or @`. 

There is already an escape option but that is using the javascript escape function
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape

**Comment by hhurz** [comment]
Thanks for reporting this issue and for pointing it out to me. I fixed this for exporting to CSV & Excel format by introducing a new option ```preventInjection``` that, as you suggested,  prepends a single quote to cell strings that start with =,+,- or @

**Comment by sebj54** [comment]
@hhurz Please add something in the documentation about this setting :)

I wondered why I add a quote in cells that contains negative values and had to dig in the issues to find out :(
