### ISSUE TITLE
how to add custom header to generated pdf file 

### ISSUE THREAD

**Issue by iadnan-diab** [hhurz/tableExport.jquery.plugin#231]
Hello , Thanks a lot for this effort to fix old repo bugs , this what i need exactly , but i want to know how to make custom header or footer in pdf file generated i want to include logo , date , and some extra information like username who generated this file 
how to do all this features ?? 
and Thanks Again

**Comment by hhurz** [comment]
Sorry for the late reply. Please see my comment in issue #118.
