### ISSUE TITLE
Only table headers getting downloaded when I use the following format

### ISSUE THREAD

**Issue by sunilsr1986** [hhurz/tableExport.jquery.plugin#233]
Please note that if I give the bootstrap table inside a td of another table. I could download only the headers not the content
"<table>

<tr>
<td>
<table id="table">
    <thead>
    <tr>
        <th data-field="name">Name</th>
        <th data-field="stargazers_count">Stars</th>
        <th data-field="forks_count">Forks</th>
        <th data-field="description">Description</th>
    </tr>
    </thead>
</table>
</td>
</tr>
</table>"

**Comment by hhurz** [comment]
There is no support of nested tables. Please see also issue #204
