### ISSUE TITLE
filter values of each column is visible in export

### ISSUE THREAD

**Issue by dasguptahirak** [hhurz/tableExport.jquery.plugin#238]
I have applied filter (bootstrap-table-filter-control.js) in my bootstrap table. But during export the filter dropdown of each column is also getting exported.

![image](https://user-images.githubusercontent.com/7932509/43438672-1a1c55ac-94ad-11e8-8f0e-f77b7c3cc32f.png)

After Export......

![image](https://user-images.githubusercontent.com/7932509/43438644-f6d7f52e-94ac-11e8-9864-4d00df72d4ed.png)

**Comment by hhurz** [comment]
This could be solved by implementing onCellHtmlData. Examples how to do this can be found in #44 and #66. The callback function will be called for ever cell during export. Within the function you can filter out the regarding cells then by returning an empty string.
