### ISSUE TITLE
when  export to excel, br-tag can't  be  recognition as a new line.

### ISSUE THREAD

**Issue by weiweibupt** [hhurz/tableExport.jquery.plugin#239]
@hhurz 
   In a bootstrap-tablethere are many lines in a cell, so  I use br- tag to change line in a <td></td> in the bootstrap-table. But when I use tableExport.js to export the table to a excel file, the br-tag  can't  be  recognition as a new line ,so all the lines written in one line in the exported excel file.   can you help me solve this problem?thank you very much

**Comment by hhurz** [comment]
Which excel file format are you trying to export to? Some example code would be helpfull. 
Or you try to implement onCellHtmlData. Examples how to do this can be found in #44 and #66. The callback function will be called for ever cell during export. Within the function you would then search for br tags in the cell text and replace them with something suitable.

**Comment by smrrrazu** [comment]
For me `<br/>` work but `<br>` does not work.
