### ISSUE TITLE
Exporting hidden columns

### ISSUE THREAD

**Issue by joshbenhamou** [hhurz/tableExport.jquery.plugin#24]
Hi

I'm using your plugin for bootstrap table, it's great so thanks very much. I was wondering if it was possible to include hidden columns in the export. I would like to limit the data that the user sees on the table whilst also being able to export it all.

Thanks for your help!
Josh

**Comment by joshbenhamou** [comment]
Just to add that I have implemented a workaround but it would be nice to stay within your plugin if at all possible.

Workaround in case anyone is trying anything similar

.[export-only-col-class] {
    position:absolute;
    visibility:hidden;
}

**Comment by hhurz** [comment]
Done. See last commit. Thanks for your comments.
BTW: your workaround will not work any longer, because the css "visibility:hidden" will be detected by the plugin from now ;)
