### ISSUE TITLE
export to excel , not all data, just those pages that I have pressed the full checkbox in the head row of page

### ISSUE THREAD

**Issue by weiweibupt** [hhurz/tableExport.jquery.plugin#240]
I use exportDataType: "selected" to export the row I selected by pressing on the checkbox, and it works well. But when I choose the full chenkbox in the head in different pages, it only exports the current page.But what I want is to export all the pages that I have pressed the full checkbox  (not all data  ,only those pages that I have pressed the full checkbox).  And  what I use is 
  sidePagination: 'client'  .   Can you help me ?Thank you very much

**Comment by weiweibupt** [comment]
exportDataType: "all"   will export all the  data,so I can't use it .

**Comment by hhurz** [comment]
Ah, now I got your problem. I thinks its a special one and it is out of scope of the tableexport plugin. One solution would be to collect all marked data of several pages in one hidden table and export this table then.

**Comment by prepared48** [comment]
I use exportDataType: "all" , but can not export all data , why ?
`
    	$('#terminalManageTable').tableExport(exportOptions);` var exportOptions = {
        		type: 'excel',
        		fileName: exportTableName,
        		ignoreColumn: [0, 8, 9], // 忽略列
        		exportDataType: "all",
        		numbers: {
        			output: false
        		}
        };`

**Comment by quliting** [comment]
i make all data to a table and hide it ;then i can export an empty excel @hhurz

**Comment by quliting** [comment]
@hhurz  in the end ;when i export table;i show it,then hiden;

**Comment by quliting** [comment]
@hhurz  so .i suggest i can export any data use columns.

**Comment by hhurz** [comment]
@quliting You could use the html data attribute ```data-tableexport-display```, then you wouldn't need to show and hide the table. This option allows you to export a hidden table.
From readme.md: ```<table style="display:none;" data-tableexport-display="always">...</table> -> A hidden table will be exported```

**Comment by quliting** [comment]
@hhurz  Ok.thank you sir .can you add some other method to support export any data with table columns .i see other plugs can do this.this is my opinion.
