### ISSUE TITLE
Persevering whitespace - do not trim option 

### ISSUE THREAD

**Issue by aronmgv** [hhurz/tableExport.jquery.plugin#241]
I have table displaying nested rows.. When I want to export such a table - it trims added whitespace at the beginning of the first column.  Every level deep it adds `&nbsp;&nbsp;&nbsp;&nbsp;`. However this is lost when exported -> thus you can no longer differentiate the structure.

Option to preserve white space at the beginning of the cell.. So you can differentiate something like this:

![image](https://user-images.githubusercontent.com/6546231/43913651-f3837460-9c05-11e8-84d8-92f86db06220.png)

Thanks, Michal

**Comment by hhurz** [comment]
Thanks for your suggestion. There is a new release available (v1.9.12) that contains two new options 'preserve.leadingWS' and 'preserve.trailingWS' (default for both: false) which will do what you requested.

**Comment by aronmgv** [comment]
Hey, it does what it says but it also takes into consideration white space used for formatting html code.. meaning the whole context of `<th>` or `<td>` has to be written inline - otherwise white space used to auto-intend that line will be exported..

**all white space you have in source code between `<th></th>` is exported**:
```
<th>
    <span>cell content</span>
</th>
```

**has to be written like this**:
```
<th><span>cell content</span></th>
```

Other thing I was not able to solve is that empty cells now contains single apostrophe:
```
"Display name",Type,IP,"First IP","Last IP",Netmask,Comment
Range2,range,',201.0.0.10,201.0.5.21,','
Range1,range,',201.0.0.10,201.0.0.21,','
NetworkGroup_8,group,',',',','
"    NetworkGroup_6",group,',',',','
"        10.0.0.20",host,10.0.0.20,',',','
"    NetworkGroup_7",group,',',',','
"        NetworkGroup_5",group,',',',','
"            NetworkGroup_4",group,',',',','
"                Range2",range,',201.0.0.10,201.0.5.21,','
"                Range1",range,',201.0.0.10,201.0.0.21,','
"            200.200.2.34",host,200.200.2.34,',',','
NetworkGroup_7,group,',',',','
NetworkGroup_6,group,',',',','
NetworkGroup_5,group,',',',','
NetworkGroup_4,group,',',',','
NetworkGroup_3,group,',',',','
NetworkGroup_2,group,',',',','
```

Example of export config:
```
elm.tableExport({
    type: 'txt',
    escape: false,
    ignoreColumn: colIgnore,
    maxNestedTables: 2,
    preserve : {
        leadingWS: true,
        trailingWS: true
    },
    fileName: (s?s:'TableExport') + formattedDate()
});
```

Any ideas? Thanks again, Michal

**Comment by hhurz** [comment]
Thanks for testing. For the single apostroph thing I confirm that this is a bug introduced recently with the new option "preventInjection". I already fixed it. 
Fixing the output of spaces used for formatting seems to be tricky. Thus I put this issue on the growing list of todo's...
