### ISSUE TITLE
Exporting into PDF -> result contains artifacts from the angular directive markup

### ISSUE THREAD

**Issue by aronmgv** [hhurz/tableExport.jquery.plugin#242]
When I export table to PDF and the table row was has e.g. angular condition it will be displayed in pdf export..

````
<td ng-if='config.columns[ 2].visible()'><span ng-repeat="t in getTimes(level) track by $index">&nbsp;&nbsp;&nbsp;&nbsp;</span><span new-bind='{{[row,config.columns[ 2].field]}}'></span></td>
````
results into this:
![image](https://user-images.githubusercontent.com/6546231/43913977-d1093914-9c06-11e8-9f63-0ac27b66058e.png)

Thanks, Michal

**Comment by hhurz** [comment]
Try to implement onCellHtmlData or onCellData. Examples how to do this can be found in #44 and #66. Both callback functions will be called for every cell during export. Within the functions you could search for tags or text that you would like to strip. The difference of the functions is, taht onCellHtmlData is called before any data parsing of the plugin and onCellData will be called after cell data has been parsed.

**Comment by aronmgv** [comment]
okay, but why does it happen only when exporting to PDF?.. when exporting to csv or txt I don't see those artifacts.. thanks

**Comment by hhurz** [comment]
Because when exporting to pdf there is an extended tag and style parsing which text formats don't have. Perhaps those parse functions would need some rework, but for now it is as it is 😎
