### ISSUE TITLE
Getting rid of jQuery dependency?? Angular 2 and above..

### ISSUE THREAD

**Issue by aronmgv** [hhurz/tableExport.jquery.plugin#246]
Hey, thanks for your work and continuous support!

I would like to confirm if you ever plan to be standalone and not dependent on jQuery? And if so what would be limitations of this library then.. I am migrating couple SPAs to the new Angular were jQuery does not belong.

Thanks, Michal

**Comment by hhurz** [comment]
I don't think I'll do that in the foreseeable future. I continued the development of this plugin after the original author didn't care about it any more and I needed such an export function for my own purposes. As the name of the plugin suggests, both the original author of the plugin and I have always seen it as an jquery extension. To make the tool independent of jquery would mean a considerable effort, for which I currently have no time. Thanks for your participations.

**Comment by aronmgv** [comment]
Thank you for the comprehensive explanation. You may close it as a reference for others :)
