### ISSUE TITLE
BUG   

### ISSUE THREAD

**Issue by acclea** [hhurz/tableExport.jquery.plugin#248]
line    1964
now this line is not  judge   type   ‘object’
else if ( htmlData !== '' ) {
so，it   need  change 
else if ( htmlData !== '' &&  typeof defaults.onCellHtmlData !== 'object' ) {

**Comment by hhurz** [comment]
Thanks for your suggestion. But it needs some explanation:
Why should defaults.onCellHtmlData become an object? defaults.onCellHtmlData is either null or a callback function. 
In case you want to skip parsing of htmldata you would implement defaults.onCellHtmlData as an empty function. 
Am I missing something?

**Comment by acclea** [comment]
<table>
<tr>
<td>id</td>
<td>name</td>
</tr>

<tr>
<td>123</td>
<td>abc</td>
</tr>

<tr>
<td>456</td>
<td>&amp;dd</td>
</tr>

<tr>
<td>789</td>
<td>ff&amp;@ee</td>
</tr>

</table>

like this,when ‘&’ appeared that throw  out  ‘$.parseHTML is not a function’，as this

Uncaught TypeError: $.parseHTML is not a function
    at parseString (tableExport.js:1965)
    at tableExport.js:802
    at HTMLTableCellElement.<anonymous> (tableExport.js:1579)
    at Function.each (base.js:2)
    at init.each (base.js:2)
    at ForEachVisibleCell (tableExport.js:1552)
    at HTMLTableRowElement.<anonymous> (tableExport.js:799)
    at Function.each (base.js:2)
    at init.each (base.js:2)
    at HTMLTableElement.<anonymous> (tableExport.js:796)

**Comment by hhurz** [comment]
I can't reproduce your problem. There are no errors when exporting your example from above into xls or pdf. Perhaps it depends on some other "special" content of your table. Anyway I suggest you try to implement the callback function onCellHtmlData like this:

``` javascript
function DoOnCellHtmlData(cell, row, col, data) {
  // Just return data in case you want to skip html parsing only.
  // Or return data after you changed it according to your demands
  return data;
}

$('table').tableExport({
  type: 'xls',
  onCellHtmlData: DoOnCellHtmlData}
);
```

**Comment by acclea** [comment]
my code ,

function exportExcel(){
            $('#tableId').tableExport({
                type:'excel',
                fileName:'test',
                excelstyles:['text-align'],
            });
        }

I don't know why my code is error,when i changed that's running.
