### ISSUE TITLE
When I export more than 10000 pieces of data, it will be stuck and the browser will crash. How to solve this problem

### ISSUE THREAD

**Issue by G0715** [hhurz/tableExport.jquery.plugin#250]
When I export more than 10000 pieces of data, it will be stuck and the browser will crash. How to solve this problem

**Comment by hhurz** [comment]
The information you provided do not allow to answer this question...

**Comment by G0715** [comment]
The problem occurred when the data volume reached tens of thousands. Not only did the browser get stuck, but the exported excel file always told the network to fail.Debug debugging found that the table string spliced by var excel exceeded the length limit of var

**Comment by G0715** [comment]
1. How to solve the length limit problem of var?
2. Do you try to export too much data?
3. How fast？

**Comment by G0715** [comment]
I tried to read the source code,It helped me a lot,but I still can't solve the problem.

Thanks.

**Comment by hhurz** [comment]
So you are trying to export to one of the excel formats. Can you tell which one?
In your second comment you mentioned a "var excel" which actually is neither declared nor used by this plugin.
There are already several issues dealing with export of large tables. Please have a look to them: #70, #127, #132, #195. Perhaps those issues help you in solving yours. Finally I never figured out what caused the reported problems. There are some hints:

- Exporting highly styled html tables slows things down
- Not including Filesaver.js prevents from downloading large export results
- Using bootstrap table with an outdated version of the export plugin

**Comment by G0715** [comment]
I found the export slow because I used the bootstrapTable merge column
[https://blog.csdn.net/jingtianyiyi/article/details/76208880](https://blog.csdn.net/jingtianyiyi/article/details/76208880)

**Comment by hhurz** [comment]
So this issue is solved for you? If yes, please close it. Thanks.
