### ISSUE TITLE
Support for Bootstrap4 dropdown changes

### ISSUE THREAD

**Issue by gallusenrico** [hhurz/tableExport.jquery.plugin#252]
Is it possible to support the new bootstrap v4 dropdown code for a correct styling.

At the moment the used template has the following code
`$export = $([
                    '<div class="export btn-group">',
                        '<button class="btn' +
                            sprintf(' btn-%s', this.options.buttonsClass) +
                            sprintf(' btn-%s', this.options.iconSize) +
                            ' dropdown-toggle" aria-label="export type" ' +
                            'title="' + this.options.formatExport() + '" ' +
                            'data-toggle="dropdown" type="button">',
                            sprintf('<i class="%s %s"></i> ', this.options.iconsPrefix, this.options.icons.export),
                            '<span class="caret"></span>',
                        '</button>',
                        '<ul class="dropdown-menu" role="menu">',
                        '</ul>',
                    '</div>'].join('')).appendTo($btnGroup);`
The styling for bootstrap v4 is not supported using this code.
I'm not a javascript expert, but maybe the best would be to set the export template depending on the bootstrapVersion-variable which is set in the bootstrap-table.js

And if it is version 4 to 
- add a `dropleft` class  to the parent div
- change the `dropdown-menu` ul element to a div and remove its role-attribute

**Comment by hhurz** [comment]
I think this is wrong place for your issue. The tableExport plugin is not specialized to bootstrap or bootstrap table and it doesn't know anything about bootstrap styling.  So please address your issue to [bootstrap table](https://github.com/wenzhixin/bootstrap-table/issues)

**Comment by gallusenrico** [comment]
> I think this is wrong place for your issue. The tableExport plugin is not specialized to bootstrap or bootstrap table and it doesn't know anything about bootstrap styling. So please address your issue to [bootstrap table](https://github.com/wenzhixin/bootstrap-table/issues)

You are so right about that, i'm very sorry for posting this here.
@hhurz Thank you very much for you fast and very helpful reply.
