### ISSUE TITLE
Export in PDF changing orientation landscape or portrait

### ISSUE THREAD

**Issue by Aragorn2004** [hhurz/tableExport.jquery.plugin#259]
Hi, i would know if it is possible changing orientation (landascape or portrait) on PDF export.

I've a large table and when i try to export files produced is always in portrait mode.

I've seen that the first Param is for landscape in jsPDF() which is l for landscape.
var pdf = new jsPDF('l', 'mm', [297, 210]); //The first Param is for landscape or portrait

but i don't know where i can do this in my implementation.

I'm using 

bootstrap-table 1.13.2 (wenzhixin) with
extension  bootstrap-table-export.js (wenzhixin) and 
tableExport.jquery.plugin Version 1.10.2

Thanks for your support.

**Comment by hhurz** [comment]
Hi, I'm not an expert for bootstrap-table, so there is no garantee for the following suggestion. I'd try something like this:
```javascript
  $(document).ready(function()
  {
    $('#table').bootstrapTable('refreshOptions', {
      exportOptions: {
        jspdf: {               // jsPDF / jsPDF-AutoTable related options
          orientation:  'l',
          unit:         'pt',
          format:       'a4',  // One of jsPDF page formats or 'bestfit' for autmatic paper format selection
          margins:      {left: 20, right: 10, top: 10, bottom: 10}
        }
      }
    });
  });
```
