### ISSUE TITLE
Option export all dont work with pagination on server

### ISSUE THREAD

**Issue by geasi** [hhurz/tableExport.jquery.plugin#26]
Hi.

The export option "all" do not work with server side pagination.
When changing it to client pagination it works.
Thanks

**Comment by hhurz** [comment]
Hi, I'm not sure if I understand your issue. Indeed this plugin only works if all table data is available on client side. Server side pagination implies that only this table data will be requested form server which belongs to the page that is to be displayed. Thus you have to find a way to retreive all data of the html table to export from the server before you use the tableExport plugin.
