### ISSUE TITLE
mso.styles not working

### ISSUE THREAD

**Issue by pavelvasev** [hhurz/tableExport.jquery.plugin#261]
mso.styles option is not working.

I'd tested with my own page (with background-color style)
and with yours `test/singleExcel.html` (with border-* styles, after adding orders to the table cells).

Exporting colored tables is a useful feature.. Please keep styling working..

**Comment by Ps-simpla** [comment]
I agree, the table with id = "excelstyles" styles do not work

**Comment by hhurz** [comment]
Thanks for reporting this issue. I fixed it and it will be available with the next release. 
FYI: Only Excel is able to view the exported styles. OpenOffice just displays an unstyled table.

**Comment by pavelvasev** [comment]
Thank you @hhurz for the hope and for clarifications! I work within LibreOffice and might check if it works there..

**Comment by hhurz** [comment]
@pavelvasev THere is no difference between LibreOffice and OpenOffice. Both do not show table styles.
