### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by ebakirmak** [hhurz/tableExport.jquery.plugin#267]
Hello hhurz,
My data contains Turkish Date but when export the data, Excel convert to English Date Format. Example: Date: 03.05.2019, Excel shows 05.03.2019. Can we change the date format type?

**Comment by hhurz** [comment]
Hi, sorry for the late answer: In case you are exporting to Excel 2000 html format (xlshtml) and you are able to modify the original html table, then you could try to add the html data attribute ```data-tableexport-msonumberformat="\@"``` to the cell that contains the turkish date. This shoud excel let treat the cell content always as text. Thats just a suggestion. I didn't try it by myself...

**Comment by ebakirmak** [comment]
Thanks hhurz.
