### ISSUE TITLE
IgnoreColumn no longer works for xlsx

### ISSUE THREAD

**Issue by jwiel86** [hhurz/tableExport.jquery.plugin#268]
Thank you for providing this plugin!  After this commit 7b8b569f93b25e71caf5ec75e0862dedf1bf33cb, it looks like IgnoreColumns for xlsx documents do not work.  Just a heads up!

**Comment by hhurz** [comment]
Thanks for reporting this. I will have a look into it...

**Comment by hhurz** [comment]
IgnoreColumns should work since release v1.10.7 again
