### ISSUE TITLE
Exported sql file cannot be run due to wrong escape string

### ISSUE THREAD

**Issue by LeoQuote** [hhurz/tableExport.jquery.plugin#269]
exported sql file looks like this :

```
INSERT INTO `Table` ('db_name') VALUES ('archer')
```
this cannot run in mysql 8.0 

```
INSERT INTO `Table` (`db_name`) VALUES ('archer')
```
this one is ok. notice the grave accent `` ` `` instead of quote ``'`` around ``db_name``

Can I configure the escape string around column names ? 

Related: https://github.com/hhyo/Archery/issues/228

**Comment by hhurz** [comment]
Currently there is no option to enclose table or column names, but I decided to provide those soon.

Update: Version 1.10.4 released which contains new options sql.tableEnclosure and sql.columnEnclosure
