### ISSUE TITLE
BOM character ï»¿ï»¿ at the beginning of exported csv file

### ISSUE THREAD

**Issue by virengujariya** [hhurz/tableExport.jquery.plugin#27]
When I export to CSV, somehow it adds ï»¿ï»¿ unicode characters at the beginning of the file. Following is my button on click event:

onClick ="$('#tablePurchasedItems').tableExport({fileName:'PurchasedGifts', type:'csv', ignoreColumn: [7], escape:'false'});"

And beginning header of csv file looks like
![image](https://cloud.githubusercontent.com/assets/5392789/9258638/75178a0a-41b1-11e5-91a6-57201acdd73f.png)

**Comment by hhurz** [comment]
CSV files exported by the plugin are utf-8 encoded which is marked with a BOM (https://en.wikipedia.org/wiki/Byte_Order_Mark) at the beginning of the file.

**Comment by hhurz** [comment]
When reading your issue subject again I noticed that you already realized that the leading bytes are a BOM. So my previous comment was some how pointless... Anyway, i just added a new option "csvUseBOM" that lets you decide if the plugin writes the BOM or not.
