### ISSUE TITLE
Exporting all data from table vanishes pagination and it is not toggled on

### ISSUE THREAD

**Issue by ksodari** [hhurz/tableExport.jquery.plugin#270]
Before Exporting All data from table with pagination
![image](https://user-images.githubusercontent.com/5551062/59421699-01a63e00-8e0a-11e9-9c96-f1d531a18b9e.png)

After Exporting All data from table makes pagination toggle off and then it does not revert back to paginated condition. Table seems to be abnormal afterwards
![image](https://user-images.githubusercontent.com/5551062/59421908-682b5c00-8e0a-11e9-90be-2192c9d16bea.png)

How to address this issue please @hhurz could you give me some insights here? Or may be you need to update your library with that functionality to check pagination is still there even after the export is performed with condition exportDataType="all"
PS: I am using bootstrap-table

Thanks in advance.

**Comment by hhurz** [comment]
Hi, I am not an expert on bootstrap tables, so I can only answer questions about the tableExport plugin, which is not specifically designed for bootstrap table. Bootstrap table uses this plugin as an "export engine" for html tables that were produced by bootstrap table. So please ask your question there or have a look into their docs, examples and faq's: https://github.com/wenzhixin/bootstrap-table. There is also a working example: https://examples.bootstrap-table.com/#extensions/export.html#view-source

**Comment by ksodari** [comment]
> Hi, I am not an expert on bootstrap tables, so I can only answer questions about the tableExport plugin, which is not specifically designed for bootstrap table. Bootstrap table uses this plugin as an "export engine" for html tables that were produced by bootstrap table. So please ask your question there or have a look into their docs, examples and faq's: https://github.com/wenzhixin/bootstrap-table. There is also a working example: https://examples.bootstrap-table.com/#extensions/export.html#view-source

Thanks for replying. Will see on the working example. Let me try with that then.
