### ISSUE TITLE
[QUESTION] issue with exporting

### ISSUE THREAD

**Issue by Skiizoo** [hhurz/tableExport.jquery.plugin#274]
Hi,

I managed to export my bootstrap table (excel) through export button with theses parameters :
	- showExport: true,
	- exportDataType: 'all'.

But i can't get working : $('#mytable').tableExport({type: 'excel'}) which is opening a corrupted file.

thanks

**Comment by hhurz** [comment]
Hi, have you seen the various bootstrap examples in [here](https://github.com/hhurz/tableExport.jquery.plugin/tree/master/test)? I think that what you are trying to do is not the right way for bootstrap table to use tableExport. Please note that I'm not a bootstrap table expert. My plugin is common jquery plugin and not specially designed for bootstrap table.

**Comment by Skiizoo** [comment]
hi !

Yes I have seen theses examples but that didn't work for me. i'll just look into the export button from bootstrap table and see how it goes
Thanks
