### ISSUE TITLE
Uncaught TypeError: Cannot read property 'utils' of undefined

### ISSUE THREAD

**Issue by bilyboy785** [hhurz/tableExport.jquery.plugin#277]
Hello i'm using bootstrap-table with export function but i get an error in console :

```
Uncaught TypeError: Cannot read property 'utils' of undefined
    at bootstrap-table-export.min.js:10
    at bootstrap-table-export.min.js:10
    at bootstrap-table-export.min.js:10
```

I followed this guide : [examples.bootstrap-table.com](https://examples.bootstrap-table.com/index.html#extensions/export.html#view-source)

**Comment by hhurz** [comment]
Hi, thats a specific question regarding bootstrap table and is not related to this plugin. Please ask your question on the bootstrap table page.
