### ISSUE TITLE
CSV Export decimal character

### ISSUE THREAD

**Issue by iwalkalone69** [hhurz/tableExport.jquery.plugin#28]
Should be possible to add an option for CSV export to decide if decimal character is a . or a ,?

I've found the function parseString() and when it is not enabled HTML, should be possible to add a replace from . to the selected character like this (line 727):

result = $cell.text().trim().replace(/\u00AD/g, "").replace('.', defaults.csvDecimalsChar); // remove soft hyphens

And adding the default parameter at the beggining, of course and detecting if it's a number.

Thanks.

**Comment by hhurz** [comment]
Thank you for your suggestion. See last commit: there is a new option "numbers" now, that defines decimal mark and thouseads seoparator of html input and export output. If one of them differs, numbers will be reformated during export process.
