### ISSUE TITLE
CSV export garbled text in IE 11

### ISSUE THREAD

**Issue by yanhuRicoh** [hhurz/tableExport.jquery.plugin#283]
CSV export feature works find in Google Chrome and Firefox, but it export garbled text(Original text is Japanese) in IE11 browser, can you please check this issue? Thank you.

Below is the exported csv file in Google Chrome and Firefox:
![data list google](https://user-images.githubusercontent.com/19463064/69106081-46fd2480-0aa8-11ea-9e3b-05280a56bb61.png)

Below is the exported csv file in IE11:
![data list ie](https://user-images.githubusercontent.com/19463064/69106100-53817d00-0aa8-11ea-9733-4810bce2187f.png)

**Comment by hhurz** [comment]
Fixed in release v1.10.11

**Comment by yanhuRicoh** [comment]
Thank you.
