### ISSUE TITLE
data-tableexport-cellformat not working

### ISSUE THREAD

**Issue by wonderiuy** [hhurz/tableExport.jquery.plugin#284]
Hello hhurz,
just to inform that with new .11 version the data-tableexport-cellformat="" has stopped working
THank you again for your incredible work

**Comment by hhurz** [comment]
Hi, thanks for your response. I suppose you tried to export to xlsx format, right? For xlsx the data-tableexport-cellformat attribute isn't implemented consequently yet. It worked before, because there was barely support for different data types in xlsx format.

**Comment by wonderiuy** [comment]
Yes hhurz, exporting in xlsx. Thank you again for all your efforts, i reverted to .09

**Comment by hhurz** [comment]
FYI: This issue should be fixed in release version v1.10.12. Thanks @wonderiuy for reporting this

**Comment by wonderiuy** [comment]
I saw it today, will try it asap. Thank you for your great work again :)

**Comment by wonderiuy** [comment]
.12 It's working very well. Thank you again
