### ISSUE TITLE
Export only values from cell with multi-valued HTML content

### ISSUE THREAD

**Issue by twhetzel** [hhurz/tableExport.jquery.plugin#285]
Is there a setting(s) to export the value of a cell with content like: `<a href="/gwas/genes/ESR1">ESR1</a>, <a href="/gwas/genes/CCDC170">CCDC170</a>` as `ESR1, CCDC170` in the export?

I've tried setting `htmlHyperlink` to 'href', but that exports the link and only the first value.

**Comment by hhurz** [comment]
Please use release v1.10.13. Before that, the plugin wasn't able to export cells containing multiple hyperlinks out of the box. For the option ```htmlHyperlink``` the default setting ```content``` should be used.

**Comment by twhetzel** [comment]
@hhurz do you have a link for that version? Currently v1.10.12 is at: https://cdn.rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js

**Comment by hhurz** [comment]
@twhetzel 
https://github.com/hhurz/tableExport.jquery.plugin/blob/master/tableExport.js
or extract it from the release archive:
https://github.com/hhurz/tableExport.jquery.plugin/archive/v1.10.13.zip
