### ISSUE TITLE
Npm install not working

### ISSUE THREAD

**Issue by emehmet** [hhurz/tableExport.jquery.plugin#286]
Hi!

I try to download this plugin via npm but I get this error.
undefined ls-remote -h -t ssh://git@github.com/chick307/adler32cs.js.git

My system is windows 10
Npm versions
{ npm: '6.11.2',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.34.0',
  node: '10.16.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.28.0',
  v8: '6.8.275.32-node.52',
  zlib: '1.2.11' }

npm i --save tableexport.jquery.plugin

Thank you.

**Comment by hhurz** [comment]
Sorry, but this issue is out of scope of the plugin. A short test of your npm command did work for me...

**Comment by emehmet** [comment]
Hi, I got this error because my computer doesn't have the git. Maybe you can add it as an explanation. Just in case you go.
