### ISSUE TITLE
How to export hidden table?

### ISSUE THREAD

**Issue by danielsharvey** [hhurz/tableExport.jquery.plugin#29]
Hi,

How can I export a table that is hidden?

For example, I have a display format that is different to the content I wish to export. To do this I can re-format the data in a hidden table. However, hidden tables content is not currently exported.

Is this possible? Perhaps an option?

Thanks,
Daniel

**Comment by hhurz** [comment]
Thanks for your suggestion. See last commit: Now you can use the already known data attribute `tableexport-display="always"` also for `<table>` and `<tr>` tags. 

Example: `<table id="myTable" style="display:none" data-tableexport-display="always">...` This lets you export the hidden table

**Comment by danielsharvey** [comment]
Ah... I see. I saw the data-tableexport-display attribute but did not know you can use for rows and tables.

Thanks, will test this.

Update: Misread your comment, I see that you added the feature. Thank you! It works perfectly.

**Comment by danielsharvey** [comment]
Looks look! Thank you.
