### ISSUE TITLE
Export csv or xlsx file performance is so slowly via tableExport jquery plugin

### ISSUE THREAD

**Issue by iamawiseboy** [hhurz/tableExport.jquery.plugin#291]
Export csv or xlsx file performance is so slowly via tableExport jquery plugin when the table have more than 10000 record(s), How to fix?

**Comment by hhurz** [comment]
There already exist several issues dealing with export of large tables. Please have a look to them: #250, #195, #132, #127, #70.  Perhaps those issues help you in solving yours. Finally I never figured out what caused the reported problems. There are some hints:

-  The plugins export speed slows down dramatically if the table cells (all of them ?) contain style and class attributes
-  Not including Filesaver.js prevents from downloading large export results
-  Using bootstrap table with an outdated version of the export plugin
-  The export become slow when using bootstrapTable merge columns
-  Hidden elements (tr, th, td) can be one reason why the export process slows down
