### ISSUE TITLE
How can i add text near drop down menu??

### ISSUE THREAD

**Issue by 488442** [hhurz/tableExport.jquery.plugin#292]
How can i add text near the dropdown menu near searchbar?
Im refer to official example : https://examples.bootstrap-table.com/#extensions/export.html

**Comment by hhurz** [comment]
That's a specific question related to bootstrap and/or bootstrap table. Please ask your question there.

**Comment by 488442** [comment]
How can i add text near the dropdown menu near searchbar?
Im refer to official example : https://examples.bootstrap-table.com/#extensions/export.html
