### ISSUE TITLE
Unable to install this plugin 

### ISSUE THREAD

**Issue by digesh2089** [hhurz/tableExport.jquery.plugin#293]
When i try to install, it give error like below

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/chick307/adler32cs.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by hhurz** [comment]
Although this issue is out of scope of this plugin, a similar question was asked before: #286 Have a look on how that guy solved his problem. Perhaps it helps.
