### ISSUE TITLE
Wrong CSV output for negative numbers

### ISSUE THREAD

**Issue by kleinph** [hhurz/tableExport.jquery.plugin#296]
Negative numbers like `-0.02` will be outputted as `'-0.02` (with a leading `'`) in CSV exports. This leads to errors when importing in Excel. Output format options seems to have no influence on this issue.

**Comment by hhurz** [comment]
From readme.md: There is an option preventInjection (default is enabled) that prevents formula injection when exporting in CSV or Excel format. To achieve that a single quote will be prepended to cell strings that start with =,+,- or @
Thus set option ```preventInjection: false``` This will ommit the output of the single quote.

**Comment by kleinph** [comment]
Thanks, that fixed the issue.
