### ISSUE TITLE
tableexport doesn't work with requirejs and jspdf

### ISSUE THREAD

**Issue by pcoemar** [hhurz/tableExport.jquery.plugin#298]
Hi,
all required js are loaded but I have this issue:
![Captura](https://user-images.githubusercontent.com/4284169/81048179-1a08c680-8ebc-11ea-80e1-48efdd7b06c7.JPG)
You support would be apreciated

**Comment by hhurz** [comment]
Hi, I guess you missed loading ```jspdf.min.js``` or loading of the file failed. Thats the only reason of the ReferenceError "jsPDF is not defined" I know.

**Comment by pcoemar** [comment]
Hi, yes it's loaded, have a look.
![Captura](https://user-images.githubusercontent.com/4284169/81084425-1f830280-8ef6-11ea-8a10-b420bf5c5898.JPG)
Kind regards,

**Comment by pcoemar** [comment]
Hi, yes sure is loaded, have a look.
![Captura](https://user-images.githubusercontent.com/4284169/81084629-6a9d1580-8ef6-11ea-90f5-ee0cdf41afed.JPG)
Kind regards,

**Comment by hhurz** [comment]
A simple web search for "RequireJS jsPDF" shows a couple of issues regarding this combination. Among others the issues https://github.com/MrRio/jsPDF/issues/869 and https://github.com/MrRio/jsPDF/issues/1317 lead me to supose that jsPDF doesn't work if it is loaded using requireJS. But this is out of scope of the tableExport plugin...

**Comment by pcoemar** [comment]
I don't know if is in the scope or not, but the excepcion happen in tableExport.js.

**Comment by hhurz** [comment]
Ofcourse the exception happens there, because the plugin uses jsPDF. I'm not able to solve incompatibilities between RequireJs and jsPDF. There are two solutions
1) Don't use the PDF export fomat of the plugin (or the plugin at all) or
2) Don't use RequireJS

**Comment by pcoemar** [comment]
Ok, thanks for your support.
