### ISSUE TITLE
get data from ajax request

### ISSUE THREAD

**Issue by wonderiuy** [hhurz/tableExport.jquery.plugin#299]
Hello hhurz,
let's start with aq big thank you for you super work here.
Isuppose this is a feature request because I can't manage to let tableExport grab the data from ajax call.
IE: I have the table as respose of a
$.get('excel.aspx', function(data) { ...
the "data" contains the table
How can i use tableExport on that "data" without putting it in the DOM?
Thank you in advance

**Comment by hhurz** [comment]
Hi, you are right: The plugin requires the table as a DOM element. Most of the parsing process depends on this. Actually I see no way to implement your request. Thanks.

**Comment by wonderiuy** [comment]
Thank you for the fast reply. Will proceed as suggested
