### ISSUE TITLE
Table export does NOT work with IE11

### ISSUE THREAD

**Issue by andyyi** [hhurz/tableExport.jquery.plugin#30]
The same project works well under Chrome, while I totally can NOT make it work under IE11. Looks like the base64 does not support under IE11. Sorry that I'm still new to Web Development. Any ideas for the solution?

This issue is really similar with #15.

**Comment by batistellabr** [comment]
Same issue.

**Comment by hhurz** [comment]
Sorry for the late response. Did you have a look at my [test page](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/index.html)? It works with IE11. Are you including FileSaver.min.js in your project?

**Comment by andyyi** [comment]
You are right. I missed this JS plug-in. Added it in my project and works well, thanks.
