### ISSUE TITLE
Cell data is modified in release 1.10.18

### ISSUE THREAD

**Issue by DahlGadeM-ELS** [hhurz/tableExport.jquery.plugin#300]
Hi and thanks for at very nice plugin :smile: 

I have a table with cells containing elements and fontawesome icons.
When i use `onCellHtmlData` to convert my cell data to text it works just fine in 1.10.17, but in the latest release the content of the cell is modified in the DOM (by calling `$cell.html(htmlData)`) and thus changes the content of my table :cry:

Is this intentional or am I doing it wrong?

Best regards
Mikkel

**Comment by hhurz** [comment]
Hi, thanks for reporting this issue, It should be fixed in release v1.10.19

**Comment by DahlGadeM-ELS** [comment]
Awesome! It works :muscle: 
Thank you very much :tada: :grinning:
