### ISSUE TITLE
export pdf doesn't support chinese?

### ISSUE THREAD

**Issue by kenlmm** [hhurz/tableExport.jquery.plugin#303]
export pdf is error code ,doesn't support chinese?

**Comment by hhurz** [comment]
The tableExport plugin uses [jsPDF](https://github.com/MrRio/jsPDF) as PDF producer. It is a known issue of that plugin, that it has no real unicode support. Only a few unicode characters (as german umlauts) are supported. Please see https://github.com/MrRio/jsPDF/issues/13, https://github.com/MrRio/jsPDF/issues/12 and https://github.com/MrRio/jsPDF/issues/115 for more information about that problem. 

You can try to replace jsPDF by pdfmake. There is a [working example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/chinesePdfmake.html) that should give you an idea how to do that.
