### ISSUE TITLE
NaN when date is empty

### ISSUE THREAD

**Issue by wonderiuy** [hhurz/tableExport.jquery.plugin#304]
Good mornign hhurz,
thank you always for your splendid work here.
I'm using the option data-tableexport-xlsxformatid="14" on some cells to force the date but when the date is empty the exported xlsx shows "NaN" (not a number) in the field value.
IE: 

> `<td data-tableexport-xlsxformatid="14"></td>`

 leads to "NaN" in the xlsx
How can I solve this?
Thank you again
Best regards

**Comment by hhurz** [comment]
@wonderiuy: Hi, thanks for reporting this issue and for the precise description (as always). It is already fixed and will be released soon.

**Comment by wonderiuy** [comment]
Fantastic work, again. Thank you so much.
Where can I send a beer canister?
