### ISSUE TITLE
Negative Number

### ISSUE THREAD

**Issue by ntooos** [hhurz/tableExport.jquery.plugin#305]
Negative data are printed as follows.

**'-13578.12**
![image1](https://user-images.githubusercontent.com/47093832/85297853-444f2b80-b4de-11ea-8249-1d29a68329bc.png)
(_test/msoFormats.html_ Execution Result)

I want to download without quotation marks.
I tried various formats.
(data-tableexport-msonumberformat)
But it didn't work.

How can I express negative numbers in numbers without quotation marks?

**Comment by hhurz** [comment]
See issue #296
