### ISSUE TITLE
How to export multiple tables to one pdf file with pdfmake and make them separate

### ISSUE THREAD

**Issue by OmegaZhou** [hhurz/tableExport.jquery.plugin#306]
I use the code like these

`$("table1,table2,table3").tableExport({
                type: "pdf",
                pdfmake: {
                    enabled: true,
                    docDefinition: {
                        pageOrientation: 'landscape'
                    }
                },
            });`
And I find that the three tables are combined to one table and the `thead` is gotten by combining all `theads` of each table 
 How can I do to make all tables separate in one pdf

**Comment by hhurz** [comment]
The export of multiple tables using pdfmake ist not supported within current version. But I started to work on that and I think it will be released soon.
