### ISSUE TITLE
Choose export type of each column (Excel 2007)

### ISSUE THREAD

**Issue by 488442** [hhurz/tableExport.jquery.plugin#307]
it's possible? I have differenti columns with anchor that i want transform to string

**Comment by hhurz** [comment]
This should be possible. There is an option `htmlHyperlink` which allows you to export either the content (set `htmlHyperlink='content'`) or the href link (set `htmlHyperlink='href'`) of <a\> tags, unless another option `onCellHtmlHyperlink` is not defined. 
In this case, for each table cell containing an href link, the callback function specified by `onCellHtmlHyperlink=function($cell, row, col, href, cellText)` is called. Depending on what you return as a result of the function, you can decide individually for each hyperlink what you want to export.
