### ISSUE TITLE
How to capture  the click event?

### ISSUE THREAD

**Issue by BInodes-official** [hhurz/tableExport.jquery.plugin#308]
I have a big table with 7000+ rows,  I need to capture the click event for telling client that the downloading need time,how to?Thanks

**Comment by hhurz** [comment]
I added an [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/deferredExample.html) for showing a progress indicator using jQuery's deferred object. This should give you a hint how to solve your task. There are propably other ways to solve this, but this solution works for me.
