### ISSUE TITLE
error which installing tableExport.jquery.plugin using bower

### ISSUE THREAD

**Issue by Shrutiag22** [hhurz/tableExport.jquery.plugin#309]
sudo bower --allow-root install tableExport.jquery.plugin
bower select2#^4.0.0            cached https://github.com/ivaynberg/select2.git#4.0.13
bower select2#^4.0.0          validate 4.0.13 against https://github.com/ivaynberg/select2.git#^4.0.0
bower tableExport.jquery.plugin#*           cached https://github.com/hhurz/tableExport.jquery.plugin.git#1.10.20
bower tableExport.jquery.plugin#*         validate 1.10.20 against https://github.com/hhurz/tableExport.jquery.plugin.git#*
bower file-saver#>=1.2.0                    cached https://github.com/eligrey/FileSaver.js.git#2.0.4
bower file-saver#>=1.2.0                  validate 2.0.4 against https://github.com/eligrey/FileSaver.js.git#>=1.2.0
bower jspdf#>=1.3.4                         cached https://github.com/MrRio/jsPDF.git#2.0.0
bower jspdf#>=1.3.4                       validate 2.0.0 against https://github.com/MrRio/jsPDF.git#>=1.3.4
bower jspdf-autotable#2.0.14 || 2.0.17      cached https://github.com/someatoms/jsPDF-AutoTable.git#2.0.17
bower jspdf-autotable#2.0.14 || 2.0.17    validate 2.0.17 against https://github.com/someatoms/jsPDF-AutoTable.git#2.0.14 || 2.0.17
bower es6-promise#>=4.2.4                   cached https://github.com/components/es6-promise.git#4.2.4
bower es6-promise#>=4.2.4                 validate 4.2.4 against https://github.com/components/es6-promise.git#>=4.2.4
bower html2canvas#*                         cached https://github.com/niklasvh/html2canvas.git#0.4.1
bower html2canvas#*                       validate 0.4.1 against https://github.com/niklasvh/html2canvas.git#*
bower jspdf#~1.0.178                        cached https://github.com/MrRio/jsPDF.git#1.0.272
bower jspdf#~1.0.178                      validate 1.0.272 against https://github.com/MrRio/jsPDF.git#~1.0.178
bower atob#^2.1.2                           cached https://github.com/node-browser-compat/atob.git#2.1.2
bower atob#^2.1.2                         validate 2.1.2 against https://github.com/node-browser-compat/atob.git#^2.1.2
bower btoa#^1.2.1                        ENOTFOUND Package btoa not found

**Comment by hhurz** [comment]
tableExport.jquery.plugin does not depend directly on btoa. But it depends on jspdf which has a dependency entry for btoa.

In my opinion btoa is no longer registered in the Bower registry and therefore cannot be found by name by the Bower client.

I am not able to change jspdf's bower.json. So either open an issue there or, if you do not need pdf output, you can remove the jspdf and jspdf-autotable dependencies from the bower.json of the tableExport.jquery.plugin.

**Comment by Shrutiag22** [comment]
Thank you for looking into it.
I will check it further.
