### ISSUE TITLE
How do I put the date in the bootstrap-table export file name? 

### ISSUE THREAD

**Issue by Yangchanhyo** [hhurz/tableExport.jquery.plugin#311]
$('#TableID').bootstrapTable({ exportOptions: { fileName: "CutomtableName" }});

-> ex: **CutomatableNmae.excel**

Desired output method : **CutomatableNmae_2020_10_03.excel**

I would like to know how to add date data to the file name in exportOptions.

how to put the date data?

**Comment by hhurz** [comment]
Although I'm not a solution provider, a quick google search led me to this solution: https://stackoverflow.com/questions/23593052/format-javascript-date-as-yyyy-mm-dd
So you could write something like that (untested): 

``` javascript
function formatDate(date, separator) {
    var d = new Date(date),
        month = '' + (d.getMonth() + 1),
        day = '' + d.getDate(),
        year = d.getFullYear();

    if (month.length < 2) month = '0' + month;
    if (day.length < 2) day = '0' + day;

    return [year, month, day].join(separator);
}
$('#TableID').bootstrapTable({ exportOptions: { fileName: 'CutomatableNmae_' + formatDate('2020-10-03', '_') + '.excel'  }});
```

**Comment by Yangchanhyo** [comment]
Thank you. I solved it!
