### ISSUE TITLE
表头最后一列占两行,设置最后一列导出隐藏,导出后只有表头列隐藏了

### ISSUE THREAD

**Issue by BingHua017** [hhurz/tableExport.jquery.plugin#313]
![image](https://user-images.githubusercontent.com/48582922/97523760-09a25600-19de-11eb-9d0e-f70f0da7bdfc.png)
![image](https://user-images.githubusercontent.com/48582922/97523801-19ba3580-19de-11eb-8529-742fa6370f29.png)
![image](https://user-images.githubusercontent.com/48582922/97523820-1fb01680-19de-11eb-8788-03d7e2f5f271.png)
操作列 data-field="more"

**Comment by hhurz** [comment]
This issue was fixed in version 1.10.21
