### ISSUE TITLE
当表格第一列为选择框，使用导出功能后当前网页表格的选择框列会消失

### ISSUE THREAD

**Issue by BingHua017** [hhurz/tableExport.jquery.plugin#316]
![image](https://user-images.githubusercontent.com/48582922/99869996-7dfd9d00-2c0a-11eb-976b-0daf046cbc12.png)
![image](https://user-images.githubusercontent.com/48582922/99870000-8655d800-2c0a-11eb-86d9-4fc5a835c07a.png)
![image](https://user-images.githubusercontent.com/48582922/99870155-d41f1000-2c0b-11eb-8bdb-5b426d6197a0.png)

**Comment by hhurz** [comment]
This issue cannot be reproduced.
