### ISSUE TITLE
How do I keep the merged cell when downloading All?

### ISSUE THREAD

**Issue by Yangchanhyo** [hhurz/tableExport.jquery.plugin#318]
I am writing as an extension plug-in for bootstrap.

Options in the table : 
data-export-types="['excel']"
data-export-data-type="all"

Merge is being used in the following ways.
$table.on('load-success.bs.table column-switch.bs.table page-change.bs.table', function () {
  $(table).bootstrapTable('mergeCells',{index:index, field:fieldName, colspan: colspan, rowspan: count});
})

When options are all(data-export-data-type="all"),
it won't merge. All merges are cancelled and printed as Excel.
But, data-export-data-type="basic"
Outputs to Excel in merged state.

For all downloads, I want to download them in a merged state.
I would like to ask if there is an option to resolve this issue.?

![keep](https://user-images.githubusercontent.com/19181743/100528042-9af22b80-321b-11eb-9b04-79bcf6afeed1.png)

**Comment by hhurz** [comment]
That seems to be an issue related to bootstrap-table. Please ask your question on their page again. 

I think that when you use the option ```data-export-data-type="all"``` (which means server side pagination), the table data will be fetched from server side (again) before the export function of the tableExport plugin is called. This seems to destroy the rowspan and colspan formatting that you applied with "mergeCells" before.

@wenzhixin Please could you confirm this?

**Comment by wenzhixin** [comment]
@hhurz yes, you can close this issue. 
ref: https://github.com/wenzhixin/bootstrap-table/issues/5463
