### ISSUE TITLE
Table with Cell including <br>

### ISSUE THREAD

**Issue by starcraft04** [hhurz/tableExport.jquery.plugin#319]
When I try to export a cell that has some <br> (it comes from a textarea field where I replaced the new line by <br> to be printed correctly on screen, the problem is that it is showing in one line in excel and I have to change the format option in excel of this cell to wrap text and then it is shown on multilines.

Is it possible to specify before the export that a td will need to be exported with the wrap text format option in excel?

**Comment by hhurz** [comment]
You have not specified which Excel format you are exporting to.  For ```FileFormat: 'xlshtml'``` there was already a related issue (see #121), which has been solved. For xlsx fomat there is unfortunately no solution yet. Perhaps a workaroud could be #239
