### ISSUE TITLE
Simple print a table

### ISSUE THREAD

**Issue by batistellabr** [hhurz/tableExport.jquery.plugin#32]
Is there any feature in the roadmap to allow a user to print a table using the browser printing funcionality?

If not, do you know any way of doing that? I don't want to export my table to a PDF in order to print it. I simple want my user to print the table he is seeing, but not the rest of the application. 

Thanks.

**Comment by hhurz** [comment]
I think this plugin is not supposed to print a table. For what you want to do, i suggest to output the table in a new (popup) window and print its content with a `window.print();` command
