### ISSUE TITLE
1.10.22 Breaks my build

### ISSUE THREAD

**Issue by brianhjelle** [hhurz/tableExport.jquery.plugin#323]
I am using tableExport.jquery.plugin in my Ember app. 1.10.21 works fine, but 1.10.22 breaks my build. The error is below:

```
Build Error (SourceMapConcat)

ENOENT: no such file or directory, open '/var/folders/6c/_mcwhwns517g9n3xrpw2kxyc0000gn/T/broccoli-40549sEcA3strXJTt/out-951-broccoli_debug_debug_5_vendor_js/node_modules/tableexport.jquery.plugin/bower_components/file-saver/FileSaver.min.js'


Stack Trace and Error Report: /var/folders/6c/_mcwhwns517g9n3xrpw2kxyc0000gn/T/error.dump.fe3f8f020ec9bae030774fa7b05e222a.log
```

Any ideas on what changed that could have caused this? Perhaps something related to file-save?

**Comment by hhurz** [comment]
No changes were made between version 1.10.21 and version 1.10.22 that could explain this issue.

**Comment by brianhjelle** [comment]
I believe this to be related to adding bower_components to gitignore since I was importing filesaver and html2canvas like shown in the lines below.
```
app.import('node_modules/tableexport.jquery.plugin/bower_components/file-saver/FileSaver.min.js');
app.import('node_modules/tableexport.jquery.plugin/bower_components/html2canvas/build/html2canvas.min.js');
```

I was able to resolve this issue by fixing my import to be like the following:
```
app.import('node_modules/file-saver/dist/FileSaver.min.js');
app.import('node_modules/html2canvas/dist/html2canvas.min.js');
```
