### ISSUE TITLE
npm install of latest version (1.10.22) is missing the libs folder

### ISSUE THREAD

**Issue by jbieneck** [hhurz/tableExport.jquery.plugin#326]
there is everything available in the zip file under tags in github but with `npm install tableexport.jquery.plugin@latest --save` a few folders are missing. amongst them the libs directory.

best,
Janet

**Comment by hhurz** [comment]
1.10.23 should address this isssue.

**Comment by jonesnc** [comment]
@hhurz I'm still getting this error when I try to install version `1.10.23`:

```
Package "libs" refers to a non-existing file
```

**Comment by tonirah** [comment]
@hhurz still getting this error with 1.10.25

**Comment by jbieneck** [comment]
@hhurz I am also getting this error still even with the latest version ```1.10.25```
as already mentioned the zip file of the release tags includes the libs folder. is there an issue with npm publish?

**Comment by hhurz** [comment]
Just published a new release 1.10.26, that hopefully fixes this issue...

**Comment by jbieneck** [comment]
yes, you made it. the libs folder is part of the npm package now. thanks a lot.
