### ISSUE TITLE
long number will be changed when export to xls/csv

### ISSUE THREAD

**Issue by Phyday** [hhurz/tableExport.jquery.plugin#327]
long number will be changed when export to xls/csv,how can I export it correct?
![image](https://user-images.githubusercontent.com/38483257/116513610-713d4d80-a8fc-11eb-92ca-3c1b343fad8e.png)
![image](https://user-images.githubusercontent.com/38483257/116513638-7bf7e280-a8fc-11eb-86a4-b975081a2a21.png)

**Comment by hhurz** [comment]
**Example table**:

```html
    <table>
      <thead>
      <tr>
        <th>Long Number</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>370911202104140038</td>
      </tr>
      <tr>
        <td>370911202104140025</td>
      </tr>
      <tr>
        <td>370911202104130330</td>
      </tr>
      </tbody>
    </table>
```

**CSV**: You have to cheat Excel. The trick is to prepend a non printable character (x1F = unit separator) to the number that you want to keep as long number. You can do that by implementing a callback function for the `onCellData` option
```javascript
$table.tableExport({
    type: "csv",
    csvSeparator: ';', 
    onCellData: DoOnCellData
});
```
```javascript
function DoOnCellData(cell, row, col, data){
    var result = data;
    if (result != "" && row > 0 && col == 0) {
        result = "\x1F" + data;
    }
    return result;
}
```

**XLS**: There are two solutions

**1st solution**: add a mso format specifier to the regarding html table cells, like
```html
      <tr>
        <td data-tableexport-msonumberformat="0">370911202104130330</td>
      </tr>
```
or **2nd solution**: Implement a callback function for the `mso.onMsoNumberFormat` option:
```javascript
$table.tableExport({
    type: "excel",
    mso: {onMsoNumberFormat: DoOnMsoNumberFormat}
});
```
```javascript
function DoOnMsoNumberFormat(cell, row, col){
    var result = "";
    if (row > 0 && col === 0) {
        result = "0";
    }
    return result;
}
```
