### ISSUE TITLE
Unable to to perform npm install

### ISSUE THREAD

**Issue by sundeepdharma** [hhurz/tableExport.jquery.plugin#328]
Unable to perform npm install as I get bellow error, I checked the latest commit has that file still unable to install
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\tableexport.jquery.plugin\libs" as it does not contain a package.json file.

**Comment by hhurz** [comment]
I reverted version 1.10.23 and published 1.10.24 so this error shouldn't occur any more.

**Comment by sundeepdharma** [comment]
Thanks now it works in 1.10.24
