### ISSUE TITLE
Export all tables to 1 doc and seperate them on a pdf (Example)

### ISSUE THREAD

**Issue by BGB2k11** [hhurz/tableExport.jquery.plugin#329]
Hi,

I saw this was fixed. But could you give me an example ?please

**Comment by hhurz** [comment]
Unfortunately, I do not understand your request and do not know to which fixed issue you are referring to

**Comment by BGB2k11** [comment]
Hi,

I mean this fix. Sorry

https://github.com/hhurz/tableExport.jquery.plugin/issues/306

I have multiple bootstrap tables. But i can not seem to figure out how to do this.

Also. I would want to export a title towards my pdf using pdfmake.
I am totally new to this plugin.

**Comment by hhurz** [comment]
Example file: https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/pdfmake.html
The file contains 2 tables that can be exported either separately or together.

I think that the page content to be exported cannot be modified from the outside currently.

BTW: You need to update to the latest version of the plugin.
