### ISSUE TITLE
Export multiple tables

### ISSUE THREAD

**Issue by iwalkalone69** [hhurz/tableExport.jquery.plugin#33]
Could be possible to export multiple tables?

For example, if I have 10 tables and i do $('table').tableExport({}); only the first one is exported.

**Comment by hhurz** [comment]
Please have a look at my [test page](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/index.html). There is an example that exports multiple tables: **PDF (AutoTable - multiple tables)**

**Comment by hhurz** [comment]
Since v1.4.0 this works wor xls export too
