### ISSUE TITLE
Listed Dependencies outdated causing crash in Docker

### ISSUE THREAD

**Issue by andrewccbc** [hhurz/tableExport.jquery.plugin#333]
Thank you for your work on this plugin. We ran into a problem with file-saver, jspdf, and jspdf-AutoTable. the versions of file-saver prior to 2.0.1 required git ssh connection which causes docker issues. There are new versions of all 3 of those dependencies which resulted in fixes for this problem. File-Saver 2.0.1+, JSPDF 2.0.0+, and jspdf-AutoTable 3.5.9+ fix this. I tested updating the package JSON to reflect the updated dependencies and it worked great without any npm issues. Just figured you might be interested in updating the dependencies in your version.

**Comment by r3dqu33n** [comment]
I had a similar issue due to ssh connection being blocked, and (as a workarond) this command solved my problem:

`git config --global url."https://github.com".insteadOf ssh://git@github.com`

**Comment by hhurz** [comment]
Dependencies for jsPDF, filesaver.js and others have been updated in release 1.20.0

**Comment by andrewccbc** [comment]
You are awesome!
