### ISSUE TITLE
XLSX export does not work

### ISSUE THREAD

**Issue by arsrobota** [hhurz/tableExport.jquery.plugin#339]
Hello,
If I import `tableexport.jquery.plugin/libs/js-xlsx/xlsx.core.min` then XLSX export fails with message `Uncaught ReferenceError: XLSX is not defined`. If I try importing `xlsx/dist/xlsx.full.min` instead, it fails again with message `Uncaught ReferenceError: XLSX.utils is not defined`. On the other hand Excel export works well.
Do I miss something ?
I use Bootstrap-Table 1.19.1 with tableexport.jquery.plugin 1.20.1 under Webpack 5.59.1.

Many thanks !

**Comment by hhurz** [comment]
Unfortunately, I can't really answer this question as I'm not a bootstrap expert. The "ReferenceError: XLSX is not defined" message indicates that the xlsx.core.min file could not be loaded. Is the directory path correct? Does the file exist? There is a [xlsx test file](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/xlsx.html) (without bootstrap) that could help you to track down your issue.

**Comment by arsrobota** [comment]
Hi hhurz, thanks for your reply.
The path to xlsx.core.min.js correct. I can export an XLSX file with your test page.
Perhaps the problem is on webpack side...

**Comment by arsrobota** [comment]
Inspecting webpack console, I can see when I import `tableexport.jquery.plugin/libs/js-xlsx/xlsx.core.min` I get an `Error: Can't resolve 'fs' in 'D:\symfony\gar\node_modules\tableexport.jquery.plugin\libs\js-xlsx'" -t "Webpack Encore"`

**Comment by hhurz** [comment]
A little bit googling leeds to this webpack [isssue](https://github.com/webpack-contrib/css-loader/issues/447). Perhaps it helps.

**Comment by arsrobota** [comment]
Thanks for the link. I also found [this Webpack migration guide](https://webpack.js.org/migrate/5/) as an update. Unfortunately it looks like Webpack Encore does not support resolve.fallback.
