### ISSUE TITLE
Version 1.20 doesn't work with IE, IE11 doesn't support "for(const " and "class ".

### ISSUE THREAD

**Issue by schzh** [hhurz/tableExport.jquery.plugin#340]
In IE 11\IE WIN 10，Version 1.20 doesn't work，F12 Debug shows SCRIPT1053: Const must be initialized
error in this sentence : "for(const "
I tried to replace all "for(const " with "for(var ", then the next error is before this sentence:
class jsPdfTableClass{
I delete all class jsPdf, now it's OK.

So the problem is clear: IE11 doesn't support "for(const " and "class ".

**Comment by schzh** [comment]
> 

and the old version 1.10 can be use with no problem

**Comment by schzh** [comment]
> Version 1.20 doesn't work with IE，F12 Debug shows SCRIPT1053: Const must be initialized in this sentence : for(const cssStyle in defaults.mso.styles) In IE 11\IE WIN 10

and the old version 1.10 can be use with no problem

**Comment by schzh** [comment]
another problem is speed, it takes a very long time to export a table of 1000 lines

**Comment by hhurz** [comment]
Release 1.21 supports IE11 again.

About speed: I confirm the speed problem. The speed of the export is determined by the source table, the browser used and the format to export to. In the near future I don't see myself being able to speed up the export significantly.

**Comment by schzh** [comment]
> Release 1.21 supports IE11 again.
> 
> About speed: I confirm the speed problem. The speed of the export is determined by the source table, the browser used and the format to export to. In the near future I don't see myself being able to speed up the export significantly.

Thanks.
