### ISSUE TITLE
exportDataType: 'all' not working

### ISSUE THREAD

**Issue by max-henri** [hhurz/tableExport.jquery.plugin#346]
Hello,
I am trying to build a button that exports all the rows (including the ones hidden because of pagination).
I found the 'exportDataType' parameter in Bootstrap Table that works with the standard button but I cannot make it work with a custom button.
Is this a limitation? Or which parameter to use?
Thanks in advance

Example:
https://examples.bootstrap-table.com/index.html#extensions/export.html

**Comment by hhurz** [comment]
Hi, that seems to be an issue related to bootstrap-table. Please ask your question on their page again.
