### ISSUE TITLE
Unable to exclude hyperlink from XLSX export

### ISSUE THREAD

**Issue by CryptocurrencyZ** [hhurz/tableExport.jquery.plugin#347]
Hi,

I have tried using htmlHyperlink: 'content', but still the hyperlinks pull through to the export?

Thanks

**Comment by hhurz** [comment]
Hi, working for me. Have you seen this [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/xlsxHyperlink.html)?

**Comment by CryptocurrencyZ** [comment]
Thank you for the example it helped me get to the solution, I also had to update the library too.
