### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [hhurz/tableExport.jquery.plugin#349]
Hey there!

I belong to an open source security research community, and a member (@uberbrady) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by hhurz** [comment]
Added default security.md

Please use the [GitHub Issue Tracker](https://github.com/hhurz/tableExport.jquery.plugin/issues) to report vulnerabilities.

**Comment by JamieSlome** [comment]
@hhurz - appreciate your response and creation of `SECURITY.md` 👍 

The report we received can be found here:
https://huntr.dev/bounties/49a14371-6058-47dd-9801-ec38a7459fc5/

It is currently private and only accessible to you (@hhurz). Let me know if you have any questions and will be happy to support you. BTW, love your GitHub profile image 😄

**Comment by hhurz** [comment]
FYI: The issue has been resolved with release 1.25.0 of the plugin
