### ISSUE TITLE
export excel style

### ISSUE THREAD

**Issue by nicocarolo** [hhurz/tableExport.jquery.plugin#35]
Hi, please i do not found an example of excelstyles, how i use it? i want to change the font style or border styles when i export to excel.
Thanks for the help!.

**Comment by nicocarolo** [comment]
i found that work with css properties, but if i add one property, this property will aplly for all the cells, how i can distint header from other cells? thanks

**Comment by hhurz** [comment]
The excelstyles option lets you define the css attributes of the original (!) 'html table' that you also want to have to be exported to the resulting excel table. The following example will fetch the background-color style attribute and the color style attribute of each html table cell and add it as style attributes to the excel table cells.

``` javascript
      $('#example').tableExport({type: 'excel', excelstyles: ['background-color', 'color']});
```

After reading your second comment I asume you tried something like this: `excelstyles: ['background-color:red', 'color:white']}` This would indeed set the background color of each cell to red and the text color to white!

**Comment by nicocarolo** [comment]
Hi, thanks! you know how i can distinct the properties for the header of the table of the other cells?

**Comment by hhurz** [comment]
i'm not sure if I understand your question. But please have a look at the plugins [test page](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/index.html). There you will find an example table for the excelstyles option. That table has different style attributes for header and body cells.

**Comment by nicocarolo** [comment]
Sorry i want the header of the table have a kind of border and font in the excel, and the cells with the data another font and border, do you understand me? thanks!

**Comment by hhurz** [comment]
So i suggest you build the html table with the css styles that you like to have for its thead and tbody cells. To export this table I would try to set the excelstyles option to something like this: 

``` javascript
excelstyles: ['background-color', 'color', 'border-bottom-color', 'border-bottom-style', 'border-bottom-width', 'border-top-color', 'border-top-style', 'border-top-width', 'border-left-color', 'border-left-style', 'border-left-width', 'border-right-color', 'border-right-style', 'border-right-width', 'font-family', 'font-size', 'font-weight']
```
