### ISSUE TITLE
Remove decimal values / showing all values decimal

### ISSUE THREAD

**Issue by vinaysavner** [hhurz/tableExport.jquery.plugin#352]
Why every values are exporting in decimal format.
I am exporting the excel sheet.

**Comment by vinaysavner** [comment]
@kleinph @Guite @simogeo @denilsonsa 
Please check my code to export the excel, I have normal values in table but it is showing decimal after exporting those table in excel.

$("#exportExcel").on("click", function () {
        doExport('table', { type: 'excel', mso: {onMsoNumberFormat: '0', fileFormat: 'xlsx', worksheetName: worksheetTablesName, 
            xlsx: {        
                formatId: {  
                  digit: 1 
                },
                format: {
                  digit: 0 
                }
              }          
         } })
    })

**Comment by denilsonsa** [comment]
~~Very rude to tag a bunch of people who haven't touched this project in five years. You wanted attention, but you got the wrong type of attention.~~

Please do not tag random people without a good reason. I haven't used this project in 5 years. I cannot help you with your problem.

You could try these:

* https://stackoverflow.com/help/how-to-ask
* http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by hhurz** [comment]
@vinaysavner You didn't write into which excel format you want to export to. For xls (Excel 2000) you can find a solution at the end of this issue: #156

**Comment by vinaysavner** [comment]
> ~Very rude to tag a bunch of people who haven't touched this project in five years. You wanted attention, but you got the wrong type of attention.~
> 
> Please do not tag random people without a good reason. I haven't used this project in 5 years. I cannot help you with your problem.
> 
> You could try these:
> 
> * https://stackoverflow.com/help/how-to-ask
> * http://www.catb.org/~esr/faqs/smart-questions.html

Thanks for providing me this important contents and sorry for the tag bunch of people, actually that time I need to fixe this issue asap possible.

**Comment by vinaysavner** [comment]
> Hi, I am using xlsx format and you will be glad to know that I have done it. But recently i want to do some styles in the XLSX format, I want to add BG colors in some cell's.
> Can you please suggest me a good this to do this.
> Thanks.

Hi, I am using xlsx format and you will be glad to know that I have done it by changing the numbers value in mso object.

 var defaults = {
      mso: {  
        xslx: {                         
          formatId: {    
          numbers: 1, // Changed this to 1 and decimal values are remove
        }
      },
Thanks.
