### ISSUE TITLE
xlsx export: no decimal for integer columns

### ISSUE THREAD

**Issue by astomas** [hhurz/tableExport.jquery.plugin#356]
After reading [#352](https://github.com/hhurz/tableExport.jquery.plugin/issues/352), I see you can remove decimals by adjusting "numbers" to 1 in tableExport.js , but il will work for all numeric columns (integer or not).

So how to remove, when exporting in xslx, the 2 decimals from integer columns only and keep the decimals for other numeric columns?

**Comment by hhurz** [comment]
There are two solutions

**1st solution**: add a xlsx format specifier to the regarding html table cells depending on their value types, like
```html
      <tr>
        <td data-tableexport-xlsxformatid="1">3709</td>
      </tr>
      <tr>
        <td data-tableexport-xlsxformatid="2">10.25</td>
      </tr>
```
**2nd solution**: Apply a callback function to the `mso.xlsx.formatId.numbers` option:
```javascript
$table.tableExport({
    type: "excel",
    mso: {
        fileFormat: 'xlsx',
        xlsx: {
            formatId: {
                numbers: onXlsxFormatId
            }
        }
    },
});
```
```javascript
function onXlsxFormatId(cell, row, col){
    let formatId = 2;
    if (row > 0 && (col === 0 || col === 3)) {
        formatId = 1;  // Apply formatId 1 to the 1st and 4th column
    }
    return formatId;
}
```

**Comment by astomas** [comment]
1st solution works, thanks. You have to know beforehand which columns are integer only.
