### ISSUE TITLE
Need themes and new Designs with the same options

### ISSUE THREAD

**Issue by passionate2023** [hhurz/tableExport.jquery.plugin#359]
Hi,

Is it possible to add new themes/designs with the same export options 

Thanks

**Comment by hhurz** [comment]
Sorry for the late response, but I don't understand your question. Please provide more inforamtion about which format you are exporting to and what you are trying to do.

**Comment by passionate2023** [comment]
I meant some working HTML files with table exports in example folder with beautiful colours or beautiful background or themes to just add in a website page

Example1_Folder
Example2_Folder
Example3_Folder
Example4_Folder
Example5_Folder

**Comment by hhurz** [comment]
I'm afraid I have to ask my question again: In which format (e.g. pdf, xls, xlsx,..) do you want to export your HTML files? 
The export format determines if and if so which stylings can be exported.

**Comment by passionate2023** [comment]
no...export of table content...There are various designs with sample HTML file with table....example https://datatables.net/

not with any other content --> only with dummy table data with beautiful diff designs of table export options, buttons, colours etc.,

**Comment by hhurz** [comment]
Could it be that you are confusing the projects? TableExport.jquery.plugin has nothing to do with datatables.net. The DataTables project has its own ecport plugin: https://datatables.net/extensions/buttons/examples/initialisation/export.html
