### ISSUE TITLE
pdf turkish character problem

### ISSUE THREAD

**Issue by cetindogu** [hhurz/tableExport.jquery.plugin#36]
pdf export dont render turkish characters correctly.

**Comment by hhurz** [comment]
This plugin uses [jsPDF](https://github.com/MrRio/jsPDF) as PDF producer. It is a known issue of that plugin, that it has no real unicode support. Only a few unicode characters (as german umlauts) are supported. Please see https://github.com/MrRio/jsPDF/issues/12 and https://github.com/MrRio/jsPDF/issues/115 for more information about that issue
