### ISSUE TITLE
Export as xlsx file 

### ISSUE THREAD

**Issue by chiragthakuri** [hhurz/tableExport.jquery.plugin#361]
Hello i am struggling on how to do this. I have added the xlsx.js dependency file.

Currently, only the file is being exported as xls using this code

$('#excel-data').tableExport({type:'excel',escape:'false'});

How can I change this code in order to generate a xlsx file. thank you!

**Comment by hhurz** [comment]
`$('#excel-data').tableExport({type: 'excel', mso: {fileFormat: 'xlsx'}});`

You can find an example file [here](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/xlsx.html). There are also some closed issues related to the xlsx format.
