### ISSUE TITLE
excel font family/size

### ISSUE THREAD

**Issue by takeAction** [hhurz/tableExport.jquery.plugin#362]
Is it possible that set font family/size and set text is wrapped when exporting excel ?

**Comment by hhurz** [comment]
Which excel format do you want to use? I assume that you mean the xlsx format, right? If yes, then the export styling (font size or family) cannot be changed.
As for the line break, I don't know of any format option for the export that can be used to make Excel wrap the cell text.

**Comment by takeAction** [comment]
Yes, xlsx format. Got it, thank you very much!
