### ISSUE TITLE
export types ".png" image and "MS-Powerpoint " not working

### ISSUE THREAD

**Issue by cetindogu** [hhurz/tableExport.jquery.plugin#37]
when i click png or "Ms-Powerpoint" nothing happens

**Comment by maker22** [comment]
I have the same issue for PNG

**Comment by hhurz** [comment]
Regarding PNG you are both right. There seems to be some kind of interaction between html2canvas and the other plugins that are used by tableexport. I fixed this issue by rearranging the include order of the plugin files:

``` javascript
  <script type="text/javascript" src="../libs/FileSaver/FileSaver.min.js"></script>
  <script type="text/javascript" src="../libs/jsPDF/jspdf.min.js"></script>
  <script type="text/javascript" src="../libs/jsPDF-AutoTable/jspdf.plugin.autotable.js"></script>
  <script type="text/javascript" src="../libs/html2canvas/html2canvas.min.js"></script>
  <script type="text/javascript" src="../tableExport.js"></script>
```

**html2canvas.min.js has to be included straight before tableExport.js**. When moving it to an earlier include position it doesn't work any more. I don't know why...

Regarding MS-Powerpoint: In opposite to the original work I do not support this format in my fork of the plugin.

**Comment by cetindogu** [comment]
Thanks for the answer i will try next day.
6 Eki 2015 ÖS 11:06 tarihinde "hhurz" notifications@github.com yazdı:

**Comment by punchi** [comment]
@hhurz I have the same order but the result PNG show just the table separation and empty cells, not data. On PDF, CSV and DOC, all show data, don't you have any problem like that? thanks

**Comment by hhurz** [comment]
@punchi: Nope, just verified PNG export with the last version of the plugin and everything works fine. Please have a look at my test page. The output of the PNG example is equal to the original html table: 

![tableexport](https://cloud.githubusercontent.com/assets/4164372/10495892/78872266-72be-11e5-81f9-44deb70b4daa.png)

**Comment by punchi** [comment]
@hhurz did you change something? downloaded last version and now it works XD anyway, thank you!! 
3 suggestions: 
1) It would be great if you can take negative values, like: `ignoreColumn:[0,-1]` ( like on Datatables )
2) ignoreColumn does not work on PNG images, the test could have an extra column at the end [-1] =) and the test is successful if the column does not appear
3) If you do not go to the test or examples, on the documentation do not appear all the possibles combinations to export to!! ie: though "XLS" was not available, as the "type" it's "excel" not "XLS.

Thanks again for this plugin to all contributors =)

**Comment by hhurz** [comment]
@punchi Thanks for your suggestions. I'll take them into consideration.

UPDATE: Your suggestions 1) and 3) have been added now.
