### ISSUE TITLE
Export strips cell content with number and leading "0"

### ISSUE THREAD

**Issue by simonsolutions** [hhurz/tableExport.jquery.plugin#370]
I have cell contents like that: "00367901234567890323", but exported is "36790123456789032300". That affects csv, txt, excel and pdf.
I have no special code only the activation of the export plugin.

**Comment by simonsolutions** [comment]
When changing the cell content from plain numeric values to a string (e.g. by adding "x" at the end) the export works like expected.

**Comment by hhurz** [comment]
Please have a look at issue #103. There are also other old issues dealing with other export formats like #81, #156, #327 that can give you an idea how to solve yours.
