### ISSUE TITLE
Export to PDF with images, control size of image?

### ISSUE THREAD

**Issue by evbrew** [hhurz/tableExport.jquery.plugin#372]
I took the file \test\cssPdf.html and added some IMG tags to the table cells.
When exporting to PDF the images are very tiny (maybe 15x15 pixels) and regardless of which css or html width and height attributes i set it doesn't change the image size.
Am i missing something?

**Comment by hhurz** [comment]
You could try to use the jspdf > autotable: > styles option `rowHeight`:
```javascript
$('#pdfstyles').tableExport({type:'pdf',
                             jspdf: {orientation: 'p',
                                     margins: {right: 20, left: 20, top: 30, bottom: 30},
                                     autotable: {styles: {rowHeight: 72},
                                                 tableWidth: 'wrap'}}});
```
