### ISSUE TITLE
Add composer.json and add package to packagist

### ISSUE THREAD

**Issue by Endition** [hhurz/tableExport.jquery.plugin#373]
Hey,

can you please create a composer.json and add the package to https://packagist.org/ so that is possible to get the package via composer. The neccassary steps are described on the landing page.

Thank you

**Comment by hhurz** [comment]
Packagist is not designed for managing or deploying jQuery or JavaScript packages. Packagist is a package repository for PHP packages and libraries that are managed using Composer, a PHP dependency manager. It is specifically tailored to the PHP ecosystem and not meant for handling JavaScript dependencies.

**Comment by Termidio** [comment]
I agree. PHP Projects are often mixed with js.

    "jquery",
    "jqueryui",
    "bootstrap",
    "bootstrap-select",
    "bootstrap-table",
    "font-awesome",

for example are available on packalist. I use bootstrap-table und want to add the download function.
https://packagist.org/packages/wenzhixin/bootstrap-table/stats
Seems to me that I am not the only one. 
It is not need, but would be an nice simplification

**Comment by hhurz** [comment]
FYI: Meanwhile I added a composer.json file to the project. It will be deployed within the next release. If required, you can download it from the project site.

**Comment by Termidio** [comment]
Thank you. Nice christmas present
