### ISSUE TITLE
How to add fields at the beginning or end in a table export to Excel.

### ISSUE THREAD

**Issue by RodrigoEscAlm** [hhurz/tableExport.jquery.plugin#375]
Good morning,

I would like to know if there is the possibility, when exporting the table to Excel, of attaching fields to the beginning and/or end of the table, such as the day, a title, that are loaded dynamically according to a variable.

Thanks in advance.

**Comment by hhurz** [comment]
There is no callback functionality to achieve this. But one way could be to work with hidden tables that are positioned before or after the actual table to be exported. With the help of a special data-atribute, the hidden tables can be output during the export. Example: `<table id="myTable" style="display:none" data-tableexport-display="always">...` This lets you export a hidden table

In the same way, you can also add hidden rows or cells to the HTML table to be exported, which are not visible in the browser but are output during the export. For that, just add the the data-tableexport-display to the hidden rows or cells.
