### ISSUE TITLE
pdfmake - table column width to automatically adjust to cell content

### ISSUE THREAD

**Issue by blendxorz** [hhurz/tableExport.jquery.plugin#378]
Hi, I'm currently using pdfmake and I'm having trouble adjusting the column width to fit the cell content.
In the snippet below, I would like to adjust the column width to fit the content in order to minimize whitespaces.
How do I do that?

![image](https://github.com/hhurz/tableExport.jquery.plugin/assets/165122514/791b199d-4ae6-4b75-b012-3954d6c116f9)

**Comment by hhurz** [comment]
Hi, use the new `widths` option from the latest release 1.29.0
```javascript
$('#tableID').tableExport({
  type:'pdf',
  pdfmake:{enabled:true,
           docDefinition:{pageOrientation:'landscape'},
           widths: 'auto'}
});
```

**Comment by blendxorz** [comment]
Thank you!

**Comment by blendxorz** [comment]
Thank you!
