### ISSUE TITLE
Possibility of excluding rows by class name?

### ISSUE THREAD

**Issue by TheBrockEllis** [hhurz/tableExport.jquery.plugin#38]
I have a situation where I may not exactly know the numeric indexes of the rows that I want to exclude from exporting without having to calculate it manually before calling the export on the table. 

Would it be beneficial to have an option to exclude certain rows if given a class name?

``` javascript
$('#tableContent').tableExport({
    type:'csv',
    excludeRowClass: "skipmeplz"
});
```

 I'd be more than happy to open a pull request with this behavior if it would be favorable.

**Comment by hhurz** [comment]
Thanks for your suggestion. I think there is already a similar solution for what you want do: `data-tableexport-display="none"` Use this data attribute for the rows you don't want to export. I added a working example on my [test page](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/index.html):

``` html
    <table id="hiddenrows" class="table-striped">
      <thead>
      <tr>
        <th>C1</th>
        <th>C2</th>
        <th>C3</th>
      </tr>
      </thead>
      <tbody>
      <tr data-tableexport-display="none">
        <td>A</td>
        <td>B</td>
        <td>C</td>
      </tr>
      <tr>
        <td>D</td>
        <td>E</td>
        <td>F</td>
      </tr>
      <tr data-tableexport-display="none">
        <td>G</td>
        <td>H</td>
        <td>I</td>
      </tr>
      </tbody>
    </table>
```

**Comment by TheBrockEllis** [comment]
Marvelous! Sorry for the needless issue. Consider this closed. :+1:
