### ISSUE TITLE
Please add the ability to export "multiple tables" with xls type

### ISSUE THREAD

**Issue by carlos-granadeno** [hhurz/tableExport.jquery.plugin#39]
Hi, excelent work with this plugin.  Do you think is possible add the same ability of multiple tables in PDF but for the type XLS.

I have several tables inside a div, that i want to export in only one worksheet file.  i tried using the div id, but the excel file returns blank.

thanks,

**Comment by hhurz** [comment]
Thanks for your suggestion. I had a look on it, but i have to admit that multiple table supprt for the current XLS format would be a major challenge. I'm thinking about to support "SpreadsheetML" aka "MS Excel 2003 xml" as a further Excel format sooner or later. With this format multiple table support seems much more easier to implement.

**Comment by carlos-granadeno** [comment]
Right now, i use this function javascript to do the job:
function preparexls()
{ window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('#container').html()));
        e.preventDefault();
}

where #container is the id of one div which contain a lot of  html tables , then
when i use it "onclick="preparexls(); return false;" creates me a xls with all the tables in the same worksheet, included thead, tbody, tfoot, some css backgrounds.
It's not a fancy code or customizable.  But is really great, try it.

thanks for answer.!!

**Comment by hhurz** [comment]
Added this feature to release v1.4.0
