### ISSUE TITLE
UTF-8 enconding issue using Excel export (not tested with other format)

### ISSUE THREAD

**Issue by simogeo** [hhurz/tableExport.jquery.plugin#4]
I have the impression that this [jquery.base64.js](https://raw.githubusercontent.com/kayalshri/tableExport.jquery.plugin/master/jquery.base64.js) file is more UTF-8 compatible than the current embedded version (see commit 335bacb61fd0860a1607f48746381567565438ed ). Is that possible? Tested with libreOffice only.

Some complement (@hhurz ) : 

Regarding UTF-8 and  jquery.base64.js, I've seen in the code (around L358) : 

> downloadFile(defaults.fileName+'.'+extension, 'data:application/vnd.ms-'+defaults.type+';base64,' + base64data);

and tried : 

> downloadFile(defaults.fileName+'.'+extension, 'data:application/vnd.ms-'+defaults.type+';charset=utf-8;base64,' + base64data);

But I get the same encoding accent problem

**Comment by hhurz** [comment]
There was no need to replace the existing base64 code. The solution to solve this problem can be found in [Encoding UTF-8 when exporting HTML table to Excel](http://stackoverflow.com/questions/25730008/encoding-utf-8-when-exporting-html-table-to-excel)
and in this question [Importing HTML table into OO Calc as UTF8 without converting to entities](http://stackoverflow.com/questions/14199428/importing-html-table-into-oo-calc-as-utf8-without-converting-to-entities)

**Comment by simogeo** [comment]
Not sure to get you .... but I've seen you made some changes on the library, and specifically on base64. I will update it and make more tests to know if the problem persists.

Thanks
