### ISSUE TITLE
Configuration of PDF page breaks

### ISSUE THREAD

**Issue by vsisko** [hhurz/tableExport.jquery.plugin#43]
Hello. When I try to export table like this:

``` html
<table id="tbl">
    <thead>
        <tr>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
    <tr><td>row 1<td/><tr/> <tr><td>row 2<td/><tr/> <tr><td>row 3<td/><tr/> <tr><td>row 4<td/><tr/> <tr><td>row 5<td/><tr/>
    <tr><td>row 6<td/><tr/> <tr><td>row 7<td/><tr/> <tr><td>row 8<td/><tr/> <tr><td>row 9<td/><tr/> <tr><td>row 10<td/><tr/>
    <tr><td>row 11<td/><tr/> <tr><td>row 12<td/><tr/> <tr><td>row 13<td/><tr/> <tr><td>row 14<td/><tr/> <tr><td>row 15<td/><tr/>
    <tr><td>row 16<td/><tr/> <tr><td>row 17<td/><tr/> <tr><td>row 18<td/><tr/> <tr><td>row 19<td/><tr/> <tr><td>row 20<td/><tr/>
        <tr>
            <td style="margin: 5px">
                Very long long long long long long long long long long long long long
                long long long long long long long long long long long long long long
                long long long long long long long long long long long long long Message
            </td>
        </tr>
        <tr>
            <td>
                Last row
            </td>
        </tr>
    </tbody>
</table>
```

to PDF format with properties:

```
{type:'pdf',
  jspdf: {
    autotable: {
      styles: {overflow: 'linebreak',
        fontSize: 26,
        rowHeight: 36,
        fillColor: 155},
      headerStyles: {rowHeight: 28,
        fontSize: 38}
   }
  }
}
```

I receive next PDF file: 
![html to pdf page break](https://cloud.githubusercontent.com/assets/5163151/10686742/036c2388-7989-11e5-9ee9-bc215e0400c7.png)

Can I configure behaviour of page breaks? I see two additional variant of page breaking:
1) Move all cell to new page,
2) Break cell and show second part of cell on new page.

**Comment by hhurz** [comment]
As you probably know I'm using another plugin ([jsPDF-AutoTable](https://github.com/simonbengtsson/jsPDF-AutoTable)) to export to PDF. There is a known issue [Overflow: 'linebreak' for continuing on new page](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/79) which I think matches your question.

**Comment by hhurz** [comment]
Since jsPDF AutoTable plugin v2.0.13 the problem seem to be solved, Thus I updated tableExport v1.2.0 to newest jsPDF AutoTable version.

**Comment by vsisko** [comment]
Problem have new appearance:

``` html
<table id="tbl">
    <thead>
        <tr>
            <th>Title</th>
        </tr>
    </thead>
    <tbody>
    <tr><td>row 1<td/><tr/> <tr><td>row 2<td/><tr/> <tr><td>row 3<td/><tr/> <tr><td>row 4<td/><tr/> <tr><td>row 5<td/><tr/>
    <tr><td>row 6<td/><tr/> <tr><td>row 7<td/><tr/> <tr><td>row 8<td/><tr/> <tr><td>row 9<td/><tr/> <tr><td>row 10<td/><tr/>
    <tr><td>row 11<td/><tr/> <tr><td>row 12<td/><tr/> <tr><td>row 13<td/><tr/> <tr><td>row 14<td/><tr/> <tr><td>row 15<td/><tr/>
    <tr><td>row 16<td/><tr/> 
        <tr>
            <td style="margin: 5px">
                Very long long long long long long long long long long long long long
                long long long long long long long long long long long long long long
                long long long long long long long long long long long long long Message
            </td>
        </tr>
        <tr>
            <td>
                Last row
            </td>
        </tr>
    </tbody>
</table>
```

On export to PDF:

![pdf page break](https://cloud.githubusercontent.com/assets/5163151/10837565/110c8472-7ee5-11e5-9311-adfc741e85f5.png)

**Comment by hhurz** [comment]
Not to me. Tried the same example (tableExport options from your first post) as you did, but cannot reproduce this behavior. Did you update jsPDF Autotable to v2.0.14?

![issue43](https://cloud.githubusercontent.com/assets/4164372/10841176/55f0e57c-7ee7-11e5-9338-9a1a9b86fa18.png)
Actually I'm not happy with row height calculation and text positioning within all three involved plugins. Digging into this seems to be a major task...

**Comment by vsisko** [comment]
Problem is fixed. Rawgit returns a cached library of old version.
