### ISSUE TITLE
Please add the ability to excluse some selector into cell by class or id

### ISSUE THREAD

**Issue by manukieli** [hhurz/tableExport.jquery.plugin#44]
Hi,

I'ts possible to add the posibility to explude some selector exportation into some cells.
For example, into cells from one or several columns, i've 2 DIV,  one with "data" class and the other with "data no_export" class or with diferent id.
I would like to export the table but exclude the content of div with class "no_export".
It's an example, but wil be a good solution.

**Comment by hhurz** [comment]
Thanks for your suggestion. I added a new option "onCellHtmlData". If defined, onCellHtmlData (cell, row, col, data) will be called for every cell before its (html) content will be parsed. By using this function you can manipulate the cell content before it will be exported.
Example: When exporting this table

``` html
    <table>
      <thead>
      <tr>
        <th>C1</th>
        <th>C2</th>
        <th>C3</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>A</td>
        <td>B</td>
        <td>C</td>
      </tr>
      <tr>
        <td><div>D</div><div class="no_export">you shouldn't see this</div></td>
        <td><b>E</b></td>
        <td><div>F</div></td>
      </tr>
      <tr>
        <td>G</td>
        <td>H</td>
        <td>I</td>
      </tr>
      </tbody>
    </table>
```

by using this tableexport options:

``` javascript
{type: 'txt', 
onCellHtmlData: DoOnCellHtmlData
}

function DoOnCellHtmlData(cell, row, col, data) {
  var result = "";
  if (data != "") {
    html = $.parseHTML( data )
    $.each( html, function() {
      if ( typeof $(this).html() === 'undefined' )
        result += $(this).text();
      else if ( ! $(this).hasClass('no_export') )
        result += $(this).html();
    });
  }
  return result;
}
```

You will get this result

``` text
C1,C2,C3
A,B,C
D,E,F
G,H,I
```

Please also have a look on my [test page](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/index.html) for the working example "TXT (onCellData)"

**Comment by manukieli** [comment]
Thank you very much to develop this posibilities.
I'm using your script with Bootstrap-table and with this new option, when i export i will get this error message of JQuery 2-1-4:
<code>
Cannot read property 'length' of null
</code>

**Comment by hhurz** [comment]
Would be nice to provide some more information about that error. Did you debug it? Which property had a length of null? Does this error depend on specific cell content?

**Comment by manukieli** [comment]
You can see an example here: https://jsfiddle.net/0gsxos85/10/

When you export the file it export the select option  list of the filter. I would like to explude it but they don't work.

**Comment by manukieli** [comment]
Here you can see another example but less the option to exclude. And you will see the result of the export file. You will see all the list option of the select.
https://jsfiddle.net/1xvbcefc/1/

**Comment by hhurz** [comment]
Based on your last example the solution is (https://jsfiddle.net/g9kksddk/1):
- Do not set the tableexport options in tableexport.js as you have done it in your 1st JSFiddle example
- Set the tableexport options using the bootstrapTable interface like this:

``` javascript
var $table = $('#table');
$table.bootstrapTable('refreshOptions', {
    exportOptions: {onCellHtmlData: DoOnCellHtmlData}
});
```
- Depending on the content of the table you want to export you have to adjust the onCellHtmlData function. For your JSFiddle table it has to look like this:

``` javascript
function DoOnCellHtmlData(cell, row, col, data) {
    var result = "";
    if (data != "") {
      var html = $.parseHTML(data);

      $.each( html, function() {
          if ( typeof $(this).html() === 'undefined' )
              result += $(this).text();
          else if ( typeof $(this).attr('class') === 'undefined' || $(this).hasClass('th-inner') === true )
              result += $(this).html();
      });
    }
    return result;
}
```

**Comment by manukieli** [comment]
Ok, thank you very much.
Tehy work like a charme.
But now I've another issue. If into column i've a cell with blank value (value = "") and i would like to export the table, they give me this error message for JQuery file:

<code>
TypeError: Cannot read property 'length' of null
</code>

You can see an example here: http://jsfiddle.net/g9kksddk/14/
Into the first column you can see they have blank cell.

**Comment by hhurz** [comment]
Check if "data" is not empty before calling $.parseHTML(data)
Here is your corrected example: http://jsfiddle.net/g9kksddk/15/

**Comment by manukieli** [comment]
Goooooooooooood.
Work like a charme.
:thumbsup: :thumbsup: :thumbsup: :thumbsup:

Thank you so mucho for your help.
