### ISSUE TITLE
Export with input Number

### ISSUE THREAD

**Issue by Gektor0508** [hhurz/tableExport.jquery.plugin#45]
I have an input type=number in my table and this plugin don't export the value. Is it possible to do this?

**Comment by hhurz** [comment]
Use the onCellHtmlData option for doing this. Here is an example: https://jsfiddle.net/9kfvge22/2
To export this table:

``` html
<table>
  <thead>
  <tr>
    <th>C1</th>
    <th>C2</th>
    <th>C3</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><input type="number" id="r1c0"></td>
    <td>B</td>
    <td>C</td>
  </tr>
  <tr>
    <td>D</td>
    <td>E</td>
    <td>F</td>
  </tr>
  </tbody>
</table>
```

use the folowing tableExport options:

``` javascript
function DoOnCellHtmlData(cell, row, col, data) {
  var result = "";
  if (data != "") {
    var html = $.parseHTML( data )

    $.each( html, function() {
      if ( typeof $(this).html() === 'undefined' )
        result += $(this).text();
      else if ( $(this).is("input") )
        result += $('#'+$(this).attr('id')).val();
      else
        result += $(this).html();
    });
  }
  return result;
}

$('table').tableExport({
  type: 'txt',
  onCellHtmlData: DoOnCellHtmlData}
);
```

In case you changed the input value to 5, the result would be:

```
C1,C2,C3
5,B,C
D,E,F
```

Note: The onCellHtmlData function depends on the content of the table you want to export. The DoOnCellHtmlData function shown above is just an example that meets the requirements of your question.

**Comment by Gektor0508** [comment]
Thanks a lot for the fast response. Everything you described worked fine for me.
