### ISSUE TITLE
Multiple tables input number

### ISSUE THREAD

**Issue by klust3r** [hhurz/tableExport.jquery.plugin#46]
I have a table with input number. Made it with this code https://github.com/hhurz/tableExport.jquery.plugin/issues/45

The problem is that when i try this code with multiple tables, there is an error Uncaught TypeError: Cannot read property 'length' of null.
I have tryed everything but it don't work. Plz help

**Comment by hhurz** [comment]
Please provide some more information about the problem. Which export format did you choose? 
Note: Multiple tables are only supported for PDF format.

**Comment by klust3r** [comment]
I use PDF format.

**Comment by klust3r** [comment]
This two functions (Number export and multiple tables) don't want to work together at the same time. Particular they work, but not together.

**Comment by hhurz** [comment]
Based on your detailed description I can't reproduce the problem. Here is a working example that includes both features: http://jsfiddle.net/fgm9k95k/

**Comment by klust3r** [comment]
I found the problem. If td is empty, it can't be exported with DoOnCellHtmlData function

**Comment by klust3r** [comment]
nevertheless thx fort help. Can be closed!

**Comment by hhurz** [comment]
To come along with an empty <td> tag, the data parameter should be checked if it is empty before passing it to jQuery's parseHTML function.

Thus the DoOnCellHtmlData function should basicly look like this

``` javascript
    function DoOnCellHtmlData(cell, row, col, data) {
      var result = "";
      if (data != "") {
        var html = $.parseHTML( data )

        $.each( html, function() {
          if ( typeof $(this).html() === 'undefined' )
            result += $(this).text();
          /*
          // add specific code depending on the content of the html table
          else if ( $(this).is("input") )
            result += $('#'+$(this).attr('id')).val();
          else if (...) {
          } 
          */
          else
            result += $(this).html();
        });
      }
      return result;
    }
```
