### ISSUE TITLE
colspan followed rowspan gives incorrect output when exporting to CSV

### ISSUE THREAD

**Issue by malthejorgensen** [hhurz/tableExport.jquery.plugin#47]
When exporting a table containing a `colspan` followed by a `rowspan` as a .csv-file, the rowspan will affect the wrong columns in following rows.

A table such as:

<table id="mixspans2">
  <tr>
    <td colspan="2">Section 1</td>
    <td rowspan="2">T</td>
    <td>Section 2</td>
    <td>Section 3</td>
  </tr>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
    <td>4</td>
  </tr>
</table>

HTML:

```
<table id="mixspans">
  <tr>
    <td colspan="2">Section 1</td>
    <td rowspan="2">T</td>
    <td>Section 2</td>
    <td>Section 3</td>
  </tr>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
    <td>4</td>
  </tr>
</table>
```

The table above will produce the following (incorrect) output from `doExport('#mixspans2', {type: 'csv'})`:

```
"Section 1",,T,"Section 2","Section 3"
1,,2,3,4
```

Here the cell-value `2` is moved one cell to the right from its expected position in the CSV-output.

**Comment by hhurz** [comment]
Fixed this issue. See last commit.
