### ISSUE TITLE
Wrong format for XLS?

### ISSUE THREAD

**Issue by dgambin** [hhurz/tableExport.jquery.plugin#49]
When I try to open my exported table in XLS format, I get the following:
- in LibreOffice it is opened in Writer instead of Calc
- in MS Office Excel 2010, it says "The file you are trying to open is in different format than specified by the file extension". 

In both cases, when opened in Calc/Excel everything seems fine. Is this a bug?

Btw, thanks very much for this piece of software, it is very useful :-)

regards, dejan

EDIT:

Ok, now I see this is because of the file being html and not real xls. I suppose this is somethng that cannot be avoided :-(

**Comment by hhurz** [comment]
Thanks for using this plugin ;-) You are right, the Excel output of TableExport is in HTML format which Microsoft introduced with Excel 2000. This makes it quite easy to convert a html table into an excel spreadsheet. Personally I would also prefere an output in BIFF or XML format, especially to export multiple tables into a workbook. But this is a bit out of my scope...

**Comment by LukeBrumfield** [comment]
These will not open in Google docs, or on Office 365. But they will work in Libreoffice, and it opened in calc. I cannot confirm any desktop version of office. 

One upon a time I had to work with creating a docx file in a program. It wasn't too complicated and we could reuse most of the xls code to create the xlsx version. If the project I am working on requires xlsx, I will get started on that.

**Comment by hhurz** [comment]
That would be great! TY

**Comment by Organizer21** [comment]
Just encountered this as well, Office 365 Desktop version is giving the error message that the format and extension does not match. The file could be corrupted or unsafe. It can be opened but the error causes some trust issues clearly for anyone using it who does not know why it is happening. Anyone progressed on this, sounded like LukeBrumfield was going to look to make a fix (but I see that's some months back already).

**Comment by Organizer21** [comment]
Not sure it could help but this one seems to have xlsx references and also credits something called SheetJS - js-xlsx: https://github.com/clarketm/TableExport

Just started using this through starting to use boostrap-datatables which apparently needs this for the export bit. Great plugin, thank you for maintaining it, might use for some custom export as well if I can get a grip around how things work :)

**Comment by hhurz** [comment]
Thanks for sharing this information. I just commited some code to support SheetJS as well. This lets you export a html table in xslx format (just table data, without any stylings)
