### ISSUE TITLE
Export to pdf does not support special characters

### ISSUE THREAD

**Issue by fr3sh** [hhurz/tableExport.jquery.plugin#50]
Hi 
Export to pdf does not support special characters like ą ś ć ż ł ó ę.
Is there a chance to fix it. Everything else working perfect :)

**Comment by hhurz** [comment]
This plugin uses [jsPDF](https://github.com/MrRio/jsPDF) as PDF producer. It is a known issue of that plugin, that it has no real unicode support. Only a few unicode characters (as german umlauts) are supported. Please see https://github.com/MrRio/jsPDF/issues/12 and https://github.com/MrRio/jsPDF/issues/115 for more information about that issue. 

I think this also answers your question from [here](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/87)

**Comment by bobisum** [comment]
Hi hhurz,

thanks for the info but I don't think that it's accurate - I have issue with german umlauts...

**Comment by hhurz** [comment]
@bobisum Can you decribe your german umlaut issue? Here you see a working example:

Original html table:
![htmloriginal](https://cloud.githubusercontent.com/assets/4164372/11691195/3fd44cf2-9e9a-11e5-82ad-7f2056307c11.png)

Exported pdf result:
![pdfresult](https://cloud.githubusercontent.com/assets/4164372/11691210/4ec76dde-9e9a-11e5-9cc1-3df5779494ba.png)
