### ISSUE TITLE
Unknow download extensions

### ISSUE THREAD

**Issue by MkeyGuzman** [hhurz/tableExport.jquery.plugin#52]
Hi everybody,
I have a issue with download extensions, I followed all the installations steps but when I want to export a table to whatever format I get an unknown file. anyone know what i´m doing wrong?.
I attached a picture whit my problem. Thank you.
![unknow file extension](https://cloud.githubusercontent.com/assets/15891851/11215088/295ada8c-8d0a-11e5-9d12-19ae15013f37.jpg)

**Comment by hhurz** [comment]
Looks like the base64 encoded export result cannot be saved as blob. In case a browser doesn't support HTML5 W3C saveAs(), the [FileSaver plugin](https://github.com/eligrey/FileSaver.js) is required.
Did you include this plugins? Which options did you set? Can you provide any example code?

**Comment by MkeyGuzman** [comment]
I tried  to check the example in the plugin website and even there I get the same problem with Firefox, Chrome and IE, I tried in another computer as well and i get the same problem. I did not know about FileSaver plugin I will give it a look, Thank you hhurz.
