### ISSUE TITLE
complex table thead rowspan colspan bug

### ISSUE THREAD

**Issue by zyz** [hhurz/tableExport.jquery.plugin#53]
<a href="https://github.com/hhurz/tableExport.jquery.plugin/issues/51">prev</a>

<table>
<thead>
<tr>
<th rowspan="2">Name</th><th colspan="2">detail1</th>
<th colspan="4">detail2</th><th colspan="4">detail3</th>
</tr>
<tr>
<th>d11</th><th>d12</th>
<th>d21</th><th>d22</th><th>d23</th><th>d24</th>
<th>d31</th><th>d32</th><th>d33</th><th>d34</th>
</tr>
</thead>
<tr>
<td>张三</td>
<td>11</td><td>12</td>
<td>21</td><td>22</td><td>23</td><td>24</td>
<td>31</td><td>32</td><td>33</td><td>34</td>
</tr>
</table>

export after

<table>
<thead>
<tr>
<th>Name</th><th>detail1</th>
<th>detail2</th><th>detail3</th>
</tr>
<tr>
<th>d11</th><th>d12</th>
<th>d21</th><th>d22</th><th>d23</th><th>d24</th>
<th>d31</th><th>d32</th><th>d33</th><th>d34</th>
</tr>
</thead>
<tr>
<td>张三</td>
<td>11</td><td>12</td>
<td>21</td><td>22</td><td>23</td><td>24</td>
<td>31</td><td>32</td><td>33</td><td>34</td>
</tr>
</table>

$("table").tableExport({
                type: "excel",
                //displayTableName: true,
                //tableName: "Demo",
                worksheetName: "Demo",
                fileName: "Demo"
            });

**Comment by hhurz** [comment]
Fixed this bug. Thanks for reporting it and for providing detailed information.

**Comment by nalindaDJ** [comment]
This issue is still there for PDF export.

**Comment by onrozcn** [comment]
<table>
<tr>
<td>col1</td>
<td>col2</td>
<td>col3</td>
<td>col4</td>
<td>col5</td>
<td>col8</td>
<td>col7</td>
<td>col8</td>
</tr>
<tr>
<td>x main1</td>
<td>x main2</td>
<td>x main3</td>
<td>x main4</td>
<td>x sub1-1</td>
<td>x sub1-2</td>
<td>x sub1-3</td>
<td>x sub1-4</td>
</tr>
<tr>
<td rowspan="4">y main1</td>
<td rowspan="4">y main2</td>
<td rowspan="4">y main3</td>
<td rowspan="4">y main4</td>
<td>y sub1-1</td>
<td>y sub1-2</td>
<td>y sub1-3</td>
<td>y sub1-4</td>
</tr>
<tr>
<td>y sub2-1</td>
<td>y sub2-2</td>
<td>y sub2-3</td>
<td>y sub2-4</td>
</tr>
<tr>
<td>y sub3-1</td>
<td>y sub3-2</td>
<td>y sub3-3</td>
<td>y sub3-4</td>
</tr>
<tr>
<td>y sub4-1</td>
<td>y sub4-2</td>
<td>y sub4-3</td>
<td>y sub4-4</td>
</tr>
</table>

$("table").tableExport({
type: "excel",
ignoreColumn:[3,4],
worksheetName: "Demo",
fileName: "Demo"
});

export after

<table>
<tr>
<td>col1</td>
<td>col2</td>
<td>col5</td>
<td>col8</td>
<td>col7</td>
<td>col8</td>
</tr>
<tr>
<td>x main1</td>
<td>x main2</td>
<td>x sub1-1</td>
<td>x sub1-2</td>
<td>x sub1-3</td>
<td>x sub1-4</td>
</tr>
<tr>
<td rowspan="4">y main1</td>
<td rowspan="4">y main2</td>
<td>y sub1-1</td>
<td>y sub1-2</td>
<td>y sub1-3</td>
<td>y sub1-4</td>
</tr>
<tr>
<td>y sub2-3</td>
<td>y sub2-4</td>
</tr>
<tr>
<td>y sub3-3</td>
<td>y sub3-4</td>
</tr>
<tr>
<td>y sub4-3</td>
<td>y sub4-4</td>
</tr>
</table>
