### ISSUE TITLE
How to export all row of table with many pages

### ISSUE THREAD

**Issue by cungtienkien** [hhurz/tableExport.jquery.plugin#54]
Dear,
Can you give me option to export all record with the datatable in pagination? I don't want to go to each page then export each to get full record. 
I use DataTables jquey 1.10.2
Thank you.

**Comment by hhurz** [comment]
Hi, the purpose of this plugin is to export existent content of a html table. Datatable builds for each page a new html table containig only the data of this particular page. Thus the data of the other pages are not available for tableExport when you export the table.
To export all data you could try to build a not visible table containing the complete content (withou pagination) and then export this table.

**Comment by cungtienkien** [comment]
Hi,
Is there any other way to do it because i think build one more table with many records will make program slower alot
Thanks

**Comment by hhurz** [comment]
If you have to deal with a lot of records, you should consider to export the data on server side. 
Even if I'd provide a callback function to get more table rows than are visible, all data would have to be fetched and sent to the browser to build the export file there. 
Anyway, I'm thinking about to provide such a callback mechanism in the near future...

**Comment by cungtienkien** [comment]
Ok, thank you for your help, i've used method to export another invisible table :dancers:

**Comment by atefBB** [comment]
Hey @cungtienkien ! Can you share some `code snippet` for your solution? I'm facing the same issue here.
