### ISSUE TITLE
issue with while loop tr

### ISSUE THREAD

**Issue by kalu8** [hhurz/tableExport.jquery.plugin#55]
hi, this is a great plugin, but I have the issue that after the while loop, I have another tr with the total of amounts, and when I made the export, excludes this last tr, I´ve already tried the: data-tableexport-display="always", and still not working... any idea?

**Comment by hhurz** [comment]
Where does the tr containing the total reside? If its outside of tbody, then it would not be exported. 
If this doesn't relate to you, could you provide an example of your table?
BTW: data-tableexport-display="always" only targets invisible cells.

**Comment by kalu8** [comment]
here is the example: 
[table-ex.txt](https://github.com/hhurz/tableExport.jquery.plugin/files/52879/table-ex.txt)

**Comment by kalu8** [comment]
I´ve already found the issue, I don´t know why my th is not displaying in the export, I changed to td and is working! t
