### ISSUE TITLE
Export table with Borders

### ISSUE THREAD

**Issue by Iamscalla** [hhurz/tableExport.jquery.plugin#56]
i wouldn't call this an issue, maybe my ignorance.
how do i export table with it borders?

**Comment by hhurz** [comment]
Which format you would like to export to? In case its xls format please have a look at my comments within this issue #35

**Comment by Iamscalla** [comment]
am exporting into pdf

**Comment by hhurz** [comment]
Actually borders are not exported to pdf automatically. You have to set it manually by using the `autotable: styles` option. See [jsPDF-AutoTable](https://github.com/simonbengtsson/jsPDF-AutoTable) for more details about styles. Example:

``` javascript
      $(selector).tableExport({type: 'pdf',
                               jspdf: {orientation: 'l',
                                       autotable: {styles: {fillColor: 'inherit', 
                                                            textColor: 'inherit',
                                                            fillStyle: 'DF',
                                                            lineColor: [0,0,0],
                                                            lineWidth: 0.1},
                                                   tableWidth: 'auto'}}});
```

**Comment by Iamscalla** [comment]
would try this n give a feed back

**Comment by maczdata** [comment]
it worked, thumbs up
