### ISSUE TITLE
Support for Secondary Table Header as Sub Data within the main Table

### ISSUE THREAD

**Issue by dontboyle** [hhurz/tableExport.jquery.plugin#59]
Would like to get permission to include the functionality to support his feature.

**Comment by hhurz** [comment]
Any Examples for what you plan to do? Feel free to open a pull request.

**Comment by dontboyle** [comment]
What I ended up doing for my personal gain was to extend the logic to parse sub tables (grids within grids) and export them to excel, but its just not as ... "nice" as I'd like it to be. So I'll be working on it and report as I get something more .. viable ;)
![image](https://cloud.githubusercontent.com/assets/8333350/13926035/945d5d54-ef58-11e5-9a50-8cb9e5291de5.png)
