### ISSUE TITLE
jsPDF

### ISSUE THREAD

**Issue by ngreis** [hhurz/tableExport.jquery.plugin#6]
Updated from original to yours, super update indeed!

But, hit a snag with pdf

the generated pdf is like this

http://prntscr.com/6hbcmj

Any tips?

Best regards

**Comment by hhurz** [comment]
The size of the pdf sheet seems not to be A4. I tested only that format. Did you change any jsPDF options? 
An other thing could be the DPI. TableExport tries to determine the DPI beore it calls jsPDF. But perhaps this is not working for you. You can try to set the new TableExport option 'dpi' manually, e.g. {type:'pdf',dpi:96} 
Usually modern browsers use a 96 dpi resolution. Finally the size (in mm) of the table in the pdf should be nearly identical to the size of the source html table.

**Comment by ngreis** [comment]
First of all.
Thx for the reply :P

Dont think i changed anyhting, heres the code, with the 96 param.

http://prntscr.com/6hm5rl

http://prntscr.com/6hm5jh

How to ajust the mm like you adviced? Oo 

Best regards

 Nuno Reis

edit:
used 175 to get the width right for the pdf.

seems the pdf gets the rows that are visible one the monitor, but sets that black part from the remaining table.

http://prntscr.com/6hmb5a

http://prntscr.com/6hmasv

the table is 50 records on that page, from witch 23 are visible and the others you have to scroll down to see them.
Seems that the non visible ones get blacked out.

(the spotted black was me altering the screenshot because of the data of the table.)

Is it normal?

**Comment by hhurz** [comment]
The scroll problem should be fixed by using the latest release version of htm2canvas. 

Regarding the black background I suggest to set the css background-color of your html table to white. 

You don't need to adjust the mm. jsPDF uses this unit per default. I mentioned the milimeters only to make clear that when you measure the size of the table in the pdf document, it should be more or less equal to the size of the source table. So don't care about it.

**Comment by ngreis** [comment]
I used the one on your zip file.
Not the latest?

Will try to check the black background byt making it white.

edit:
neither 0.4.1 nor the 05 alpha solved it.

Wil wait for it, for now will warn that only visible table is exported to png and pdf :P
