### ISSUE TITLE
Export a data attribute instead of the TD content

### ISSUE THREAD

**Issue by extqy** [hhurz/tableExport.jquery.plugin#60]
I would like of export the content of a data attribute instead of the TD content.
e.g.

``` html
<tbody>
   <tr>
       <td data-tableexport-content="Export this content">
       instead of this here
       </td>
   </tr>
</tbody>
```

And make the same thing with table head:

``` html
<thead>
   <tr>
      <th data-tableexport-title="Export this title">
       instead of this here
      </th>
    </tr>
</thead>
```

Thanks

**Comment by hhurz** [comment]
Thanks for your suggestion. Will have a look for it

**Comment by hhurz** [comment]
Done. You can use the new data attribute "data-tableexport-value" for th and td now

**Comment by extqy** [comment]
Thank you very much !
