### ISSUE TITLE
Table export for the 2nd time without refresh fails

### ISSUE THREAD

**Issue by aronmgv** [hhurz/tableExport.jquery.plugin#63]
Hey,

I am having the issue with exporting table for the 2nd time without refresh. It goes through nicely 1st time but for the second chrome reports problem with the file that it does not exists.. Tried PDF and CSV, same behavior. I did enable logging and it seems data get parsed correctly which makes me think the issue might be with saving it at users end..

I am using angular directive for doing that (as explained [here](https://medium.com/@darilldrems/angularjs-export-html-table-to-pdf-excel-or-doc-formats-bb741d06dfec#.uln9chtuf)). And I do have FileSaver included..

Any help will be appreciated.. thanks! Michal

**Comment by aronmgv** [comment]
Hey, you may close this one.. it was/is a Chrome Canary issue at the moment.. in other browsers it works as expected.

Thanks, Michal

**Comment by hhurz** [comment]
Hi, I like closing issues ;) Thanks for notifying.
