### ISSUE TITLE
Excel - delete the blank column

### ISSUE THREAD

**Issue by movmo232** [hhurz/tableExport.jquery.plugin#68]
Hi hhurz, 
first - thank you so much for the fork and your effort! :+1: 
This is more a question then a issue. :)

I use this table with a checkbox and the sort function. 

`<table id="table"
       data-toggle="table"
       data-toolbar="#toolbar"
       data-show-export="true"
       data-sort-name="stargazers_count"
       data-sort-order="desc">
    <thead>
    <tr>
        <th data-field="state" data-checkbox="true" data-tableexport-display="none"></th>
        <th data-field="key" data-sortable="true">Key</th>
        <th data-field="search" data-sortable="true">Search</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td data-tableexport-display="none"></td>
        <td> Key 2</td>
        <td>526</td>
    </tr>
    </tbody>
</table>
</div>
</body>`

When I export this table into excel I have the problem that the first colume is blank. So then my Idea was that i use your "data-tablexport-display="none". 

![image](https://cloud.githubusercontent.com/assets/11699409/13934499/ce46e6f2-efb2-11e5-97fc-34c37d321b14.png)

Have you a idea how to remove this blank row? Or the blank column - when I am not use both "data-tableeexport-display="none" funktions?

![image](https://cloud.githubusercontent.com/assets/11699409/13934611/6054cdfc-efb3-11e5-8b30-a8d3c1019617.png)

Thanks so much! :)

**Comment by hhurz** [comment]
Try to use  the `ignoreColumn` option. Example:

``` javascript
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>
  <script type="text/javascript" src="../tableExport.js"></script>
  <script type="text/javascript" src="https://raw.githubusercontent.com/wenzhixin/bootstrap-table/master/src/extensions/export/bootstrap-table-export.js"></script>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css" />
  <script type="text/javaScript">
  $(document).ready(function()
  {
    $('#table').bootstrapTable('refreshOptions', {
        exportOptions: {ignoreColumn: [0]}
    });
  });
  </script>
  </head>
  <body>
    <div class="container">
      <table id="table" 
        data-toggle="table" 
        data-toolbar="#toolbar" 
        data-show-export="true" 
        data-sort-name="stargazers_count" 
        data-sort-order="desc"> 
        <thead> 
          <tr> 
            <th data-field="state" data-checkbox="true"></th> 
            <th data-field="key" data-sortable="true">Key</th> 
            <th data-field="search" data-sortable="true">Search</th> 
          </tr> 
        </thead> 
        <tbody> 
          <tr> 
          <td></td> 
          <td> Key 2</td> 
          <td>526</td> 
        </tr>
      </tbody> 
    </table> 
    </div>
  </body>
</html>
```

**Comment by movmo232** [comment]
Thanks so much - now it works well!
