### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by simogeo** [hhurz/tableExport.jquery.plugin#7]
@hhurz : thanks for the nice library update. issue #4 is fixed.

I think it would be nice to have a minified version of the library. Using [closure](http://closure-compiler.appspot.com/home), your 19 kB library get compressed to 8 kB.

I point you to a python tool I wrote for my online Filemanager : https://github.com/simogeo/Filemanager/blob/master/utils/minify.py. The use is simple : 

> python ./utils/minify.py

It just take a given file and create a minified version (`tableExport.js` would become `tableExport.min.js`)

If you are interested to implement it, I can prepare and pull the script. Just let me know.

**Comment by hhurz** [comment]
Thank you for your suggestion and your offer. Cause I do not use python 2 any more I adapted your script for python 3

**Comment by simogeo** [comment]
You're welcome !
