### ISSUE TITLE
Issue with exporting

### ISSUE THREAD

**Issue by shrikantTudip** [hhurz/tableExport.jquery.plugin#71]
Hi,

I am using this extension and I have some questions:
1. when I choosing to export as PDF it looks like this:
[table (1).pdf](https://github.com/hhurz/tableExport.jquery.plugin/files/197327/table.1.pdf)

**Comment by hhurz** [comment]
HI, to answer this question I need more details. An example html would be helpfull too. 
As a first step you could take a look into the [jsPDF-AutoTable](https://github.com/simonbengtsson/jsPDF-AutoTable) documentation which is used as base when exporting to pdf with the tableExport plugin. There is a `overflow` style option, that could help with your problem.
