### ISSUE TITLE
does not extension of the file

### ISSUE THREAD

**Issue by atiladelcanton** [hhurz/tableExport.jquery.plugin#72]
Good evening , I'm using table - bootstrap plugin where you have the option to export , which uses your plugin , however when export command does not come the extension of the file :( only one file to download name and no extension .

**Comment by hhurz** [comment]
Hi, without more details i'm unable to help you. How did you inlude the plugin to your sources? which browsers do you use? Did you have a look on this working [bootstrap example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap.html). Also there is a [basic jsfiddle example](http://jsfiddle.net/e3nk137y/4144/) referenced from https://github.com/wenzhixin/bootstrap-table/issues/1765
