### ISSUE TITLE
.plugin extension changes filetype on mac

### ISSUE THREAD

**Issue by nevace** [hhurz/tableExport.jquery.plugin#78]
Hello,

I want to use bower to install this but the folder is recognised as a plugin file on my mac due to the .plugin extension. Will it be possible to rename it to tableExport-jquery-plugin for Bower?

Thanks,

**Comment by hhurz** [comment]
Hi, my version of tableExport.jquery.plugin is a fork of the project and I'm not able to rename it. See also [this issue](https://github.com/bower/bower/issues/120) for what is needed to unregister a bower package. There you will also find a remark I want to recite: 

> it is generally considered bad behavior to remove versions of a library that others are depending on

.
