### ISSUE TITLE
Export String to Excel with rows formatted as text

### ISSUE THREAD

**Issue by Anne623** [hhurz/tableExport.jquery.plugin#81]
Hi, All
  I have table text "0010",while I export to excel, in excel row it shows "10"。

```
HTML | EXCEL
00212704 | 212704
00212336 | 212336
00212251 | 212251
```

solution:
add `'mso-number-format:"@";'` for each td style when export excel.
or
add  `'mso-number-format:"@";'` in table, keep the same <td>style  when export excel.

**Comment by hhurz** [comment]
Next version will support mso-number-format style attributes. To apply it use either the new callback function `onMsoNumberFormat` which will be called when exporting to excel or use the new data attribute `data-tableexport-msonumberformat` while generating the html table you want to export. Example showing both methodes:

``` html
<table id="mytable"">
  <thead>
  <tr>
    <th>Number as text</th>
    <th>Number</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td data-tableexport-msonumberformat="\@">00212704</td>
    <td>00212704</td>
  </tr>
  <tr>
    <td>00212336</td>
    <td>00212336</td>
  </tr>
  <tr>
    <td>00212251</td>
    <td>00212251</td>
  </tr>
  </tbody>
</table>
```

``` javascript
$('#mytable').tableExport({type: 'excel', onMsoNumberFormat: function(cell, row, col) {
    return (row > 1 && col == 0) ? '\\@' : '';
  }
});
```

**Comment by CSGrandeur** [comment]
But how to add " data-tableexport-msonumberformat" option in <td> in bootstrap-table？
