### ISSUE TITLE
Export Json ie11

### ISSUE THREAD

**Issue by DebNathalie** [hhurz/tableExport.jquery.plugin#83]
I use tableExport.jquery.plugin-1.5.1 and I try the export in JSON via a boostrap-table on ie11 explorer and it doesn't work. Have you a solution ?

**Comment by hhurz** [comment]
Just successfully verified json export (w/o bootstrap) of the plugin using FF, Chrome and IE11. Without any details and/or source code examples I'm not able to help you.

BTW: There is an [bootstrap example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap.html) in the test folder of the plugin. Perhaps it helps...

**Comment by DebNathalie** [comment]
plugin used : 
tableExport.jquery.plugin-1.5.1/tableExport.min.js
bootstrap-table-1.9.1/dist/extensions/export/bootstrap-table-export.min.js

Here my source code : 
 <table class="table table-over"
                data-toggle="table" 
                data-url=myDataUrl
                data-pagination="true"
                data-sort-name="m_iEntityId"
                data-sort-order="desc"
                data-side-pagination="server"
                data-show-refresh="true"
                data-show-columns="true"
                data-show-export="true"
                data-export-types="['json','xml', 'csv', 'txt', 'sql', 'excel']"
                data-search="true" >

nothing in js

**Comment by hhurz** [comment]
Sorry, the information you provided isn't sufficient to give you some hint. Did you have a look into the bootstrap example I mentioned above? I'm not sure if this is rather more a bootstrap-table related question. Perhaps you ask your question in https://github.com/wenzhixin/bootstrap-table/issues too
