### ISSUE TITLE
Export file in Arabic language

### ISSUE THREAD

**Issue by HKhedr** [hhurz/tableExport.jquery.plugin#84]
I want to change Unicode export file to support Arabic..
I have column's Title "Header" in Arabic Language when I export file i get column like that 
' D \* 3 D 3 D ' D # 3 E ' D 9 F H ' F ' D E D ' - 8 ' \* ' D 1 E 2 ' D ( . . . 1 B E ' D E F 7 B ) ' D G ' \* A ' D A ' C 3 ' D , H '

My table is in Arabic language when export I get Hash code [Myjsfiddle](http://jsfiddle.net/Khedr/brjejv7z/4/)

Regards

**Comment by hhurz** [comment]
Your example shows that this is a pdf related problem. The excel export seems to work properly.

This plugin uses [jsPDF](https://github.com/MrRio/jsPDF) as PDF producer. It is a known issue of that plugin, that it has no real unicode support. Only a few unicode characters (as german umlauts) are supported. Please see https://github.com/MrRio/jsPDF/issues/13, https://github.com/MrRio/jsPDF/issues/12 and https://github.com/MrRio/jsPDF/issues/115 for more information about that problem.

**Comment by HKhedr** [comment]
Thank you.
Can I use another plugin support Arabic language !!!?

Regards

**Comment by hhurz** [comment]
I don't know an other plugin. If so I would use it myself ;-)

**Comment by mradmrad** [comment]
> Thank you.
> Can I use another plugin support Arabic language !!!?
> 
> Regards



> I want to change Unicode export file to support Arabic..
> I have column's Title "Header" in Arabic Language when I export file i get column like that
> ' D * 3 D 3 D ' D # 3 E ' D 9 F H ' F ' D E D ' - 8 ' * ' D 1 E 2 ' D ( . . . 1 B E ' D E F 7 B ) ' D G ' * A ' D A ' C 3 ' D , H '
> 
> My table is in Arabic language when export I get Hash code [Myjsfiddle](http://jsfiddle.net/Khedr/brjejv7z/4/)
> 
> Regards

Hello , did you find a solution for this issue ?

**Comment by hhurz** [comment]
Meanwhile there are two example files dealing with arabic language:

https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/arabicExcel.html
https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/arabicPdfmake.html

Perhaps this helps
