### ISSUE TITLE
export all row using tableExport

### ISSUE THREAD

**Issue by dragscorp88** [hhurz/tableExport.jquery.plugin#85]
Hi, Folks
Want to know is it possible to export all rows of data using tableExport? Currently i just found export the data based on the pagination. may be have any option to set?

Thanks

**Comment by hhurz** [comment]
Hi, I assume your question relates to export in pdf format. An export without pagination in pdf isn't possible cause pdf is a page oriented format. Or do you just want no table header after a page break?

**Comment by dragscorp88** [comment]
Hi, Thanks for reply.
Actually, i want to export in CSV format. currently, only got the data based on pagination.
What i need is export all data to CSV file.

**Comment by hhurz** [comment]
Are you exporting a bootstrap table? If so try to set the bootstrap option `exportDataType` with something like that:

``` javascript
$(document).ready(function()
{
  $('#table').bootstrapTable('refreshOptions', { exportDataType: 'all' });
});
```

In case this doesn't help and its realy a bootstrap table, please ask your question here: https://github.com/wenzhixin/bootstrap-table/issues

**Comment by dragscorp88** [comment]
currently, i export data on bootstrap table using tableExport but cannot for all data.
if we use bootstrapTable library so means need to load another js library? or no need?

**Comment by hhurz** [comment]
There is a working example: https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap.html or you have a look into the bootstap examples page: https://github.com/wenzhixin/bootstrap-table-examples

**Comment by xts-velkumars** [comment]
@hhurz, i'm using jquery datatable, i'm not using bootstrapTable.
please advice.

**Comment by weiweibupt** [comment]
@hhurz  I use       exportDataType: "selected"   to export the row I selected by pressing on the checkbox, and it works well. But  when I choose the full chenkbox in the head  in different pages, it only exports the current page.But what I want is to export all the pages that I have pressed the full checkbox.  Can you help me ?Thank you very much

**Comment by hhurz** [comment]
@velkumars This is a frequently asked question. See also issues #26, and #54. In short, tableexport needs ALL data on client side for export.
