### ISSUE TITLE
ignore colum not work when use data-field

### ISSUE THREAD

**Issue by dylan-lu** [hhurz/tableExport.jquery.plugin#88]
```
exportOptions:{
    displayTableName : false,
    htmlContent : true,
    ignoreColumn : ["projectName", "projectID"], //this code not make work
    consoleLog : true
}
```

**Comment by hhurz** [comment]
I suppose you are trying to export a bootstrap table. I just verified the `ignoreColumn` option with the plugins [bootstrap table test page](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/bootstrap.html). There the `ignoreColumn` array is filled with numeric columns indices `[0,1]` to exclude the first and second column from export. After changing the array to `['Rank','Date']` both columns were ignored successfully. Do the ignoreColumn names in your code exactly match (Case-sensitive!) with data-field names?

**Comment by dylan-lu** [comment]
thank you for your answer!
I have found the problem, cause i included the old version. 
It works after i use the latest version.
