### ISSUE TITLE
Unable to get whole table data including those paginated  for excel export 

### ISSUE THREAD

**Issue by ansarul99** [hhurz/tableExport.jquery.plugin#89]

**Comment by hhurz** [comment]
I would appreciate some details and/or example code

**Comment by rof20004** [comment]
I am testing this plugin today. I have a table with six pages, but only print first page, have some configurations to print all table pages?

Thanks and regards.

**Comment by hhurz** [comment]
@rof20004 Your question is a duplicate of issues #182 and #187. Thanks.
