### ISSUE TITLE
Export to excel not working on Office 2016

### ISSUE THREAD

**Issue by Knot1985** [hhurz/tableExport.jquery.plugin#90]
Hi

I start using your library some weeks ago and all worked fine, but now it doesn't work on Office 2016 when I try to export to excel. I experienced this issue starting 1 day ago.
If I try to export to csv or doc it works fine, and if I try to export to excel using Office 2013 it works fine to.
In Office 2016 the excel open with grey color and without cells and don't appear the notification that says "the file comes from another computer..."

$("#historico").tableExport({type:"excel",escape:"false"});

To open the  file I need to go to their properties and select the "unlock" option like the attached image
![capturar](https://cloud.githubusercontent.com/assets/20456240/16835641/8e6aa0c4-49b1-11e6-9e91-0c84f28b690f.PNG)

**Comment by hhurz** [comment]
Sorry for the delay in my reply. Nevertheless i have no glue what and why it is not working for you. I'm in doubt that the problem you describe ist specific to this plugin, but seems to me more related to office 2016. Casue I do not own office 2016 I'm not able to support you in this.

**Comment by Catchwa** [comment]
I see this when exporting a list of JIRA issues to Excel also. It seems that when you download an Excel file from the internet the blocked flag is set on the file. Excel 2016 seems to be silently blocking the file without notification.

There is a good summary here:
https://social.technet.microsoft.com/Forums/office/en-US/4a15e472-a265-4058-b439-7d79c2670817/xls-file-will-not-open-in-excel-2016-only-gray-view?forum=excel

**Comment by hhurz** [comment]
@Catchwa - Thanks for sharing this information!
