### ISSUE TITLE
Increasing Border thickness

### ISSUE THREAD

**Issue by maczdata** [hhurz/tableExport.jquery.plugin#91]
Good day, just wanna know how to increase the thickness of the table borders

**Comment by hhurz** [comment]
Sorry for the delay in my reply.  Assuming you want to export to pdf, try to set the [jsPDF-AutoTable](https://github.com/simonbengtsson/jsPDF-AutoTable) option `lineWidth`
Example: 

```
$('#tableID').tableExport({type:'pdf',
                           jspdf: {autotable: {styles: {lineWidth: 2.0, 
                                                        lineColor: 100}
                                              }
                                  }
                          });
```
