### ISSUE TITLE
ignoreColumn & ignoreRow does not work correctly with colspan & rowspan

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#93]
I have a table that uses rowspan & colspan. When i try to use the ignoreColumn & ignoreRow then dont work correctly with it. 

![original](https://cloud.githubusercontent.com/assets/5576379/17324970/b7c707fe-58c6-11e6-9dfc-6f21370bad10.jpeg)

![after_export](https://cloud.githubusercontent.com/assets/5576379/17324976/c127946c-58c6-11e6-944f-c82732052ba4.png)

I have used the simple code

$('.customreport').tableExport({
                            type: 'xls',
                            ignoreColumn: [4,7],
                            ignoreRow: [4,8,11,13,19,24,25]
}); 

Want to hide the columns with % using ignore columns but does not work correctly.

Also i tried using the field names (i.e. ["id", "name"]) to ignore columns & rows but was not successfull,
If anyone can help showing me how to use it.

Thanks in advance , also a very nice plugin

**Comment by hhurz** [comment]
Thanks for reporting this. There seems to be a bug when hiding colspaned columns. As soon as I get some time I'll have a closer look on it. Meanwhile, while building the table, you could try to set `data-tableexport-display="none"` for cells you want to hide during export.

**Comment by nshah143** [comment]
Thanks a lot for such a quick reply. data-tableexport-display="none" helped me hiding the columns not needed.
