### ISSUE TITLE
How to use the options

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#94]
I have tried using the options excelstyles , numbers , onMsoNumberFormat , worksheetName but applying them does not have any effects in the output when exporting to excel.
1. I wish to have bold heading in excel file 
2. there are numbers which should output as 1,357,805.84 but in excel it is like 1357805.84 even using the numbers option
3. using the worksheet name , does not show the sheet name when opening the excel.

a) Also i want to save the file on server also before providing it to user to download , is it possible ?
b) Also is it possible to save multiple tables in multiple sheets of an excel using the plugin ?

Any help would be appreciated. Thanks in advance

Edit : I see information provided about the plugin on the following link 
https://github.com/hhurz/tableExport.jquery.plugin

There are a lot of useful options provided by the plugin which can be very helpful to all the users but i miss the examples or proper usage & its benefits, which somehow does not let me take the full adavantage of the plugin. 
If there is more elaborate documentation about the plugin somewhere it can be very helpful.

**Comment by hhurz** [comment]
In general you are right to complain the lack of sufficient documentation. The only excuse i can offer is that I forked that abandoned plugin and adapted it to my needs (and some others on request). I had never time and aspiration to make a complete package out of it.

**Comment by hhurz** [comment]
Regarding worksheetName: this option works for me. See below.

Regarding onMsoNumberFormat: There was a bug when exporting MsoNumberFormats defined by onMsoNumberFormat or data-tableexport-msonumberformat. I fixed it within my last commit.
Example:

``` javascript
$('#MyTable').tableExport({type: 'excel', worksheetName: 'MSO-FORMATS', onMsoNumberFormat: DoOnMsoNumberFormat}));
```

``` javascript
    function DoOnMsoNumberFormat(cell, row, col) {
      var result = "";
      if (row > 0 && col == 0)
        result = "\\@";
      return result;
    }
```

``` javascript
   <table id="MyTable">
      <thead>
      <tr>
        <th>Number as text</th>
        <th>Number</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td data-tableexport-msonumberformat="\@">1,357,805.84</td>
        <td>00212704</td>
      </tr>
      <tr>
        <td>00212336</td>
        <td data-tableexport-msonumberformat="\#\,\#\#0\.00_ \;\[Red\]\-\#\,\#\#0\.00\ ">-212336</td>
      </tr>
      <tr>
        <td>00212347</td>
        <td>1357805,84</td>
      </tr>
      </tbody>
    </table>
```

![example](https://cloud.githubusercontent.com/assets/4164372/17381712/9a7b76c8-59cd-11e6-8639-951c4638ae8c.jpg)

**Comment by sangar82** [comment]
Can I have the excel headers of each table in bold??
I'm not able to achieve it. Thanks!!!

**Comment by hhurz** [comment]
@sangar82 In case you are exporting to Excel 2000 html format (xlshtml) and the header row of the original table is also styled bold, then you can use the ```mso.styles``` option. There is an [example](https://github.com/hhurz/tableExport.jquery.plugin/blob/master/test/cssExcel.html) which should help you

**Comment by sangar82** [comment]
@hhurz thanks for your reply!

I want to export to xlsx. This is my configuration

```js
$('table.toExportSheet').tableExport({
    type:'xlsx',
    number : {
        html : {
            decimalMark: ',',
            thousandsSeparator: '',
        },
        output : {
            decimalMark: '.',
            thousandsSeparator: '',
        },
    },
    mso: {
        fileFormat:'xmlss'
    }
});
```

**Comment by hhurz** [comment]
From readme.md:
> To export in XSLX format SheetJS/js-xlsx is used. Please note that the implementation of this format type lets you only export table data, but not any styling information of the html table.

When you [search](https://github.com/SheetJS/js-xlsx/issues?utf8=%E2%9C%93&q=bold) in the issues of SheetJS/js-xlsx there are many styling requests like yours, but no solutions for it :-(

**Comment by sangar82** [comment]
@hhurz i has been searching a solution for this along this week and I didn't found any solution. Thanks for your help and for your work! Very appreciate!
