### ISSUE TITLE
issues when export using png & pdf 

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#95]
I tried exporting multiple tables using png & csv & word but it does not work. But it works with excel & pdf.

Also when trying to export it using pdf , if i use it like 
$('.customreport').tableExport({
                                type: 'pdf',
                                fileName: 'MonthlyReport',
                                jspdf: {orientation: 'p',
                                   margins: {left:20, top:10},
                                   autotable: false}
                            }); 
Then this generates a pdf with only one table but with all css formatting.

But using it simply like this 

$('.customreport').tableExport({
                                type: 'pdf',
                                fileName: 'MonthlyReport',
                            }); 

shows all the tables in the pdf but without the css :(

Possibly it could be because except one table all other tables are hidden.
Which somehow works with excel using  data-tableexport-display="always" but not with others.

Any ideas ?

**Comment by hhurz** [comment]
When setting `autotable: false` jsPDF's addHTML function is used to export the first found table. In this case there is no multitable support. 
When using autotable, which supports multiple tables, there is almost no css export of the original table styling. But you can try to set the styles options `fillColor, textColor and fontStyle` to `inherit` to export at least some cell stylings. Perhaps this helps.

**Comment by nshah143** [comment]
Thanks for the reply , I tried as per your suggestion. But i found 2 issues with it

1) The fillColor in styles & alternateRowStyles does not work correctly with rowspan
2) using the inherit in fillcolor the pdf gets blank

the code used is 

$('.customreport').tableExport({
                                type: 'pdf',
                                fileName: 'MonthlyReport',
                                jspdf: {autotable: {
                                                    styles: {
                                                                fontStyle: 'normal',
                                                                rowHeight: 9,
                                                                fillColor: [247, 249, 229]
                                                            },
                                                    alternateRowStyles: {
                                                                fillColor: [244, 233, 222],
                                                            },  
                                                   }
                                       }
                            }); 

Attached is the image to have more idea about the problem
![autotable_color_issue](https://cloud.githubusercontent.com/assets/5576379/17362644/9fcaf0d4-5993-11e6-8b7d-6bae7f9d0615.png)
