### ISSUE TITLE
Multitable supports for PNG & CSV exports 

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#96]
Like it is possible for having multitable export to Excel & PDF , when trying to export multitables to PNG and CSV only the first table is exported correctly .

Is it possible to export multiple tables in other formats as well apart from Excel & PDF ?

**Comment by hhurz** [comment]
Does it make sense to export multiple tables into a single csv or png file?
Or is your intention to export multiple tables into multiple csv/png files? If yes, i think you could implement this within a loop that calls the plugin.
