### ISSUE TITLE
Possibility to export each table in new page of PDF export 

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#97]
Currently when exporting multiple tables to PDF , tables at the end of the page gets divided between 2 pages. some of the part is in the above page & some of it goes into the next page. This destroys the presentation of the table information in the PDF.

Is there some setting/option to overcome this issue ?

**Comment by hhurz** [comment]
There is jsPDF-Autotable option `pageBreak`. This option defines the behavior of the table when it will span more than one page. If set to 'always' each table will always start on a new page. Never tried it by myself. Perhaps it works for you: `autotable: pageBreak: 'always'`

**Comment by nshah143** [comment]
Thanks , it works :+1:
