### ISSUE TITLE
export to excel from html cannot set background colors 

### ISSUE THREAD

**Issue by nshah143** [hhurz/tableExport.jquery.plugin#98]
The original html tables is like this 

![original1](https://cloud.githubusercontent.com/assets/5576379/17363430/112fc2c8-5998-11e6-97de-0933cb66f45c.jpeg)

But when exporting to excel , cannot set any background colors or formatting.

![excel_bg_issue](https://cloud.githubusercontent.com/assets/5576379/17363451/2c5bdc62-5998-11e6-927d-b913bd1ef448.png)

How to set these , any ideas ?

**Comment by hhurz** [comment]
Perhaps this closed issue https://github.com/hhurz/tableExport.jquery.plugin/issues/35 helps...

**Comment by nshah143** [comment]
Thanks for the help. I checked the link that you have provided above and also i tried testing from the test folder provided in the source, the link "XLS (excelstyles)" in the index.html file.
But the link also exports xls file without any background colors or border-colors

I tested it on 2 environments but on none of them it works
1. Ubuntu 14.04 + LibreOffice Calc
2. Windows 8.1 + Open Office

I am not sure what i am doing wrong as from the link you provided , it seems it should have worked :(

**Comment by hhurz** [comment]
I think the only thing you are doing wrong is using LibreOffice/OpenOffice ;) I just checked it with this exported file (added .txt extension to be able to upload it):

[tableExport.xls.txt](https://github.com/hhurz/tableExport.jquery.plugin/files/401110/tableExport.xls.txt)

and opened it in Excel:
![excelstyles](https://cloud.githubusercontent.com/assets/4164372/17394571/354bd060-5a2a-11e6-8640-2fc3db205680.png)

**Comment by Silverbullet78** [comment]
hhurz, tell me please one thing. For example I've html-table like on your picture above (different cells styled with different colors). I can not get the same excel-table in xls-file. Tryed to put styles inside html-tags like in your example link and in outer css-file. Doesn't work!   Can you show simple example how to transfer css styles to xls-file? Thanks beforehand!

**Comment by hhurz** [comment]
Excel styles example (Keep in mind that you won't see colors in OpenOffice or LibreOffice!):

``` javascript
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>HTML table Export</title>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="../libs/FileSaver/FileSaver.min.js"></script>
  <script type="text/javascript" src="../tableExport.js"></script>
  <script type="text/javaScript">
    function doExport() {
      $('#excelstyles').tableExport({type:'excel',
                                     excelstyles: ['background-color', 'color',
                                                   'border-bottom-color', 'border-bottom-style',
                                                   'border-bottom-width', 'border-top-color',
                                                   'border-top-style', 'border-top-width',
                                                   'border-left-color', 'border-left-style',
                                                   'border-left-width', 'border-right-color',
                                                   'border-right-style', 'border-right-width',
                                                   'font-family', 'font-size', 'font-weight']});
    }
  </script>
</head>
<body>
  <a href="#" onclick="doExport()">Export to Excel</a>
  <table id="excelstyles">
    <thead>
    <tr>
      <th style="border: 2px solid #b60000; font-family: arial; font-size: 18px; font-weight: bold">C1</th>
      <th style="border: 2px solid #b60000; font-family: arial; font-size: 18px; font-weight: bold">C2</th>
      <th style="border: 2px solid #b60000; font-family: arial; font-size: 18px; font-weight: bold">C3</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td style="background-color:red">A</td>
      <td style="background-color:green">B</td>
      <td style="background-color:blue">C</td>
    </tr>
    <tr>
      <td style="border: 1px solid #000000;">D</td>
      <td style="background-color:yellow">E</td>
      <td style="border: 1px solid #000000;">F</td>
    </tr>
    <tr>
      <td style="background-color:green">G</td>
      <td style="background-color:blue">H</td>
      <td style="background-color:red">I</td>
    </tr>
    </tbody>
  </table>
</body>
</html>
```

**Comment by Silverbullet78** [comment]
Thanks a lot man! It works! Finally I got it! This plugin takes styles even from css-file. I don't know how but there is no need to put styles inside html-tags. ))

**Comment by vlcya** [comment]
Hi,

I am trying to export a html table to xlsx and keep the styling. i've tried your solution with excelstyles but with no luck...
do you have any ideas on how to do this?

Thanks

**Comment by hhurz** [comment]
The option mso.styles (formerly known as excelstyles) only works for the html format of Excel 2000. It has no effect for the xlsx format. This means that no styling settings can be exported in this format.
